### ISSUE TITLE
Please don't make JavaParser (or other classes) final

### ISSUE THREAD

**Issue by jimshowalter** [javaparser/javaparser#1044]
I saw your exchange in chat:

"Dwooll94 @Dwooll94 Jul 28 13:18
Hey, just a quick question, is there a particular reason why the JavaParser class is Final? If there were any way that it could not be final, that would be really convenient for use in projects alongside Mockito.

Federico Tomassetti @ftomassetti Jul 29 01:16
Having classes final is considered a best practice, unless they are specifically designed for extension (JavaParser is not). That said I understand your issue, however Mockito 2 or PowerMock could be able to handle final classes (e.g. https://github.com/mockito/mockito/wiki/What's-new-in-Mockito-2#mock-the-unmockable-opt-in-mocking-of-final-classesmethods)"

But you're doing yourselves a disservice by making them final, because it makes it difficult for another programmer to try something quick locally by subclassing, like experimenting with ways to fix https://github.com/javaparser/javaparser/issues/1039 (yes, SourceRoot isn't final, but suppose it was).

**Comment by jimshowalter** [comment]
When I started writing Java, I made everything private and final that could be made private and final, but eventually realized it just made testing and subclassing more difficult. It doesn't increase security, because anyone can use reflection to get to any field (unless blocked by Java's security manager, which almost nobody seems to use).

**Comment by ftomassetti** [comment]
Making a class non-final has a meaning: it tells others that the class has been designed to be extended. Most new languages create final classes by default (e.g., Kotlin does that). As the designers of a library we must decide what can be safely extended. We cannot just leave all classes as non-final because aside being a bad practice it could lead to users running into issues. That means they would open more issues here and it would lead to more work for us. We can consider making certain classes non-final but it requires choosing which ones makes sense to subclass, understanding for which goals, adding comments and advices, etc.

So which classes would you want to be non-final? Just JavaParser? Why? For which reason do you want to subclass it?

**Comment by matozoid** [comment]
Hmmm, I can imagine wanting to add more "parse" methods to it. If so, don't forget to tell us so we can add them for the next release!

**Comment by jimshowalter** [comment]
I've written Java for 15+ years. I'm pretty good at it. There's a dogma that classes should be final to indicate that they shouldn't be extended, but why shouldn't they? I get that a security module shouldn't allow extension, but why anything else? The designers of the classes aren't omniscient and can't possibly think of all of the ways someone else might want to use them. How exactly would users run into issues with non-final classes if you approve all commits? You're the gatekeepers. If someone extends a class, they can't get it into your trunk without your approval. That argument is specious. Making classes final makes them harder to test, harder to test new ideas on, and doesn't improve security (because they can always be circumvented by bytecode hackery). For example, I'm currently extending SourceRoot to try to make it parse multithreaded. If you'd made the class final, I would have to git clone your entire repo just to experiment. Currently I can just extend SourceRoot. But if I wanted to try an experiment in JavaParser, I couldn't do that.

Private members and methods are the same thing. Why not make them protected instead.

Somewhere along the line, we were mis-taught that locking things down improves code, but it actually just thwarts other developers' desire to play around with code. And playing around with code fosters innovation.

**Comment by ftomassetti** [comment]
In my opinion and in the opinion of many other experienced developers ideally a class should be either designed for extension or final.

The reason is that leaving a class not intended for extension open could lead to issue because the developer extending it would risk to face unexpected behaviors or run into difficulties trying to achieve what it wants too. This would lead to more issues. Over 600 issues have been opened for JavaParser and 150 for JSS. To make the problem sustainable we have to restrict the source of potential problems because otherwise we will enable to cope with all the requests.

> How exactly would users run into issues with non-final classes if you approve all commits? You're the gatekeepers. If someone extends a class, they can't get it into your trunk without your approval. That argument is specious.

Probably I did not explain it well before and I am sorry about that. The problem is not what would be committed to JavaParser, the problems lie in how users would use JavaParser. If we leave open more possibilities to write code that does not run as the user would expect that would lead to more errors in user code -> more disappointment for them + more work for us.

> Making classes final makes them harder to test, harder to test new ideas on, and doesn't improve security (because they can always be circumvented by bytecode hackery)

I have never expected to increase security. People are free to use bytecode hackery or reflection. However users that do so are typically users that know Java fairly well and can write their own code without running into troubles. This is not true for all JavaParser users: some of them are Java experts, others are novices.

Also, making a class final is an hint that the designers think extending that class should not be needed. Probably because the intended result can be obtained in another way. In some cases we could miss a new interesting usage that is not possible because of a class being final. In that case it is good if the developers talk to us so that we can help him ensuring there is no an already known alternative and if it is the case we can change a class from final to open, with a better understanding of how JavaParser is used.

I am not saying that all classes should be final. I am just saying that we should remove final where present carefully, considering the pros and cons and ensuring it makes sense to extend a particular class, without that leading to more issues for users and for us.

> Private members and methods are the same thing. Why not make them protected instead.

Also in this case I think it should be done if we have good reasons to do so. Also, subclassing is not the only way to reuse code, maybe we should support composition in some cases. I would suggest we focus on specific use cases and scenarios where you would need to remove the final keyword and we look into it to check what it is the best approach.

**Comment by DeepSnowNeeL** [comment]
While I agree a bit with both of you, when I encounter final classes and
want to try something, I just clone the repo and do the changes in it, if
you find it suits your needs after altering the existing thing, you can
even send a pull request, how wonderful !

**Comment by matozoid** [comment]
There's so much text here that I'm tempted to simply remove `final` everywhere so we can get on with more important stuff :-)

**Comment by jimshowalter** [comment]
It's your project. I was just trying to point out that while you may think locking things down is helping, it actually gets in the way of experimenting. Yes, I can clone the whole repo, except in the case of JSS now I also have to install and learn a new build system. All I wanted to be able to do is take SourceRoot, subclass it locally, and experiment with making it parse on multiple threads to speed it up. I can do that because SourceRoot isn't final. I can't do that with other classes. I can resort to copying just the classes I want locally and renaming them or some dorky thing to work around the finals, but why put me through that?

The thing about making members and methods private is that you wind up writing stateful code. I know JavaParser isn't thread-safe, because while trying to thread SourceRoot, at first I had just one JavaParser, and kaboom. But the funny thing is, you could have written JavaParser as a set of static stateless utility methods, which are inherently thread-safe, and passed in whatever state is needed. Then you could test the methods separately, much more easily. And the discussion of misusing JavaParser by subclassing it would be largely moot, because all that file would consist of is some methods that orchestrate calls to the utility methods. In effect, JavaParser, the class, would be no more complicated than the unit tests of the static utility methods. It's the difference between writing a Math object that encapsulates the left and right operands vs. a Math library that has a static multiply method that takes two parameters--the left and right operands.

**Comment by matozoid** [comment]
Uhuh, that's the thing with this library: it's pretty ancient, and was originally set up as a parser + a bunch of POJO's. Mutability all over the place. If we were to start over, this would not be how it would be done anymore. One of our contributors split off and did something more like that over here: https://github.com/ptitjes/jlato . We (I?) made a decision to keep JP like it is - last century's technology - and tighten it up as much as possible. It gets a lot of positive feedback on being easy to use, and I suspect that's partly because of this. None of it is very surprising or high tech. It's funny when other projects use JP's source as a test case because really, it's not very challenging code :)

Anyway, if you add issues saying "this class shouldn't be final because of X" and it's sensible, we'll just take it off. I personally don't see a reason to definalize JavaParser.java because really, it's mostly static helpers there.

**Comment by jimshowalter** [comment]
Fair enough. It's clearly a reasoned decision. I'll let you know if a final gets in the way.

**Comment by matozoid** [comment]
Cool! Thanks for all the feedback by the way - it's very valuable!
