### ISSUE TITLE
Add method to ImportDeclaration that returns class name for static imports

### ISSUE THREAD

**Issue by jimshowalter** [javaparser/javaparser#1052]
Otherwise to get the class name requires getName().replaceAll("[.][^.]+$", "").

**Comment by matozoid** [comment]
Name is qualified, can you look at its members to see if it's easy enough to get the info without regexes?

**Comment by matozoid** [comment]
Some background info: `ImportDeclaration` was subclassed by its four variants for a while during the version 3 alpha builds. These had more specific getters. Since we had several complaints about that being too complicated, I reverted it back to this single node type for version 3.

(Then someone complained that the four subclasses were missing :-( )

**Comment by jimshowalter** [comment]
What were the four subclasses?

If you added getImportedClassNameAsString(), it could return the imported class when non-static, and the class with the method being statically imported when static, and I could remove a regex.

**Comment by matozoid** [comment]
Have you looked at the members of `Name` as suggested? I'm pretty sure `getIdentifier` will get you the class and `getQualifier` the package.

The four types were modeled after this section in the JLS: https://docs.oracle.com/javase/specs/jls/se8/html/jls-7.html#jls-7.5 - I assume that will explain everything :-)

**Comment by jimshowalter** [comment]
Sorry, I'd missed your comment about name qualification. I'll take a look. Thanks!

**Comment by jimshowalter** [comment]
Worked perfectly. Thanks!

**Comment by matozoid** [comment]
Cool! Let us know if it worked

**Comment by matozoid** [comment]
Cool! I'll close this then
