### ISSUE TITLE
MethodCallExpr scope is null

### ISSUE THREAD

**Issue by cciollaro** [javaparser/javaparser#117]
### What I did

I was running the following code which is supposed to print out the `MethodCallExpr` in its own source:

```
public class MethodCallExprPrinter {
    public static void main(String[] args) throws Exception {
        FileInputStream in = new FileInputStream("src/MethodCallExprPrinter.java");
        CompilationUnit cu;
        try {
            cu = JavaParser.parse(in);
        } finally {
            in.close();
        }
        new MethodCallExprVisitor().visit(cu, null); 
    }
    private static class MethodCallExprVisitor extends VoidVisitorAdapter {
        public void visit(MethodCallExpr n, Object arg) {
            System.out.println(n.getName());
        }
    }
}
```

The output was:

```
parse
close
visit
println
```

Note that `getName` was excluded.
### What I found

I looked into `VoidVisitorAdapter.visit(final MethodCallExpr n, final A arg)`. It seems that the relevant bit is:

```
if (n.getScope() != null) {
    n.getScope().accept(this, arg);
}
```

I confirmed that the `Node` corresponding to getName is a `MethodCallExpr` with `getScope() == null`. This might be completely unrelated... it's my best guess though.

**Comment by cciollaro** [comment]
If it's my original code that has the bug let me know that too, I was going out on a limb with the scope thing.

**Comment by ptitjes** [comment]
Hi @cciollaro!

The problem comes from the fact that the call `n.getName()` is an argument of the call to `println`. Thus in order to catch it in your visitor, you have to let the visitor process the `println` call recursively.

For this to happen, just add

```
            super.visit(n, arg);
```

at the end of your `void visit(MethodCallExpr n, Object arg)` implementation.

Do not hesitate to ask more questions!! Also you can query us on the chat room.

If you don't mind, I'll close the ticket.
