### ISSUE TITLE
JSON/XML/YAML back to AST

### ISSUE THREAD

**Issue by EndruK** [javaparser/javaparser#1280]
Hi, is there a way to parse the text representation back to an AST?

**Comment by matozoid** [comment]
Nope, they are only meant for visual inspection. Try using a proper serialization library like jaxb or so.

**Comment by matozoid** [comment]
Okay, I tried with JAXB and YamlBeans, and they both have trouble. JAXB because everything needs annotations, and YamlBeans because it doesn't understand the code style very well. So your best chance to serialize/deserialize is the parser and the pretty printer (although that is not exact with comments) or using the lexical preserving printer (although that has some bugs) or you can print the tokenrange (although that is only built when parsing and never changed.)

:-/

**Comment by EndruK** [comment]
Ok, nevertheless thank you for the fast answer :)

**Comment by matozoid** [comment]
If you want to see this improved, do open an issue :-)
