### ISSUE TITLE
Parent node somehow gets lost when node is added to a NodeList

### ISSUE THREAD

**Issue by malteskoruppa** [javaparser/javaparser#1303]
I stumbled upon a very weird problem in my code. One of those which really make you sit staring at your screen for a long time, aghast, going "Huuuuuuh? Whaaat? Whyyy? That's totally weird!". :wink: 

Upon a lot of debugging work, I found out that the reason seems to be that parent nodes of nodes are lost when they are added to a NodeList, and wrote a minimal example that demonstrates the problem. Consider:

```
CompilationUnit cu = JavaParser.parse("class A { public int a; }");
FieldDeclaration dec = cu.getType(0).asClassOrInterfaceDeclaration().getMember(0).asFieldDeclaration();
System.out.println("Parent of dec is present: " + dec.getParentNode().isPresent()); // true
NodeList<BodyDeclaration<?>> list = new NodeList<>();
list.add(dec);
System.out.println("Parent of dec is present: " + list.get(0).getParentNode().isPresent()); // false !?
```

As you can see, we parse a simple piece of code and obtain a reference to the node that represents the field declaration of `a`. We call this declaration `dec`.
First we confirm that `dec` indeed has a parent node, as expected.
Then we add `dec` to a NodeList. We retrieve it back from the NodeList, and again check whether it has a parent node: But now the parent node has gone. :confused: 

Is this behavior intended?
If no, could you fix this problem? :smiley:
If yes... could you explain why? What would be a good workaround? For now, I'm using a normal Java List instead of JavaParser's NodeList as a workaround.

**Comment by malteskoruppa** [comment]
One more thing that I forgot to mention (even though it may be clear): The problem is that the node itself is modified just by adding it to the NodeList. In other words, if we add the following code after the code snippet above:

`System.out.println("Parent of dec is present: " + dec.getParentNode().isPresent()); // false
`

...then we see that the node `dec` really has no parent anymore, simply because it was added to the NodeList at one point. The very same code that returned `true` earlier now returns `false`, due to the statement `list.add(dec);` which (surprisingly) modifies `dec`.

**Comment by matozoid** [comment]
There's an explanation for that :-) Two things:
- when a node that is already in an AST is put into some other place in the same or another AST, JavaParser will try to keep the AST consistent by removing it from it's previous spot by removing it from the parent's children list and unsetting the parent node. If it is not an optional node it will fail. A node cannot be in two places at once because it can have only one parent. Always consider if this is really what you want, or if you want to `.clone()` the node before adding/setting it.
- a `NodeList` is not a `Node` and cannot be a parent. The elements in the `NodeList` get the same parent as the `NodeList` itself. Since your `NodeList` doesn't have a parent, this is the parent that your node got: no parent.

In general JavaParser does its utmost to avoid an inconsistent AST, which is quite a challenge because the whole thing is mutable.

Does this help?

**Comment by malteskoruppa** [comment]
I had a feeling something like this might be the case. That certainly helps, and it's really good to know!

Thanks a lot for your kind support, as usual. :smiley:

**Comment by matozoid** [comment]
No problem!
