### ISSUE TITLE
Static nested class not visited or returned as ClassOrInterfaceDeclaration

### ISSUE THREAD

**Issue by markjohndoyle** [javaparser/javaparser#1313]
I've only just started using JavaParser but I think I've followed the examples correctly.

That said, I have an interface that has a static nested class called `KeepAliveData` that doesn't seem to appear in the child types (of the compilation unit) after parsing the source file. It's also not visited by visit(ClassOrInterfaceDeclaration n, Void arg), presumably because it's not in the node tree.

An example of the class is available here:
[url](https://github.com/markjohndoyle/native-socket/blob/master/src/main/java/org/mjd/nativesocket/NativeSocket.java)

I'm using the visitor methods but I also checked the child node list to see if it appeared as a node in the compUnit as follows:
```java
compUnit.getTypes().stream().filter(type -> type instanceof ClassOrInterfaceDeclaration).
                                       map(type -> (ClassOrInterfaceDeclaration) type).
                                       collect(Collectors.toList())
```

Javaparser version: 3.5.9 (also tried 3.5.3, 3.5.0 and 3.4.4)
JDK version: 8
OS: Linux

**Comment by matozoid** [comment]
Hi! Here's what is happening:
- `CompilationUnit#getTypes` gets only the top level types, so that's only `NativeSocket` here
- I'm not sure what happened to your visitor since you've not shown the code. Here is a working one:
```java
        cu.accept(new VoidVisitorAdapter<Void>() {
            @Override
            public void visit(ClassOrInterfaceDeclaration n, Void arg) {
                System.out.println(n.getNameAsString());
                super.visit(n, arg);
            }
        }, null);
```
Maybe forgot to call super?
- here's a simple way to get all the classes in the file: `cu.findAll(CompilationUnit.class)`.
- if you like to inspect how the AST is constructed, try something like this: `System.out.println(new YamlPrinter(true).output(cu));`

**Comment by markjohndoyle** [comment]
Hi!

It was a missing super call. I was sure it was something stupid I was doing, especially since there was a suspicious absence of this type of question on this page.

Thanks again, much appreciated!
