### ISSUE TITLE
Get the primary class of a compilation unit

### ISSUE THREAD

**Issue by cunhazera** [javaparser/javaparser#1341]
Is there anyway to create an instance of ClassOrInterfaceDeclaration from a CompilationUnit?
Today, I'm doing this: `ClassOrInterfaceDeclaration clazz = JavaParser.parse(file).getClassByName(name)`
But to do this, I'm having to get the file name and remove the extension.

What do you guys think about including something like this:
``` java
ClassOrInterfaceDeclaration clazz = JavaParser.parse(file).asClass();
```
or
``` java
CompilationUnit compUnit = JavaParser.parse(file);
ClassOrInterfaceDeclaration clazz = new ClassOrInterfaceDeclaration();
clazz.setInstance(compUnit); // setInstance is just a stupid name here to demonstrate the idea :)
```

**Comment by matozoid** [comment]
So, the question is... "How can I let JP create a public class with the name of the file minus `.java`"?

I was thinking of creating a method to "get" this class, not create, but I guess we can add that one as well.

This of course depends on the availability of the file name, so the "create" method could throw an exception (since it's your fault for not having parsed from a file.) The "get" method returns optional, since it's quite possible that the class is not defined in the file.

Will have to consult the JLS for the right way to refer to this type of class. "main class" or so?

**Comment by cunhazera** [comment]
I think I didn't express myself in the best way.
I just want to have a ClassOrInterfaceDeclaration with the value I got from the parse without having to use the `getClassByName`, because when I load my java files dynamically I don't know the class name, only the file name.

Let me show you what I'm doing:
``` java
            // first I get all java files in the project
            List<Path> javaFiles = Files.find(project.getBasedir().toPath(),
                    Integer.MAX_VALUE, (path, basicFileAttributes) -> path.toFile().getName().endsWith(".java"),
                    FileVisitOption.FOLLOW_LINKS)
                    .collect(Collectors.toList());

            for (Path path : javaFiles) {
                File file = path.toFile();
                // substring to remove the .java
                String name = file.getName().substring(0, file.getName().indexOf("."));
                ClassOrInterfaceDeclaration clazz = JavaParser.parse(file).getClassByName(name).get();
            }
```

So I was thinking about this option to remove the necessity to substring the name of the file when I use the `getClassByName` method.

**Comment by matozoid** [comment]
So you're saying you are interested in "get", not "create"? I can't see another difference. If there is, please say so :-)

Anyway, I'll build both, they both seem useful.

**Comment by cunhazera** [comment]
I think "get" is the right word.

Thank you @matozoid

**Comment by matozoid** [comment]
> If and only if packages are stored in a file system (§7.2), the host system may choose to enforce the restriction that it is a compile-time error if a type is not found in a file under a name composed of the type name plus an extension (such as .java or .jav) if either of the following is true:
> 
> The type is referred to by code in other ordinary compilation units of the package in which the type is declared.
> 
> The type is declared public (and therefore is potentially accessible from code in other packages).
> 
> This restriction implies that there must be at most one such type per compilation unit. This restriction makes it easy for a Java compiler to find a named class within a package. In practice, many programmers choose to put each class or interface type in its own compilation unit, whether or not it is public or is referred to by code in other compilation units.
> 
> For example, the source code for a public type wet.sprocket.Toad would be found in a file Toad.java in the directory wet/sprocket, and the corresponding object code would be found in the file Toad.class in the same directory.

Wonderful how they can talk about a very specific type of class without giving it a name :-/

**Comment by matozoid** [comment]
Oh, @cunhazera , if you're doing things with source files in a source directory, you can take a look at the `SourceRoot` class.

**Comment by matozoid** [comment]
I want to call it "main class" but that would imply that it has a `main` method. Maybe "public class" but it doesn't have to be public, and inner classes can also be public, so it's not specific enough. I'll go for "primary class" - but it can also be another type like an enum. So getting it will be "getPrimaryType" then. I'll add `createPrimaryClass` because that seems to be the common case, and `createPrimaryType` where you can pass your own type. Let's see...

**Comment by matozoid** [comment]
I just realised there is not much point to the create methods since when you know the filename, there is probably a class in that file already.

**Comment by matozoid** [comment]
Hey @UHDante - as you may have realised it's a good idea to open a new issue instead of adding to a previously closed one :-) I'll delete it here, okay?
