### ISSUE TITLE
Continuous parsing.

### ISSUE THREAD

**Issue by artur-shaik** [javaparser/javaparser#136]
Does we have continious parsing or is it in the plan, that will give ability to parse files, even with errors?

**Comment by ftomassetti** [comment]
I think that writing an error-tolerant grammar is in general quite difficult, especially for a grammar quite ambiguous as the Java one. However we could introduce some functionality in this sense. We use JavaCC for the parser and here there is some information on error recovery: https://javacc.java.net/doc/errorrecovery.html

**Comment by talios** [comment]
I've not actually played with it too much, but I wonder how some form of RxJava integration could work here - maybe not in exactly the way @artur-shaik maybe thinking - either as a direct part of javaparser or a separate artifact/project ( so as to not tie an RxJava dependency to the core library ).

One could have say an `Obversable<CompilationUnit> observeCompilation(File file)` , which whenever the `file` changes ( file watchers, polling, ... ) the parser gets executed and a new `CompilationUnit` instance is emitted.

Rather than refer to it as _continuous parsing_ you'd call this _reactive parsing_ - subscribe to compilation events and process the results down a reactive flow.

That could be quite powerful.

**Comment by ftomassetti** [comment]
Well, if you are interested in that I wrote an incremental Java parser (https://github.com/ftomassetti/JavaIncrementalParser). I have not played with it much but it should be able to parse a reasonable amount of Java 7 code. It is written in Scala using the papa-carlo library for incremental parsing.

**Comment by artur-shaik** [comment]
Ok, thanks for link to javacc docs. I played with those error skip codes, and I see that there is ability to catch ParseException and skip some tokens until semicolon or close braces. This method allow skip erroneous lines or may be blocks. Withal we could collect all catched exceptions to report it later.

What about @talios said. Sounds powerful and complex :smile: . For now I wish to just have ability to   parse whole class as it has no errors.

**Comment by wsdjeg** [comment]
mark
EDIT:https://github.com/artur-shaik/vim-javacomplete2/issues/185

**Comment by matozoid** [comment]
A start has been made on this.

**Comment by wsdjeg** [comment]
Nice! And thanks for your work.

**Comment by matozoid** [comment]
You can track it under this label: https://github.com/javaparser/javaparser/labels/error%20recovery

**Comment by artur-shaik** [comment]
@matozoid , thank you very much for mention it. I'm quite busy now, so I can not track contributions related to this field.
I will try to check it later.

**Comment by matozoid** [comment]
Check out https://matozoid.github.io/2017/06/11/parse-error-recovery.html
