### ISSUE TITLE
Consider serialVersionUID as field

### ISSUE THREAD

**Issue by cunhazera** [javaparser/javaparser#1375]
When I call `clazz.getFields()` it includes serialVersionUID.

Is it useful?

**Comment by matozoid** [comment]
Hi! Do you mean: the symbol solver should be able to use this field?

**Comment by cunhazera** [comment]
I mean stopping returning it as a field. I don't think it's useful to have it in my list of fields from my class.

**Comment by matozoid** [comment]
What is clazz here?

**Comment by cunhazera** [comment]
An instance of ClassOrInterfaceDeclaration

**Comment by matozoid** [comment]
Okay, so consider that the task of JavaParser is to take source code and give it to the user as a tree. If the source code contains a `serialVersionUID`, that should be in the tree because, well, it is in the source. Imagine if someone wanted to write a tool to remove all `serialVersionUID`s from the source code. If JP ignored `serialVersionUID`, that tool could not be built.

What are you building? Are you looking at fields and taking some action? Maybe I can help a little.

**Comment by cunhazera** [comment]
I'm scanning all my fields em checking which have some specific annotation. But it's ok, I can remove it with no problems. Assuming the main purpose of JP it makes sense to parse the serialVersionUID

**Comment by matozoid** [comment]
Alright, I guess serialVersionUID never has that annotation so it should be easy :-) Good luck!
