### ISSUE TITLE
Document the meaning of arraysAnnotations in ReferenceType

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#139]
[ReferenceType](https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/ast/type/ReferenceType.java) has one field named `arrayAnnotations`. I think we should document it, because I cannot remember what it does without looking at the grammar. Is that the weird thing deprecated since Java 1.1?

**Comment by jgesser** [comment]
​​
It is really weird. I didn't knew it was possible, I had to look at the JLS
to be sure. Actually it is new, since Java 1.8 it is possible to declare
Annotations between the dimensions of an array declaration, as can be seen
below.

public class Test {

```
@Target(ElementType.TYPE_USE)
@interface Ann {

}

// HERE
int @Ann [] @Ann [] array;
```

}

Maybe a new type of node could be created to carry the real positions of
these Annotations.
Instead of ReferenceType have a list of Annotations and the arrayCount
field, it would have just a list of this new node: Dimension.

R​egards​,

Julio Vilmar Gesser

2015-05-14 21:28 GMT+01:00 Federico Tomassetti notifications@github.com:

**Comment by ftomassetti** [comment]
First of all it is an honour to get an answer directly from Julio :)

Then yes, I agree that we should probably create a new Node representing the array modifier (`[]`) and the associated annotation, if any.

In the meantime we should document the meaning of the existing field.

What do you think?

**Comment by jgesser** [comment]
Sure. Document the entire AST was an open issue from the original project
that I could never solve alone.

Atenciosamente,

Júlio Vilmar Gesser

2015-05-15 9:28 GMT+01:00 Federico Tomassetti notifications@github.com:

**Comment by ptitjes** [comment]
Guys, I have that as a proposition already: https://github.com/javaparser/javaparser/issues/112
:p

**Comment by ftomassetti** [comment]
While I agree that your suggestion makes sense, what I am proposing is a smaller change: just create a new node representing the array modifier (`[]`) and the corresponding annotations.

For now I will send a patch for document the existing behavior.

**Comment by ptitjes** [comment]
@ftomassetti Well this is exactly what I proposed: "ArrayType would denote only one level of array and hold the annotations for the (single-level) array type."

**Comment by ftomassetti** [comment]
I do not think so: you are proposing to make ArrayType extends ReferenceType, which could make sense imho but it is a major change. I am instead proposing of creating a class, let's call it ArrayModifier:

```
// Represent an array modifiers (e.g., []) and the associated annotations
class ArrayModifier {
  List<AnnotationExpr> annotationsOnTheSquareBrackets;
}

class ReferenceType {
  // etc
  // remove private int arrayCount;
  // remove private List<List<AnnotationExpr>> arraysAnnotations;
  List<ArrayModifier> arrayModifiers;
}
```

What I would like to understand is if currently we are guaranteeing that arrayAnnotations.size() == arrayCount. We need that because otherwise we do not know which annotations are associated to which modifiers. In other words:

`Foo @Ann1 [] [] []  @Ann2 [] [] foo;`

How long is arrayAnnotations in this case? Is 2 or it is 5? I want to figure out that and document it.

**Comment by ftomassetti** [comment]
Ok, at least `arraysAnnotations.size() == arrayCount`

**Comment by ptitjes** [comment]
As of now "arraysAnnotations.size() == arrayCount" is enforced (only :p) by the grammar.

As for ArrayType, I did not choose that at random. This follows the specification. Adding a "ArrayModifier" is kinda a hack and does indeed modify the API. So if we modify the API, we should do it in the right way, that is IMO, following the spec. Please consult the JLS.

**Comment by ptitjes** [comment]
Also, @ftomassetti, using a ArrayType naturaly encodes the direction of the arrays.

`A[][]` is an array type of `A[]`s, which is itself an array type of `A`s. Hence the type `ArrayType(ArrayType(ClassOrInterfaceType("A")))`.

In contrast, see how confusing it can be to figure out what direction should a `List<ArrayModifier>` should be read... (the order is important when there are annotations)

**Comment by ftomassetti** [comment]
@ptitjes I specified twice that I agree with your solution (no need to tell me "Please consult the JLS."). I am just specifying that my proposed solution was different because you misunderstood it.
So said, I think that your solution, while, again, being nice, is a major change. I proposed to consider doing a smaller step toward something more understandable, just for the sake of reducing the impact on existing users.

I think it is fundamental to start documenting the current solution, because this feature is new and not so commonly used, so I think it would be confusing for many users. I created a patch for that (#142).

**Comment by jgesser** [comment]
According to the JLS (https://docs.oracle.com/javase/specs/jls/se8/html/jls-4.html#jls-ArrayType)  the @ptitjes' proposal is almost right in my opinion. 

```
ArrayType:
    PrimitiveType Dims
    ClassOrInterfaceType Dims
    TypeVariable Dims
Dims:
    {Annotation} [ ] {{Annotation} [ ]}
```

It will be really necessary to define an `ArrayType` node, but it should not be linked to another of the same type to define an array of array of something.
It should have a componentType and a list of brackets, called Dim in the specifications, I presume it means Dimension.

`Foo[][]` instead of `ArrayType(ArrayType(ClassOrInterfaceType("A")))` would be `ArrayType(ClassOrInterfaceType("A"), Dimension, Dimension)`

This way I think will be better to conserve the position of each braked and its annotations.
And also easier  to manipulate the AST.

So, what @ftomassetti has proposed can be the first small step to reach the final solution.

**Comment by ptitjes** [comment]
I close this as this as been merged.
