### ISSUE TITLE
Ways to free memory?

### ISSUE THREAD

**Issue by AwesomeLemon** [javaparser/javaparser#1391]
Hello.
I'm using JavaParser and JavaSymbolSolver when creating a dataset by processing thousands of git repos.
My problem is that the RAM consumption increases the longer my dataset-creating-program runs until there's no more RAM left.
I found that calling `JavaParserFacade.clearInstances();` helps by clearing the cache, about which I don't really care since I have already moved on to processing of the next project.
So I wonder if there're other similar methods for some other caches, or generally any ways to clear memory?

**Comment by matozoid** [comment]
@ftomassetti can comment on the caches.

There's another option: you can look at `ParserConfiguration` and check to see which features you don't need, then turn those off.

**Comment by AwesomeLemon** [comment]
Thanks for the pointer, I've set only lexical preservation to false, since all other options seem to impact comments, which I need.

**Comment by ftomassetti** [comment]
I could find these caches:
* in PhantomNodeLogic
* in JavaParserTypeSolver (3 caches)
* in SourceRoot
* TypeInferenceCache
* in JavaParserFacade (2 caches)

**Comment by ftomassetti** [comment]
I would say: let's see which ones are causing an issue and add methods to reset them

**Comment by dhardtke** [comment]
What I find problematic is that there is no way not to use `JavaParserFacade.instances` since `JSS`s internal classes use `JavaParserFacade.get()` internally :(

**Comment by matozoid** [comment]
For `SourceRoot`: read the Javadoc carefully and you'll be able to avoid the cache. Also: the cache is scoped to the lifecycle of `SourceRoot`, so once it gets garbage collected the cache is gone. Meaning: regularly instantiate a new one if the cache is bothering you.

**Comment by daanschipper** [comment]
I'm currently investigating the problem while parsing many files with JavaParser. I'm running it against a project with ~290 source roots and ~20k .java files. 

My findings are:
- The cache in `SourceRoot` is not used since I'm calling `SourceRoot.parseParallelized`. By invoking `tryToParse` or `save` (manually adding a newly created Java file) will add the path to the file together with the compilation unit to the cache. 
- Since I'm 'scraping' java files, the caches `cacheWithLambdasSolved` and `cacheWithoutLambdasSolved` in `JavaParserFacade` are memory hogs. These caches are present to see if the type of a node is already known, if so return it otherwise calculate it. In my case the latter is (almost) always true. Regarding performance, it is an IdentitityHashMap, so retrieving and storing takes O(1), this should not have a very large impact. It would be great if these caches can be disabled.
- The caches in `JavaParserTypeSolver` can be of use if a certain type is requested often, but of course this can quickly grow. More on that in the following section.


I've profiled the execution of my program with VisualVM, this is after ~45 minutes of parsing:
- Memory usage is steady at 3.1 GB, which is fine by me. I did not bother to further look into this
![screen shot 2018-05-15 at 15 41 35](https://user-images.githubusercontent.com/2778477/40060295-8c87b7c8-5856-11e8-9345-135103989c94.png)
- This screenshot shows (self time)(https://stackoverflow.com/questions/14626475/visualvm-and-self-time], aka the time spent in a method. 
![screen shot 2018-05-15 at 15 44 52](https://user-images.githubusercontent.com/2778477/40060461-f6a1eeb2-5856-11e8-8ca6-b4ba728a929a.png)
  - What is really interesting is that the `Provider.provider()` method, why does that method occupy soooo much time? I have no clue what it exactly does even. 
  - And what is happening in `ReflectionTypeSolver.tryToSolve()`?

**Comment by ftomassetti** [comment]
Great stuff @daanschipper ! Thank you for your work.

If my memory is right some caches are not just nice for performance reasons but are really needed because there are situations in which you have a sort of circular dependency in type resolution. For example, to understand the types used in lambda you need to figure out which method is called. But to figure out which method is called you need to figure out the type of the parameters _including_ the parameter represented by the lambda. You have this sort of things which are... unpleasant to deal with.

**Comment by ftomassetti** [comment]
Regarding `Providers.provider()`: I do not see a method there taking no parameters. Dies the tool list the methods as having no parameters even if they have them?

Regarding `ReflectionTypeSolver.tryToSolve()` it try to see if there is a class with a given name. By default it tries to solve only stuff in the java or javax packages. It uses reflection and... when there is qualified name it does not know what is a top class and what is an inner class so.... it just tries. If you try to resolve `com.foo.MyClass.MyInnerClass` it will first try to load `com.foo.MyClass.MyInnerClass` and fail, then it will try to load `com.foo.MyClass` and succeed. At that point it will look for MyInnerClass within MyClass.

Now, what happens if a class cannot be solved and the package is very deep? A lot of calls to `ClassLoader.loadClass`. Note that this should probably be an issue only if we configure it to use reflection also for stuff outside java or javax. At least, this is what I would expect.

**Comment by daanschipper** [comment]
Fortunately the cache only take up memory. As you say these caches are needed to solve lambdas, but I have the idea many entries are not needed. I think it would be great to somehow control this more, instead of saving **all** the parsed nodes. 

Do you see any way the `ReflectionTypeSolver` can be sped up? For me it simply takes too long to process my project. Or do you have tips on how I could speed up the execution (split the project into smaller pieces, create new JavaParserFacade instances for each sourceroot/package/java file)?

**Comment by daanschipper** [comment]
Another question, `SourceRoot` provides a way to parallel parse the individual `CompilationUnit`s, but I'm constantly asking `expression.calculateResolvedType`. To my knowledge there only exist one `TypeSolver` and `JavaParserFacade` instance, does this parallelisation affect this is any way? Are the threads waiting for one another?

**Comment by matozoid** [comment]
Notes about `SourceRoot`s threading are in its Javadoc. I'd say be very, very careful with the callback version - it's your responsibility to avoid concurrency issues there.

A `provider` is an abstraction for the data that is being streamed into the parser. I guess you're seeing disk access time there.

edit: I'm not sure having memory full is a problem (could be) because the caches should remove items when memory is getting full. I'm curious if it makes a difference when you reconfigure them to accept a maximum of 1000 items or so.

**Comment by daanschipper** [comment]
Regarding the threading, I'm only visiting the individual nodes and for certain conditions I'm calling `expression.resolve` or `expression.calculateResolvedType` and saving them in a db. I know for certain that the saving to the db is safe, but are the other functions considered thread safe? Otherwise I'll have to implement something to circumvent multiple simultaneous calls to JavaParserFacade.

**Comment by matozoid** [comment]
Well, if @ftomassetti says that resolution depends on the content of the cache, and the cache is a single instance, then threads could influence the resolution result of another thread. Most straightforward solution: don't use parallel parsing, just use the sequential one.

**Comment by daanschipper** [comment]
I'm now trying to profile the sequential one. If I really want to use the parallel parsing I'll have to implement some queue of nodes that JavaParserFacade can resolve.

**Comment by matozoid** [comment]
From my own experience I know that it is noticably slower - tens of percents.

**Comment by daanschipper** [comment]
@ftomassetti On your question, VisualVM did not list the method parameters in the sampling mode. I'm now running it with 'Profiler' and that does show the method parameters

**Comment by daanschipper** [comment]
Apparently you can't invoke JavaParserFacade in parallel, so I'm now running everything in serial, which seems to perform a lot better. However, it's still not enough.

I've tried to optimise the visitor I'm using, ignoring nodes that are useless for my analysis (`node.getComments()` is quite costly since it's invoke for every node by `VoidVisitorAdapter`).

The project I'm analysing has one gigantic SourceRoot which consists of ~10.000 .java files (this is not my code to be clear), and it's still struggling to completely analyse it. The time to analyse files just keeps on increasing. After 8000 files the program just becomes too slow and I have to abort parsing.

```
10:31:12.595 [main] INFO  generate.Generator - Parsing file 4000 of 10029
10:32:49.172 [main] INFO  generate.Generator - Parsing file 5000 of 10029
10:34:27.990 [main] INFO  generate.Generator - Parsing file 6000 of 10029
10:36:30.895 [main] INFO  generate.Generator - Parsing file 7000 of 10029
10:49:02.943 [main] INFO  generate.Generator - Parsing file 8000 of 10029
```

I'm now trying to profile what happens after 7000 files, but that takes some time to get there. After that I'll play around with different cache types.

**Comment by ftomassetti** [comment]
I am not sure about what kind of analysis you are doing, but would it make sense to run it for subset of the code and store the partial results somewhere. Finally you would merge the partial results

**Comment by daanschipper** [comment]
I'm extracting log statements (log.info("some log message")), type hierarchies (A extends B) and the output of toString methods. I'm just extracting this information with a visitor and storing it in a database.

```
sourceRoot.parse(startPackage, sourceRoot.getParserConfiguration(), (localPath, absolutePath, result) -> {
    result.ifSuccessful(compilationUnit -> {
        compilationUnit.accept(new ExtractInformationVisitor(), null);
    });
    return SourceRoot.Callback.Result.DONT_SAVE;
});
```

That is all I'm doing, which is why I'm wondering why it is so slow after a while.

To give some more insight on how I'm extract for instance the type hierarchy, I'm resolving the current class I'm in, getting the extendedTypes, resolving that, and storing it in the database (`hierarchies.create(superType, subType`). 

```
@Override
public void visit(ClassOrInterfaceDeclaration n, String qualifiedName) {
    Type subType = types.createIfAbsent(n.resolve().getQualifiedName());
    NodeList<ClassOrInterfaceType> extendedTypes = n.getExtendedTypes();
    if (!extendedTypes.isEmpty()) {
        for (ClassOrInterfaceType superClass : extendedTypes) {
            try {
                Type superType = types.createIfAbsent(superClass.resolve().getQualifiedName());
                hierarchies.create(superType, subType);
            } catch (UnsolvedSymbolException e) {
                logger.warn("Unable to resolve extended type " + superClass.getNameAsString() +
                        " of " + subType.getQualifiedName());
            }
        }
    }
    for (BodyDeclaration<?> bodyDeclaration : n.getMembers()) {
        bodyDeclaration.accept(this, subType.getQualifiedName());
    }
}
```

**Comment by matozoid** [comment]
I'm not sure it was said explicitly, but if you don't need tokens and/or comments, you can turn them off in the ParserConfiguration and use that on `JavaParser` *and* `JavaParserTypeSolver`.

Turning off comments ("do not attribute") will skip the algorithm for placing comments at the right nodes.
Turning off tokens prevents JP from creating a few objects for every token.

**Comment by daanschipper** [comment]
What does the `setStoreTokens()` exactly do? I was already using attribute comments.

**Comment by matozoid** [comment]
It creates/keeps the list of tokens and gives all nodes a TokenRange that points to it. If you don't access tokens or functionality based on it (lexical preserving printer) you can ignore them.

**Comment by daanschipper** [comment]
I found a culprit, the cache in `JavaParserFacade` of `IdentityHashMap<Node, ResolvedType>`! While parsing multiple files this cache just keeps growing and growing. In my case using 384/473 MB of the used memory by my application.

![screen shot 2018-06-22 at 13 53 48](https://user-images.githubusercontent.com/2778477/41775440-2da31fea-7624-11e8-9d3c-7d2ae9c191e1.png)


Clearing this cache with `JavaParserFacade.clearInstances()` seemed to have solved the issue.

I do have to note that I'm using my own implementation of a `TypeSolver` that is using an index, so some problems can still occur in `JavaParserTypeSolver` that I didn't encounter with this test.

**Comment by ftomassetti** [comment]
Interesting. If we were using guava we could use some map with a limited size, like a map that keep a list of the last X entries and delete the oldest one when growing too much. We could even build that ourselves and this would remove this issue.

**Comment by daanschipper** [comment]
The current implementation of the caches in `JavaParserFacade` allows them to keep growing without any limit. This should really be addressed, making users call `clearInstances` isn't fail proof

**Comment by daanschipper** [comment]
You could start indeed with a simple guava cache with a limited number of items. This could of course be improved by using weighted entries based on the number of times an entry is used.

**Comment by ftomassetti** [comment]
Right, that is in JSS which is allowed to have dependencies (unlike JP), so yes, why not using a guava map?

**Comment by daanschipper** [comment]
As for reference, these are the memory usages of my application while parsing 25k files, the first is without `JavaParserFacade.clearInstances()` and the latter is with. The enormous spikes is because I've let the program run with 12gb of heap space, so jvm utilises it all.

![screen shot 2018-06-22 at 10 53 42](https://user-images.githubusercontent.com/2778477/41775735-69657f5e-7625-11e8-98b4-b18b4feca8ad.png)
![screen shot 2018-06-22 at 14 04 14](https://user-images.githubusercontent.com/2778477/41775744-70c3df8e-7625-11e8-9f1b-fc1c8e39ff19.png)

**Comment by daanschipper** [comment]
I'll count how many objects are present in those caches during my run so we can set a meaningful limit

**Comment by matozoid** [comment]
@daanschipper any news?

**Comment by daanschipper** [comment]
I'll try to free up some time this week to finish up this issue

**Comment by matozoid** [comment]
Hey @daanschipper - it would be wonderful if you could find some time for this!

**Comment by matozoid** [comment]
Well, I guess someone else will have to have a go at this.

**Comment by liiri** [comment]
In the meantime it would be great to add some piece of documentation about the `JavaParserFacade` cache. I've gone through the same process as @daanschipper 
![mat](https://i.imgur.com/zXu2LB7.png)

**Comment by matozoid** [comment]
@liiri - that's a great idea, but what documentation and where?

**Comment by jiaxian-lin** [comment]
I also encountered this problem when parsing multiple projects (I needed to setting up a new symbolSolver for StaticJavaParser repeatedly and then reset it), and it was taking up more and more memory
```
public static void setTypeSolver(ArrayList<Path> paths, ArrayList<Library> additionalLibrary) throws IOException {
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
        for(Path path: paths){
            ProjectRoot projectRoot = new ParserCollectionStrategy().collect(path);

            for (SourceRoot root : projectRoot.getSourceRoots()) {
                JavaParserTypeSolver javaParserTypeSolver = new JavaParserTypeSolver(root.getRoot());
                combinedTypeSolver.add(javaParserTypeSolver);
                javaParserTypeSolver = null;
            }
        }

        combinedTypeSolver.add(new ReflectionTypeSolver());

        for(Library library: additionalLibrary){
            Path jar = Paths.get(library.getWorkPath());
            try {
                JarTypeSolver jarTypeSolver = new JarTypeSolver(jar);
                combinedTypeSolver.add(jarTypeSolver);
                jarTypeSolver = null;
            }catch (Exception e){
                logger.error("Can't parse jar: " + jar);
                try {
                    if(new File(jar.toUri()).delete()){
                        logger.info("Jar has been deleted "+jar);
                        PackageDownloader.download(library, "./data/library");
                    }
                }catch (Exception e2){
                    logger.error("Can't delete the file "+jar.toString());
                }
            }

        }
        JavaSymbolSolver javaSymbolSolver = new JavaSymbolSolver(combinedTypeSolver);
        StaticJavaParser.getConfiguration().setSymbolResolver(javaSymbolSolver);
    }


public void build(Commit commit, Collection<RepoClass> repoClasses) throws IOException {
        for(RepoClass repoClass: repoClasses){
            CompilationUnit cu = repoClass.getAST();
            VoidVisitor<RepoClass> methodCallVisitor = new MethodCallVisitor();
            methodCallVisitor.visit(cu, repoClass);
            cu.remove();
        }
}

public void main(){
    ......
    for (Project project: projects){
            ASTBuild.setTyeSolver(projectArrayList, libraryArrayList);
            ASTBuild.parseClasses(project.getRepoClassHashMap().values());
            methodCallBuilder.build(project.getRepoClassHashMap().values());
            JavaParserFacade.clearInstances();
    }
......
```

**Comment by jiaxian-lin** [comment]
> I also encountered this problem when parsing multiple projects (I needed to setting up a new symbolSolver for StaticJavaParser repeatedly and then reset it), and it was taking up more and more memory
> 
> ```
> public static void setTypeSolver(ArrayList<Path> paths, ArrayList<Library> additionalLibrary) throws IOException {
>         CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
>         for(Path path: paths){
>             ProjectRoot projectRoot = new ParserCollectionStrategy().collect(path);
> 
>             for (SourceRoot root : projectRoot.getSourceRoots()) {
>                 JavaParserTypeSolver javaParserTypeSolver = new JavaParserTypeSolver(root.getRoot());
>                 combinedTypeSolver.add(javaParserTypeSolver);
>                 javaParserTypeSolver = null;
>             }
>         }
> 
>         combinedTypeSolver.add(new ReflectionTypeSolver());
> 
>         for(Library library: additionalLibrary){
>             Path jar = Paths.get(library.getWorkPath());
>             try {
>                 JarTypeSolver jarTypeSolver = new JarTypeSolver(jar);
>                 combinedTypeSolver.add(jarTypeSolver);
>                 jarTypeSolver = null;
>             }catch (Exception e){
>                 logger.error("Can't parse jar: " + jar);
>                 try {
>                     if(new File(jar.toUri()).delete()){
>                         logger.info("Jar has been deleted "+jar);
>                         PackageDownloader.download(library, "./data/library");
>                     }
>                 }catch (Exception e2){
>                     logger.error("Can't delete the file "+jar.toString());
>                 }
>             }
> 
>         }
>         JavaSymbolSolver javaSymbolSolver = new JavaSymbolSolver(combinedTypeSolver);
>         StaticJavaParser.getConfiguration().setSymbolResolver(javaSymbolSolver);
>     }
> 
> 
> public void build(Commit commit, Collection<RepoClass> repoClasses) throws IOException {
>         for(RepoClass repoClass: repoClasses){
>             CompilationUnit cu = repoClass.getAST();
>             VoidVisitor<RepoClass> methodCallVisitor = new MethodCallVisitor();
>             methodCallVisitor.visit(cu, repoClass);
>             cu.remove();
>         }
> }
> 
> public void main(){
>     ......
>     for (Project project: projects){
>             ASTBuild.setTyeSolver(projectArrayList, libraryArrayList);
>             ASTBuild.parseClasses(project.getRepoClassHashMap().values());
>             methodCallBuilder.build(project.getRepoClassHashMap().values());
>             JavaParserFacade.clearInstances();
>     }
> ......
> ```

I found a simple solution: manual garbage collection
```
for (Project project: projects){
        ASTBuild.setTyeSolver(projectArrayList, libraryArrayList);
        ASTBuild.parseClasses(project.getRepoClassHashMap().values());
        methodCallBuilder.build(project.getRepoClassHashMap().values());
        JavaParserFacade.clearInstances();
        System.gc();
    }
```

**Comment by jlerbsc** [comment]
The StaticJavaParser class is a utility that should only be used for testing. You can use JavaParserAdapter and instantiate the parser for each project. That should definitely improve the operation.

**Comment by jiaxian-lin** [comment]
> The StaticJavaParser class is a utility that should only be used for testing. You can use JavaParserAdapter and instantiate the parser for each project. That should definitely improve the operation.

Thanks for your reply! btw, is there a JavaParserAdapter usage example?

**Comment by jlerbsc** [comment]
It's just a wrapped arround a JavaParser so you can find example in unit tests.

**Comment by jiaxian-lin** [comment]
Thank you!

However, after I changed the parser, the problem persisted
![image](https://user-images.githubusercontent.com/71680354/223077331-d4cc2e2e-bb61-49fd-9844-785983f718e1.png)

**Comment by jlerbsc** [comment]
Can you adapt your code snippet?
How many source files are you analyzing?

**Comment by jiaxian-lin** [comment]
Sorry, the problem is with me, I did not completely delete the parsed AST. Thank you for getting back to me, there maybe about several thousand files

**Comment by jlerbsc** [comment]
> manual garbage collection

It's useless since it's the JVM that does this when necessary.
