### ISSUE TITLE
Complete NodeWithMembers

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1441]
As noted in #1440, the methods in `NodeWithMembers` are not completely consistent.

We could use...
```java
addFieldWithInitializer(Class<?> type, String name, Expression initializer, Modifier... modifiers)
addFieldWithInitializer(String type, String name, Expression initializer, Modifier... modifiers)
addPrivateField(Type type, String name)
addPublicField(Type type, String name)
addProtectedField(Type type, String name)
```

**Comment by kotari4u** [comment]
Would like to work on this. Will fork the project and keep posting updates

**Comment by matozoid** [comment]
Cool, consider yourself assigned.

Don't forget to judge for yourself if the API is complete, the above is just a quick note.

**Comment by kotari4u** [comment]
Made changes and created [PR](https://github.com/javaparser/javaparser/pull/1656)

Also I see that NodeWithMembers.getMethodsByParameterTypes(Class<?>); does not with classes with same simple name but are in different packages. Ex: java.util.List and java.awt.List. This is because NodeWithParameters.hasParameterTypes works on simple name. Is this something you would prefer to overload to check for names. By that we can provide overloaded method in NodeWithMembers

_default List<MethodDeclaration> getMethodsBySignature(String name, Class<?> paramTypes) {_
along with
_default List<MethodDeclaration> getMethodsBySignature(String name, String... paramTypes) {_

**Comment by matozoid** [comment]
@kotari4u ah, it is difficult to estimate if these methods are useful or confusing for people. To be correct, these methods would need to call the symbol solver. But we don't do that now.

So... what do you think, should they be there?

**Comment by kotari4u** [comment]
Agreed. Also adding more methods might confuse people. We can add if there is any demand. We can close this issue if we are good with the PR

**Comment by matozoid** [comment]
Good, I'll go merge it.
