### ISSUE TITLE
JavaParser does not correctly parse annotations on method return type

### ISSUE THREAD

**Issue by CharlesZ-Chen** [javaparser/javaparser#1446]
~~I think this issue might related to https://github.com/javaparser/javaparser/issues/912~~

Given below code:

```java
public @A Object m() {
   //...
}
```

The JavaParser would parsed above code into below `MethodDeclaration`:

```bash
@A
public Object m() {
//...
}
```

And always parsed `@A` as a declared annotation on the whole method.

This somehow modifies the meaning of the annotation, if `@A` is defined as a annotation designated applied to type also (e.g. `@Target.TYPE_USE` and `Target.TYPE_PARAMETER` is valid target for `@A`).

javaParser may need to look at the annotation definition to determine what should be the correct position of this annotation, according to the [java 8 JSL 9.7.4 Where Annotations May Appear](https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.7.4).

Therefore, whether parser `@A` as a declared annotation on the whole method or a type annotation on the return type, is determined by what `@Target` in `@A`'s definition that `@A` is allowed to be used.

Specifically, given above code example,

- If `@A` is only allowed as declared annotation, then `@A` should be parsed as an annotation on the method declaration.

- If `@A` is only allowed as type annotation, then `@A` should be parsed as an annotation on the method return type

- If `@A` is allowed as both declared annotations and type annotations, then `@A` should be parsed as both an annotation on the method declaration, and an annotation on the method return type.

Currently, however, JavaParser will always parse `@A` as a declared annotation for above code examples.

**Comment by matozoid** [comment]
Hi!

This is known, it is documented in the Javadoc: http://www.javadoc.io/doc/com.github.javaparser/javaparser-core/3.5.15
, so the decision was made to put all annotations on `MethodDeclaration`, not on the type. This is because the parser itself has no way to look for other classes, to solve symbols, or anything, all it can do is construct the tree. Therefore deciding what the annotation belongs to (which means looking for that annotation somewhere) is way beyond parsing. It could be part of a tool which uses the symbol solver though, so I suggest to keep this issue for building that tool (a kind of annotation-associator.)

**Comment by CharlesZ-Chen** [comment]
@matozoid  Ok, good to know this. Thanks for the quick reply!

**Comment by matozoid** [comment]
No problem! Let us know if you have more issues :-)
