### ISSUE TITLE
Add binary name support as described in JLS 8

### ISSUE THREAD

**Issue by lamvak** [javaparser/javaparser#145]
Add method getBinaryName returning a binary name of node to NamedNode interface.
Binary names are described in language specification: https://docs.oracle.com/javase/specs/jls/se8/html/jls-13.html#jls-13.1

**Comment by ftomassetti** [comment]
We could not generate the same binary name the compiler generates for anonymous classes because that is arbitrary:
`The binary name of an anonymous class (§15.9.5) consists of the binary name of its immediately enclosing type, followed by $, followed by a non-empty sequence of digits.`

However it would make sense to generate it for the other cases

**Comment by lamvak** [comment]
It's rather an important part of the language.
The binary name for anonymous class - of course you can (and should) generate it. What Java specification gives you is flexibility, not constraint. So it should be easier, not harder. The only constraint is that within one parsing activity you should return the same name for the same anonymous class - as the definition is anonymous it matters_only_inside of a compilation unit.

**Comment by ftomassetti** [comment]
yes, you know that, but my concern is that many users could be surprised that the name we generate is not necessarily the same name generated by the Java compiler. Of course we could document that but... not many users read the documentation :)

**Comment by matozoid** [comment]
I wouldn't say that surprise is enough to stop this request :-)

I'm curious if this is in scope because it concerns naming _inside_ a class file. JavaParser parses source code, gives you a tree, and stops. Nowhere do we talk about class files. If we add getBinaryName, should we also make a way to create a class? Should we generate byte code? Should we build a compiler?

**Comment by matozoid** [comment]
I guess this issue is outdated. Please open a follow up issue if necessary.
