### ISSUE TITLE
Incorrect behaviour with dirs with dots in names

### ISSUE THREAD

**Issue by AwesomeLemon** [javaparser/javaparser#1450]
In some projects there're subfolders with dots in names. (example: https://github.com/eclipse/eclipse.platform.team).

Compiling such projects using SourceRoot leads to NoSuchFileException. I've tracked the code and found out the culprit: it turns out that in method ``CodeGenerationUtils.packageToPath`` the dots in the path are replaced with slashes. Obviously, if there were indeed dots in the folder name, this leads to the wrong output path which of course is not found.

In my opinion, this could be simply fixed by checking whether the path with dots exist before trying to replace them with slashes.
So, replace this:
```
    public static Path packageAbsolutePath(String root, String pkg) {
        pkg = packageToPath(pkg);
        return Paths.get(root, pkg).normalize();
    }
```
With this:
```
    public static Path packageAbsolutePath(String root, String pkg) {
        Path path = Paths.get(root, pkg);
        if (Files.exists(path)) {
            return path.normalize();
        }
        pkg = packageToPath(pkg);
        return Paths.get(root, pkg).normalize();
    }
```

If you would like it, I could create a pull request with this.

**Comment by matozoid** [comment]
Hi! Is this on the very latest version? We just had a change near this functionality.

**Comment by SjurWarEagle** [comment]
Hi matozoid,
it's still in 3.5.15 latest version on maven from Feb28 and in the version from git, at least in the CodeGenerationUtils.
I was about to file the same problem.

Another idea to fix this would be to add a new parameter to ParserConfiguration.

**Comment by matozoid** [comment]
Okay, after looking over this for a bit, I think it is a misconception about what a source root is.

SourceRoot's root directory should correspond to the location of the default package of a set of source files. It isn't a simple directory walker. If "eclipse.platform.team" is inside your source root, it is not a valid source directory, because it cannot correspond to a part of a package. So, `/blah/eclipse/eclipse.platform.team/` should be the root directory of the source root, not `/blah/eclipse/`.

Let's get to #1445 and give you a way to get the functionality you want.

**Comment by matozoid** [comment]
I see it's not well documented in `SourceRoot` too, let me fix that. (Pretty odd, seeing that this is the most well documented class in the whole project ;-) )

**Comment by AwesomeLemon** [comment]
Ok, I understand the problem; let's move to that another issue.
