### ISSUE TITLE
Which method parameters are declared final in JavaParser?

### ISSUE THREAD

**Issue by malteskoruppa** [javaparser/javaparser#1475]
I have a question that doesn't directly have anything to do with _using_ JavaParser, but more about the _code style_ used in JavaParser's own  source code. I hope it is not out of place. Otherwise, please feel free to remove it.

I noticed that, throughout the JavaParser source code, many method parameters are declared as `final`. Not all of them, but certainly a noticeable amount.

This led me to wonder when I should declare method parameters as `final` in my own source code (I never used to do it before, except where necessary, e.g., because of anonymous classes declared within a method that use one the method's parameters). On the one hand, I almost never reassign method parameters in any of my methods (except for extremely rare exceptions), so in principle I could declare _all_ parameters in _all_ my methods throughout _all_ my source code as `final` to provide more semantic information. On the other hand, I feel like this only adds a lot of code clutter and makes the code less readable. So I have mixed feelings about whether this is a good idea.

I consider you guys very competent programmers, so I'd been interested in hearing your opinion, as you appear to use the `final` keyword often for method parameters. What is your approach here? When are method parameters declared as `final` in the JavaParser source code, and when aren't they?

Knowing how you handle this will also help me and others writing code that is consistent with JavaParser's coding style when submitting PRs. :wink:

**Comment by matozoid** [comment]
Ow, thanks for the compliment :-) In my opinion making method parameters final adds really little. I don't even think it's a sin to change a parameter in the method itself. When I add final to a parameter I'm probably in an "everything should be pretty" mood. On the other hand I do add final to local variables a lot - they reduce the amount of state you have to deal with in a method, and after a while `final` will start to look like `var` or `def` in other languages: a point where a new variable is defined.

In the end the code base has been built by many different people so style differs a lot. That's partly because I, as the maintainer, prefer that committers feel welcome, so I won't bury them in a mountain of style complaints for every PR. "Working code over style guides" should have been in the agile manifesto :-D

I'm curious what @ftomassetti thinks about this, as the other big committer.

**Comment by ftomassetti** [comment]
I agree with @matozoid . I can only add that in many modern languages (like Kotlin) parameters are immutable. Less state, less headache.

If you use `final` consistently when you do not use it you are communicating to the reader that the particular parameter is going to be changed. If you use it only sometimes you just confuse the reader.

**Comment by malteskoruppa** [comment]
Thanks guys, I agree with you too. :smiley: So I'm going to stay with not adding the `final` keyword to parameters, except where needed (anonymous classes) or where I feel that for some reason I want to communicate to other developers that a given parameter should really really not be reassigned.

I think that making method parameters immutable by default as in Kotlin is a great idea -- that's the behavior you want in 99.99% of cases anyway. I wish it were like that in Java too. At least, the semantics should be the other way around -- have method parameters be `final` by default, and if you really want to reassign a parameter in a method, mark it as `mutable` or something like that.
