### ISSUE TITLE
JavaParserFacade.solve(FieldAccessExpr fieldAccessExpr) doesn't return SymbolReference<ResolvedFieldDeclaration>

### ISSUE THREAD

**Issue by ErtelJessica** [javaparser/javaparser#1479]
The used Method of JavaParserFacade is
public SymbolReference\<ResolvedFieldDeclaration> solve(FieldAccessExpr fieldAccessExpr) which should return SymbolReference\<ResolvedFieldDeclaration>.

What I'm looking for is the JavaParserFieldDeclaration to get the initializer value for my fieldAccessExpr. My code is

```
FieldAccessExpr fieldexpr = argument.asFieldAccessExpr();
SymbolReference<ResolvedFieldDeclaration> fieldDeclaration = JavaParserFacade.get(combinedTs).solve(fieldexpr);
JavaParserFieldDeclaration decl = (JavaParserFieldDeclaration) fieldDeclaration.getCorrespondingDeclaration();
```
But I get the following Error:
Exception in thread "main" java.lang.ClassCastException: com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration$1 cannot be cast to com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserFieldDeclaration

I tried to use ResolvedClassDeclaration/JavaParserClassDeclaration as well, but this leads to an compile Error because SymbolReference\<ResolvedFieldDeclaration> could not be cast to SymbolReference\<ResolvedClassDeclaration>.

**Update:** 
I think this problem occures when the fieldexpr is not directly defined in the class but in a parent class. Expample:

```
public class A {
  public static final String AFIELD = "a";
}

public class B extends A {
  public static final String BFIELD = "b";
}

```
The Error occures when resolving the FieldAccessExpr in:

```
doSomething(B.AFIELD);
```

**Comment by ErtelJessica** [comment]
I have an additional question to this issue:
Sometimes I also get an ReflectionFieldDeclaration instead of a JavaParserFieldDeclaration  - which is okay since they both implement ResolvedFieldDeclaration.
But why am I getting two different types? I don't unterstand the difference.
In all cases the fields are definied and used as follows:
```
public class B extends A {
      public static final String FIELD1 = "field1";
}

...

String s = ((B) object).get(B.FIELD1);
```

And second: How do I get the initializer of a ReflectionFieldDeclaration?

**Comment by ErtelJessica** [comment]
@matozoid Could you estimate how much time it will take to fix this bug?

**Comment by matozoid** [comment]
@ErtelJessica - I'm sorry, I don't work on this part. @ftomassetti is setting up his own business and has currently no time to work on this, so we're dependent on outside contributions for a while (so creating a PR is the fastest way to get this fixed.)

**Comment by ftomassetti** [comment]
@ErtelJessica it is difficult to estimate it because our energies are limited and we havecurrently 183 issues open to look into. At the moment this is not considered to have a significanly higher priorities than other bugs so we cannot give you a reliable estimate. However we can help people contribute to it.

**Comment by ftomassetti** [comment]
One thing that could help us a lot is one simple failing test

**Comment by jlerbsc** [comment]
Hi @ErtelJessica You are right, you cannot cast the corresponding declaration with JavaParserFieldDeclaration class because in the case of inherited field the corresponding declaration is an inner anonymous class which implements ResolvedFieldDeclaration interface (see JavaParserClassDeclaration.getAllFields()).

     JavaParserFieldDeclaration decl = (JavaParserFieldDeclaration) fieldDeclaration.getCorrespondingDeclaration();

One solution would be to create a static inner class which would give access to the declaration of fields. I will create a PR to make a change proposal. @maartenc could you take a look at this please?
