### ISSUE TITLE
primary class

### ISSUE THREAD

**Issue by wangkang5** [javaparser/javaparser#1509]
When I use `CompilationUnit compilationUnit = JavaParser.parse(inputStream,charset);`
I can't get primary class by `compilationUnit.getPrimaryTypeName()`.
Also,I don't know what fileName or primary className it is

**Comment by matozoid** [comment]
Hi! The problem is that an inputstream doesn't have a filename, and we can only find the primary class when we know the filename, since it is defined as "the class that has the same name as the file."

[Here ](https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/JavaParser.java#L213) you can see the code used to set the filename when parsing from a file.

I guess you could try an alternative approach, like find the only public class in the compilation unit.

**Comment by matozoid** [comment]
Is it working for you?

**Comment by matozoid** [comment]
Assuming answered.
