### ISSUE TITLE
Remove unused imports

### ISSUE THREAD

**Issue by ivanjunckes** [javaparser/javaparser#1590]
How can I remove unused imports programmatically? Can anyone help me on this?

**Comment by matozoid** [comment]
I'm guessing: resolve all variables and fields in a compilation unit, then match all imports to all these names, then remove all imports that haven't matched any variable or field.

**Comment by ftomassetti** [comment]
That would be a nice example to write. One could also try removing an import and see if any resolution changes.

**Comment by ivanjunckes** [comment]
@ftomassetti what you mean by see if any "resolution" changes?

Calling resolve in the class I get: "Symbol resolution not configured: to configure consider setting a SymbolResolver in the ParserConfiguration"

**Comment by ivanjunckes** [comment]
@matozoid tried this one, but is very hard to get all the types. Because it can go to annotations recursively etc..

**Comment by matozoid** [comment]
@ftomassetti is the expert on symbol solving here - isn't it possible to simply "find all `Type` -> resolve" ?

**Comment by ftomassetti** [comment]
@ivanjunckes by resolution change I mean taking any symbol in the code and try to resolve it. For example find out that "Foo" is resolved in a certain point as "my.packagez.Foo". Then remove the import and try again. It could happen that Foo is then resolved to another class, maybe in the same package or maybe it is still resolved to the same class because Foo was in the same package or because an import with the asterisk introduce it anyway.

**Comment by ftomassetti** [comment]
To find all types I would think that there are utilities to traverse the tree and get all nodes of a certain type. We mainly want SimpleName nodes I think.

**Comment by matozoid** [comment]
`SimpleName` is always unqualified. Don't you mean `Name` which can be qualified?

**Comment by ivanjunckes** [comment]
@ftomassetti do you know which utility class is that?

**Comment by matozoid** [comment]
@ivanjunckes `Node.find...`

**Comment by matozoid** [comment]
I assume this is answered.
