### ISSUE TITLE
java.lang.UnsupportedOperationException when calling accessspecifier method

### ISSUE THREAD

**Issue by parvez2014** [javaparser/javaparser#1597]
I am using both parser and JSS. For each ResolvedMethodDeclaration instance, I am collecting name, return type and access specifier. The program is working for many of the cases but in some cases, I also receive exceptions when calling the following method on a ResolvedMethodDeclaration instance:

`resolvedMethodDeclaration.accessSpecifier() `
I have received the following exception:

> Exception in thread "main" java.lang.UnsupportedOperationException
> 	at com.github.javaparser.symbolsolver.javassistmodel.JavassistMethodDeclaration.accessSpecifier(JavassistMethodDeclaration.java:174)

I checked the code in the repository. I could not find the class that implement ResolvedMethodDeclaration interface and I don't know what can throw this exception. The documentation does not say anything on this. Any idea what can cause this exception?
Other methods, like getName(), getQalifiedName, getClassName() of ResolvedMethodDeclaration are working without any problem

**Comment by ftomassetti** [comment]
It is actually very easy to find the source code of that Method. It is exactly at [line 174 of the class JavassistMethodDeclaration](https://github.com/javaparser/javaparser/blob/b64b7a425769228e24ee8784c7f535fc7b49d32e/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistMethodDeclaration.java#L174).

The issue is that the method has not been implemented: it should be relatively easy to do so and we are willing to help to prepare a Pull Request if you want to help us with this issue. Otherwise we will do so as soon as we can (consider we have 206 issues open at the time of this writing)

**Comment by parvez2014** [comment]
Thanks for quick reply. This is a great project and I would like to contribute. Can you give me some additional pointers to help with the issue and how to contribute. Thanks.

**Comment by matozoid** [comment]
@parvez2014 here you go: https://github.com/javaparser/javaparser/blob/master/CONTRIBUTING.md

**Comment by jlerbsc** [comment]
Now JavassistMethodDeclaration.accessSpecifier() method is implemented but without minimal test case we can't verify anything. You are free to create a new issue if the problem persists.
