### ISSUE TITLE
Further improve correction of whitespace during difference application

### ISSUE THREAD

**Issue by ThLeu** [javaparser/javaparser#1638]
Example that does not work yet, probably because of the extra space after the annotation `@Override`

```java
    @Test
    public void removingAnnotationsWithSpaces() {
        considerCode(
                "class X {" + EOL +
                        "  @Override " + EOL +
                        "  public void testCase() {" + EOL +
                        "  }" + EOL +
                        "}" + EOL
        );

        cu.getType(0).getMethods().get(0).getAnnotationByName("Override").get().remove();

        String result = LexicalPreservingPrinter.print(cu.findCompilationUnit().get());
        assertEqualsNoEol(
                "class X {\n" +
                        "  public void testCase() {\n" +
                        "  }\n" +
                        "}\n", result);
    }
```

**Comment by matozoid** [comment]
Hi @ThLeu! Are you still around?

**Comment by ThLeu** [comment]
Hi @matozoid! Yeah, I am still around, I was on vacation for some time but I definitely plan to contribute again, I'll just have to take it a bit slow.

**Comment by matozoid** [comment]
Cool! Take it easy :-)

**Comment by jlerbsc** [comment]
It's right the issue is caused by the extra space after the annotation @Override. If we remove this space from the test case, the following character is a line separator character is not treated in the same way.

**Comment by jlerbsc** [comment]
I'm going to try and explain the problem you encountered in detail to keep a trace of the analysis of this bug and the solution provided.

Lexical preservation is based on decomposing AST nodes into tokens. Spaces, tabs and end-of-line characters are also represented in the form of tokens. When lexical preservation is enabled, each operation on the AST updates this list of tokens, which are then printed to restore the lines of code.

The list of tokens analysed is defined from the parent node of the node on which the operation is performed. In the example provided, this is the list of tokens representing the declaration of the method on which the annotation is removed.

The problem you describe arises when you try to delete the first element in the list, as the prior indentation is generally carried by the parent node of the element in consideration (in this case, the annotation). Here, the tokens representing the method declaration are not sufficient as they do not contain the indentation information because they start with the element representing the annotation. We therefore need to analyse the parent node of the method declaration, then search the list of tokens for the element corresponding to the method declaration and finally determine whether an indentation is present and delete it if necessary.
