### ISSUE TITLE
Qualified class name parsed as nested FieldAccessExpr

### ISSUE THREAD

**Issue by Shoreray** [javaparser/javaparser#1639]
Hi there.
I have a question about parser behavior (or a bug report, depending what the expected behavior is).

Qualified class name that appear as a scope of a FieldAccessExpr or MethodCallExpr would be parsed incorrectly as nested FieldAccessExpr expressions.

For example, the code `java.lang.System.out` is parsed as nested FieldAccessExpr expressions with 3 layers:
Inner most layer: **{scope:** "java.lang.System"; **name:** "out"**}**
Second layer: **{scope:** "java.lang"; **name:** "System"**}**
Third layer: **{scope**: "java"; **name:** "lang"**}**

It seems like with some information from the symbol resolver, the parser can tell which part is the type name and which are the actual field names? 
I'm hoping that the parser have already been able to do this and it's just me that is not configuring the parser correctly...
Please let me know. Thanks a lot!

**Comment by ftomassetti** [comment]
The parser could not possibly be able to do that without the symbol solver because it has no idea that java.lang.System is a class and java.lang or java.lang.System.out are not. This thing looks as a FieldAccessExpr to the parser because syntactically there is no way to differentiate a qualified class name from a field access.

However the symbol solver can tell you what the whole `java.lang.System.out` is a reference to a field

**Comment by Shoreray** [comment]
Thanks for the prompt response!

I'm wondering which API I should use to resolve the names in the FieldAccessExpr in this case, as FieldAccessExpr is not a Resolvable.
It might have been discussed in the documentation but I thought it might be easier to just ask.
Could you point me in the right direction if the answer is not too complex?

**Comment by Shoreray** [comment]
I found it. 
Thank you very much.
