### ISSUE TITLE
Does JavaParser work with Kotlin?

### ISSUE THREAD

**Issue by jorgecoca** [javaparser/javaparser#1640]
Quick question, is this tool also suitable for inspecting Kotlin code? If not, do you know of any tool that might help on the Kotlin side?

I run this code for a Kotlin file (rootRibBuilder is a Kotlin (*kt) file
```
val compilationUnit = JavaParser.parse(rootRibBuilder)
        val yamlPrinter = YamlPrinter(true)
        println("Printing compilation unit")
        println(yamlPrinter.output(compilationUnit))
```
and I got this stacktrace:

```
> Parse error. Found "package", expected one of  ";" "@" "\u001a" "abstract" "class" "default" "enum" "final" "import" "interface" "module" "native" "open" "private" "protected" "public" "static" "strictfp" "synchronized" "transient" "transitive" "volatile" <EOF>
  Problem stacktrace :
    com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:10311)
    com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:10170)
    com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:201)
    com.github.javaparser.JavaParser.parse(JavaParser.java:129)
    com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:328)
    com.github.javaparser.JavaParser.parse(JavaParser.java:203)
    com.connected.brisk.rib_state_tree_generator.StateTreeGenerator.generateStateTreeGraph(StateTreeGenerator.kt:21)
    com.connected.brisk.rib_state_tree_generator.RibStateTreeGeneratorTask.run(RibStateTreeGeneratorTask.kt:20)
```

Thanks!

**Comment by ftomassetti** [comment]
Hi @jorgecoca , no, JavaParser does not support Kotlin. We do not have a Kotlin parser. The JavaSymbolSolver would be able to handle referenced to compiled Kotlin code because it can handle bytecode but we miss a Kotlin parser. Would you like to help integrating an existing one?

**Comment by jorgecoca** [comment]
Souds good! I need to find some time and get familiar with the project, but I can do it! Thanks! ;)

**Comment by Octogonapus** [comment]
@ftomassetti What would need to be done? Presumably, make versions of `JavaParser` and `JavaToken` for Kotlin. Anything else you can think of? I am unfamiliar with the existing internal architecture, so I don't know how difficult it might be to put in new lexer/parser implementations.

**Comment by ftomassetti** [comment]
Well, first of all I would suggest to find an existing Kotlin grammar, not writing one from scratch. When you have that it would be nice to give it a similar API to what we have for JavaParser and we could reuse some of the symbol resolution logic probably but most of the code would be different and it should probably stay in a separate project.

**Comment by matozoid** [comment]
It should definitely be a separate project: our team is too small to support the features we currently have, so we can't have more features.

Is there no API to Kotlin's parser?

**Comment by miho** [comment]
Hi all,

I am working on a ANTLR4 based framework which generates a rich language model API from a labeled .g4 grammar spec. For many use cases it is is similar to javaparser. The framework is very young and not fully released yet (it still lives in a private repo). So far, we have working grammars for JSON, Java 8 and some DSLs that we use in our research group. While we developed it for synchronizing visual and textual representations of a program, the framework itself just focuses on processing, analyzing and transforming source code.

Just an example on how the generated API will look like (using the Java 8 grammar file):

```java
// parse the code
Java8ModelParser parser = new Java8ModelParser();
Java8Model model = parser.parse(code);

// find all method declarations which return void
// and add a parameter `int myP` to them
model.vmf().content().stream(MethodDeclaration.class).
    filter(MethodDeclaration::returnsVoid).
    forEach(m ->
        m.getParams().getParams().add(
            parser.parseFormalParameter("int myP")
        )
    );

// unparse the transformed model, i.e., serialize it to it's textual representation
Java8ModelUnparser unparser = new Java8ModelUnparser();
unparser.setFormatter(new MyFormatter());
String transformed = unparser.unparse(model);
```

This would certainly work for Kotlin, since there's already an ANTLR4 grammar for Kotlin.

Maybe there's a way we can collaborate between the projects.

**Anyone interested? Let me know.**

**Comment by matozoid** [comment]
@miho - that actually looks like what JavaParser would have been if we had had the time to convert everything to ANTLR. It looks pretty awesome - maybe we can remove the JavaCC part of JavaParser and depend on your project. On the other hand - that would make JavaParser pretty much redundant (which is a good thing.)

@ftomassetti - what do you think?

**Comment by matozoid** [comment]
@miho oh, to add one more thing: working on JavaParser has made it clear that there is quite a bit of demand for a parser for Java which is easy to use, is up to date and actively maintained, and has a friendly license.

**Comment by ftomassetti** [comment]
I think there are some similarities but I think that JP has a lot of little features we added to make the API usable for a larger audience.

Some not so small features (but admittedly problematic) are:
* lexical preservation: parse code, change it, reprint it keeping the original layout, with adaptations based on the changes
* symbol resolution: "this symbol A in this context is a reference to the field defined in the ancestor class Foo"
* support for comments: we do not ignore them but we track them and associate them to elements of the AST

We are definitely not trying to build a generic framework but instead focusing on the very specific needs of people who needs to work with Java code.

Probably the thing we support less well is transforming Java code, as it is quite complex to do this with JavaParser at the moment. Also, templates of Java code would be cool. Something like: `generateClass("class <<Name>> { int foo; }").usingData(listOfBeans)`

**Comment by ftomassetti** [comment]
A thing we do not support but would be cool to support is Java extensions: having the possibility of plugging in a new kind of statements or stuff like that.

**Comment by miho** [comment]
Hi @matozoid, hi @ftomassetti,

thanks for your replies!

@matozoid I actually wanted to do it years ago but didn't have the time. But last year I was in the lucky position that I could spend a couple of month on it. It's so cool to just specify a grammar file and yield a bidirectionally mapped API with traverse/iterator support, change notification, undo/redo etc.

@ftomassetti I'm very aware of the fact that you optimized javaparser for one language. And that's  fine. If javaparser had lexical preservation a couple of years ago, I'd probably never developed our ANTR4-based framework. I am still glad I did it though :)

Regarding the features you mentioned, symbol resolution is the only one that can't be fully automated. While lexical preservation isn't easy, it can be implemented in a fully generic way without loosing any functionality. Unfortunately, I didn't have enough time to include it right from the beginning. But it is definitely on the roadmap (*help wanted*). We currently have two approaches for comments: for special comment types, such as JavaDoc, they can be directly added to the grammar and the parse tree. For generic comments, i.e., comments that can appear everywhere, we merge them based on the code-ranges/intervals. This isn't ideal but worked well so far.

From a user's perspective, the APIs are surprisingly similar. And we do support a delegation mechanism which allows to introduce custom behavior to the generated API. So there's plenty of room for a custom/optimized API for a language like Java.

I like the template idea.

I have to discuss the details first, but we are going to release the code under either BSD (2-clause or new), Apache or LGPL/GPL+Classpath-Exception.

Anyway, I just wanted to let you know that we are working on this project and that I think it would be very cool and productive if we'd collaborate. Our framework is still in an early stage. There are tons of similar problems to solve...

**Comment by ftomassetti** [comment]
> While lexical preservation isn't easy, it can be implemented in a fully generic way without loosing any functionality.

I am not sure about that because there are expectation on the style and ways to do the harmonization of spaces, new lines, and indentation when modifying code that could be surprisingly complex

> for special comment types, such as JavaDoc, they can be directly added to the grammar and the parse tree

Well, technically nothing prevent me to add a JavaDoc anywhere I want. Also, If I insert a JavaDoc and then 10 empty lines, does the JavaDoc still refer to thing following it?

> For generic comments, i.e., comments that can appear everywhere, we merge them based on the code-ranges/intervals. This isn't ideal but worked well so far.

We do that and then use some heuristics to understand to what a comment refer to (and if it refers to something specifically)

> From a user's perspective, the APIs are surprisingly similar

Nice!

**Comment by miho** [comment]
> I am not sure about that because there are expectation on the style and ways to do the harmonization of spaces, new lines, and indentation when modifying code that could be surprisingly complex

So you are talking about behavior that can't be extracted from the raw grammar itself. I actually thought about annotating the grammar with style information and generating a formatter from that. It is certainly not easy and since I wasn't able to estimate the amount of work, I didn't pursue it from the beginning. I believe it is possible. But if you think that a manual formatter implementation makes more sense in this case this would still be an option.

> Well, technically nothing prevent me to add a JavaDoc anywhere I want.

Sure. In this case it is just treated as a regular comment.

> Also, If I insert a JavaDoc and then 10 empty lines, does the JavaDoc still refer to thing following it?

Yes, because there's nothing in between. 

So as long as the user is able to indicate what's a comment, the framework should be able to handle it. And again, if the raw grammar doesn't contain the information, one might annotate it. 

Coming back to the "does javaparser support language x" question. I think javaparser is perfect if you want to work with Java. And since you have done all the work already, it is certainly a downgrade from there to a generic framework.

But wouldn't it be cool to have a generic framework that can handle different grammars and uses compatible APIs for different languages? The language specific optimizations could be added to the generic API. The only existing framework I have seen that can do that (to some extend) is Xtext. But unfortunately they rely on a very old ANTLR version and writing grammars for it is far from intuitive. ANTLR4 is a huge improvement in that regard. I also tried to make our framework fully ANTLR compatible and not just rely on a subset.

**Comment by matozoid** [comment]
Sorry, was ill for a few days. @miho I'm curious what your project looks like - let us know when it's release please. At this moment I'm also not really sure how we can help each other, but the more help the better. (We have a chat channel, by the way - https://gitter.im/javaparser/javaparser )

**Comment by miho** [comment]
Sorry for my late response. Was busy with the initial preview release. Here it is:  https://github.com/miho/VMF-Text I'll explain more in the gitter chat you suggested.

**Comment by matozoid** [comment]
Hey @miho - the project is cool! Do you have any ideas about working together? I can't think of much right now.

**Comment by miho** [comment]
Hi @matozoid, here are some ideas :)

We could try to create/generate a Java(un)parser API with VMF-Text to see which features would be necessary to generate something like a full javaparser (minus symbol solver). Would be cool how far one can get with VMF-Text.

Another interesting area would be a multilingual API, e.g. for common combinations like Java and Groovy. This would be a huge additional benefit over single language APIs.

We could also try to come up with a generic way to model/declare symbol resolution. That's something I definitely want in VMF-Text (at least long-term).

I am still working on lexical preservation. I sketched out some ideas. Just to see how hard it is and which consequences it has for the API design and the code generator. If that's done I will start to actually use VMF-Text generated API in research projects and IDEs.

**Comment by matozoid** [comment]
Closing because inactive.

**Comment by ronansayao** [comment]
Is there any updates on this?
I'd like to help to develop KotlinParser.
I need some help, somebody can help-me?

**Comment by ftomassetti** [comment]
I would love KotlinParser. I would just suggest to use ANTLR instead of JavaCC.
Also, I would check if the official Kotlin compiler has a parser you could just use.

**Comment by ronansayao** [comment]
@ftomassetti Thanks.
