### ISSUE TITLE
How to find fully qualified name of method invocation target?

### ISSUE THREAD

**Issue by marcosscriven** [javaparser/javaparser#165]
Here's a simple example:

```
import com.mycompany.myproject.FooInterface;
import com.mycompany.myproject.FooImpl;

public class Test
{

   private final FooInterface memberFoo = new FooImpl();

   public void aMethod() {
       memberFoo.bar();
   }

   public void anotherMethod(FooInterface externalFoo) {
      externalFoo.bar();    
   }

}
```

Looking at this trivial and convoluted example in isolation, it's easy to see that:
- There's two invocations of `com.mycompany.myproject.FooInterface.bar()`.
- That the invocation in `aMethod()` is definitely on a `FooImpl` object.
- We don't know what the impl is passed to `anotherMethod`.

(Of course, in a more complex example `memberFoo` (if it weren't final or private) might not still be a `FooImpl`.)

Is it possible with JavaParser to at least discover the fully qualified name of the invocation target? Digging into `MethodVisitor`, I can get hold of a `MethodCallExpr`, which gives me a scope and a name. So the question becomes, what's the best way to lookup the fully qualified name of the scope? So far as I can see, one would have to look up the member in the `CompilationUnit` by scope name, and then parse the imports.

Optionally, it would be great to be able to also capture the usage of the `FooImpl` concrete class (assuming it's not a compilation error, and `FooImpl` really is a `FooInterface`). But I realise that's rather less trivial.

EDIT - The background to this is I'd like to statically analyse some code (that we know is compilable) and find all usages of methods on a given class or interface. Basic text search of course works in many cases, but for shorter or more generic method names, it's rather less effective.

**Comment by ftomassetti** [comment]
I think that what you are trying to do require a symbol solver. A symbol solver can be built using javaparser in combination to some libraries to examine JAR files because of course you can reference libraries in your source code.

I have been working on building a symbol solver on top of JavaParser as part of [effectivejava](http://github.com/ftomassetti/effectivejava). That piece of code is written in Clojure but it should not be too complicated to call it from Java. I would be extremely happy to help you reuse it and I would take the opportunity to improve it.

As an alternative you can build your own symbol solver, maybe these posts can help you getting started:
http://tomassetti.me/building-models-of-java-code-from-class-and-jar-files/
http://tomassetti.me/how-to-build-a-symbol-solver-for-java-in-clojure/

**Comment by marcosscriven** [comment]
Thanks @ftomassetti.

I wasn't really looking for anything quite so comprehensive; it's possible to determine the fully qualified name of a class of the method invocation without analysing anything else in the code base or in dependent JARs. I'm not looking to establish _where_ that target class is for my use case, just its name.

Of course the actual object at runtime could be any number of possible implementations, which is a more complex problem and would warrant a full 'symbol solver'.

**Comment by ftomassetti** [comment]
If I understand correctly, given an invocation:

``` java
foo.bar();
```

You want to find the fully qualified named of foo, right?

To do so you need to find the declaration of _foo_. If the _foo_ is a reference to a local variable or a parameter you should not have issues, right? However if it is inherited field you need to find the parent class, which could be a class in a JAR file or anyway a class for which you do not have the source code, right?

You could also have something like this:

``` java
foo.bar().baz().something();
```

in this case to understand what is the class on which something is called you need to resolve the previous calls and maybe the definition of _baz_ is in a class for which you do not have the source code.

I think you can solve your problem without looking at other classes, but looking just at the class containing the method invocation in a decent amount of cases but not in 100%. I do not know if for your problem is enough to go with the easy & fast solution.

But maybe I misunderstood what you are trying to do, these things are always hard to explain :)
Sorry if I misunderstood!

**Comment by ftomassetti** [comment]
I think we should have questions like this inserted in the documentation/F.A.Q.

**Comment by matozoid** [comment]
Is this still open because we should document it?

**Comment by matozoid** [comment]
... if so, open an issue for it.
