### ISSUE TITLE
get expression on right side of ':' inside foreach expression

### ISSUE THREAD

**Issue by freefire4547** [javaparser/javaparser#1661]
In  `for(int h:var.getArray())` I want to get expression `var.getArray()` . How can I do it ?

**Comment by matozoid** [comment]
Hello! Here are the tools you need: http://javaparser.org/inspecting-an-ast/ . Feel free to ask more questions if you can't figure it out.

**Comment by freefire4547** [comment]
@matozoid Actually, I wanted to know if there is any direct method to get that

**Comment by matozoid** [comment]
Yes, there is. You need to know which AST node you're looking for, and what its fields are and what they contain. You can read how to do that in the article so that we don't have to explain to people where each and every field is. It's a five minute read with clear examples.

Feel free to ask more questions if you can't figure it out.

**Comment by freefire4547** [comment]
Thanks, I got it !. I needed `ForeachStmt.getIterable()`
