### ISSUE TITLE
Migration-Guide HELP 1.0 to 3.0

### ISSUE THREAD

**Issue by victorbergar** [javaparser/javaparser#1663]
Hello, I'm migrating a project made in javaparser 1.0 to javaparser 3.0.

There is no information on migration from Java 1.0 to 2.0.

Can someone give me the information?

I am finding it impossible to know what to do with:
LongLiteralMinValueExpr
EmptyTypeDeclaration
EmptyMemberDeclaration
TypeDeclarationStmt
SwitchEntryStmt
VariableDeclaratorId
((CompilationUnit) nodeHierarchy.get (0)). GetPackage ()

etc..

Thank you very much.

**Comment by matozoid** [comment]
Hi! Some of them can be found here: https://github.com/javaparser/javaparser/wiki/Migration-Guide

Nobody of the current team worked on version 1, so we actually cannot write a migration guide... But we'll do our best to help with questions.

- `LongLiteralMinValueExpr` - see #605
- `EmptyTypeDeclaration` - see migration guide
- `EmptyMemberDeclaration` - see migration guide
- `TypeDeclarationStmt` - I think you want #668
- `SwitchEntryStmt` - still exists, so I don't know what the problem is
- `VariableDeclaratorId` - see migration guide
- `((CompilationUnit) nodeHierarchy.get(0)).getPackage()` - try `getPackageDeclaration()`

**Comment by victorbergar** [comment]
Thanks so much!!!! Matozoid.

**Comment by matozoid** [comment]
No problem!

**Comment by freddielaure** [comment]
Hi @matozoid ,

i migrate from 1.0 to 3.0

i have following errors

1- setTypeArgs

    private Type getGenericType(IType typeParameter) {
        if (typeParameter instanceof IParameterizedType) {
            IParameterizedType paramType = (IParameterizedType)typeParameter;
            List<Type> recursiveType = getGenericTypes(paramType.getTypeArguments());
            ClassOrInterfaceType classType = new ClassOrInterfaceType(paramType.getTypeName());
           classType.setTypeArgs(recursiveType);
            return classType;
        } else {
            return ASTHelper.createReferenceType(typeParameter.getTypeName(), 0);
          
        }        
    }

how to replace classType.setTypeArgs(recursiveType);?



2- `getTypes`


    private TypeDeclaration findType(String typeName) {
        List<TypeDeclaration> types = (List<TypeDeclaration>) cu.getTypes();        
        for(TypeDeclaration td : types) {
            if (td.getName().equals(typeName)) {
                return td;                
            }
        }
        return null;
    }

with which method should i replace getTypes?


3- ModifierSet.PUBLIC

    public void createInterface(String name) {
        currentClass = new ClassOrInterfaceDeclaration(ModifierSet.PUBLIC, true, name);
        ASTHelper.addTypeDeclaration(cu, currentClass);                
    }

What is the Variante for ModifierSet.PUBLIC in 3.0.0?


Thanks


Laure

**Comment by matozoid** [comment]
Hi @freddielaure! This issue is closed, can you open a new issue for this please?

**Comment by freddielaure** [comment]
@matozoid yes. Thanks you
