### ISSUE TITLE
Question regarding JavaParserFacade ClearInstance method

### ISSUE THREAD

**Issue by parvez2014** [javaparser/javaparser#1670]
I am using JSS for multi-version program analysis. Consider that I have already analyzed version-1 source files with JSS. Now, I need to analyze version-2, which has 10 new source files and furthermore, some source files in version-1 are modified in version-2 and some are deleted. 
From https://github.com/javaparser/javaparser/issues/1562, I found that to analyze version-2 source files, I need to collect files again using a new collection strategy as It is not possible to add new files later.
After analyzing version-1 source files, I need to remove all type information collected by JavaParserFacade from version-1 source files. Should I call the clearInstance() method and then collect source files of version-2 with a new collection strategy?
Is it the case that calling JavaParserFacade.clearInstance() remove all collected type information (does it mean a fresh start)?
Thanks.

**Comment by ftomassetti** [comment]
I think that `JavaParserFacade.clearInstance` should do that but I also think this is not a typical usage of JP so I would double check. I would try to first solve everything in V2 of your project and save that information, then start the process again and solve first V1 and then V2 and verify that this time you get the same information as you did when you solved exclusively V2. That should reassure you it works and help us double checking we are not missing anything

**Comment by daanschipper** [comment]
The `JavaParserFacade` has a cache of the `Node` it already has solved together with the resulting `ResolvedType`. So this means if you apply some changes to the source code, this isn't reflected by the cache. 

However, since you're dealing with different versions of source code, I would suspect that you also have two different `TypeSolver`s, one for V1 and one for V2. By calling `JavaParserFacade.get(TypeSolver)`, you get an instance specific to that typesolver, which means you have two caches, one for V1 and one for V2 again.

**Comment by daanschipper** [comment]
So to answer your question, `JavaParserFacade.clearInstances()` only clears the static `Map<TypeSolver, JavaParserFacade> instances`, with it's corresponding cache of already solved nodes.

If you still need to resolve symbols for V1, keep the `TypeSolver`, otherwise you can clear the instances and collect a new TypeSolver using a collection strategy to clear the cache of the `JavaParserFacade`

**Comment by parvez2014** [comment]
Thank you both. That means I can create different typesolvers. Calling JavaParserFacade.get( TypeSolver) will register the typesolver. Calling ClearInstances will remove all the typesolvers. I will check the result as suggested by fmasseti. I am curious whether there are other caches used by JSS. Can you give me any other related class names ? Thanks again..

**Comment by daanschipper** [comment]
Look at #1391, there is an active discussion on the caches used by the symbol solver.
