### ISSUE TITLE
isStatic() throws NullPointerException when called on an enum ResolvedFieldDeclaration

### ISSUE THREAD

**Issue by jjbr** [javaparser/javaparser#1699]
Take an enum definition as follows:
```
public enum MyEnum {
    SOME, ARBITRARY, VALUES
}
```

Now access an enum value with e.g. `MyEnum.SOME`, parse that expression and call `.resolve()` on it. Call `.isStatic()` on the resulting ResolvedFieldDeclaration (a cast is required beforehand).

Result: A NullPointerException is thrown when `isStatic()` is called. This is due to the fact that `isStatic()` tries to access the `wrappedNode` of the JavaParserFieldDeclaration, which doesn't exist for an enum field. 

How should this method behave? The concept of static fields in an enum is obviously a bit odd but perhaps there is a better way to handle this than to throw a NullPointerException? I'd suggest either returning `true` in this case or throwing a more specific/clear and not accidental-looking exception.

**Comment by malteskoruppa** [comment]
To me it looks like the problem is that a `ResolvedFieldDeclaration` is returned in the first place. It should be a `ResolvedEnumConstantDeclaration` instead. Then, there is no problem with an `isStatic()` method, because `ResolvedEnumConstantDeclaration` doesn't provide that method.

To clarify, let me recap the relevant parts of the JSS architecture. `FieldAccessExpr#resolve()` returns a `ResolvedValueDeclaration`. We have the following type hierarchy:

- (Interface) `ResolvedValueDeclaration`
  - (Interface) `ResolvedFieldDeclaration`
    - (Class) `JavaParserFieldDeclaration`
    - (Class) `ReflectionFieldDeclaration`
    - (Class) `JavassistFieldDeclaration`
  - (Interface) `ResolvedEnumConstantDeclaration`
    - (Class) `JavaParserEnumConstantDeclaration`
    - (Class) `ReflectionEnumConstantDeclaration`
    - (Class) `JavassistEnumConstantDeclaration`

In the case mentioned in the original post (and the test case provided in PR #1700), we can see that when calling `resolve()` on a `FieldAccessExpr` that represents an enum constant element (`MyEnum.SOME`), a `JavaParserFieldDeclaration` is returned, when actually, I would have expected a `JavaParserEnumConstantDeclaration`.

Therefore I do not think that the `isStatic()` method is the problem here. The real problem is that the wrong type of resolved declaration is returned in the first place.

`FieldAccessExpr#resolve()` returns a `ResolvedValueDeclaration`, so it is perfectly able to (and it should) return a `JavaParserEnumConstantDeclaration` (and not a `JavaParserFieldDeclaration`) in this case. At least, that's he behavior I would expect. :-)

@ftomassetti Or is it indeed expected for a `ResolvedFieldDeclaration` to be returned in this case? If so, why? Wouldn't a `ResolvedEnumConstantDeclaration` make more sense?

**Comment by ftomassetti** [comment]
mmm, probably you are right, it should be a ResolvedEnumConstantDeclaration after all
@malteskoruppa you are contributing very good points to discussions :)

**Comment by malteskoruppa** [comment]
Thank you, I'm happy to help! :blush:
