### ISSUE TITLE
ObjectCreationExpr with anonymous class body cannot be resolved on interface types

### ISSUE THREAD

**Issue by kgeilmann** [javaparser/javaparser#1757]
```JavaParserFacade.get(typeSolver).solve( expr )``` fails with a ClassCastException for ObjectCreationExpr nodes which have an anonymous class body and whose type is an interface, like in 
```
new Comparator<String>() {
   public int compare(String o1, String o2) {
       return 0;
    }
}
```
I've seen it failing with the following exceptions:

java.lang.ClassCastException: com.github.javaparser.symbolsolver.reflectionmodel.ReflectionInterfaceDeclaration cannot be cast to com.github.javaparser.resolution.declarations.ResolvedClassDeclaration

java.lang.ClassCastException: com.github.javaparser.symbolsolver.javassistmodel.JavassistInterfaceDeclaration cannot be cast to com.github.javaparser.resolution.declarations.ResolvedClassDeclaration

java.lang.ClassCastException: com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserInterfaceDeclaration cannot be cast to com.github.javaparser.resolution.declarations.ResolvedClassDeclaration

**Comment by malteskoruppa** [comment]
Quick comment: This is very similar to #1599.

There, the problem was that one cannot resolve method calls to methods defined in an anonymous class.

Here, the problem is that one cannot resolve object creation expressions to constructors defined in an anonymous class. (In this case, it is an implicit declaration of a default constructor).

This particular class cast expression problem stems from the fact that JSS first resolves the type of the instantiated object and simply assumes that it must always be a `ResolvedClassDeclaration`, since the type is being instantiated. But, in the case of an anonymous class, it could also be a `ResolvedInterfaceDeclaration`, of course. (As far as your class cast exceptions are concerned: Note that all of `ReflectionInterfaceDeclaration`, `JavassistInterfaceDeclaration`, and `JavaParserInterfaceDeclaration` are instances of `ResolvedInterfaceDeclaration`, which cannot be cast to `ResolvedClassDeclaration`.)

In the big picture, though, all of this is one big issue "implement support to resolve call expressions to callable declarations in anonymous classes".

**Comment by malteskoruppa** [comment]
Ah, re-reading that other issue, I see that the very problem mentioned here was already reported there too: https://github.com/javaparser/javaparser/issues/1599#issuecomment-392761331.

**Comment by matozoid** [comment]
@kgeilmann - if you are still around, can you retry with version 3.15.6? (It is being released while I'm writing this)
