### ISSUE TITLE
Check if ObjectCreationExpr ever gets non-null typeargs

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1809]
It seems like the typeargs are attached to the type, not the expression.

**Comment by edefazio** [comment]
Is this related to why annotations are "lost" if they are applied to ObjectCreationExprs?

i.e. if we have a TYPE_USE annotation:

```java
@Target({ElementType.TYPE_USE})
public @interface Test {}
```
...and we parse:  
```java 
Statement st = StaticJavaParser.parseStatement("N n = new @Test N();");
System.out.println("ST " + st );
```

the output is:
`"N n = new N();"` //missing Test annotation
 
Note: I've tested the other "weird" uses of TYPE_USE & TYPE_PARAMETER annotations with JP and these work fine:

```java 
class C implements @Test Serializable{
     //in type argument WORKS
     List<@Test String> emails = new ArrayList();
            
      void m() //on throws WORKS
           throws @Test RuntimeException {
           //in cast WORKS
           String t = (@Test String)emails.get(0);                
           //in instanceof WORKS
           boolean b = t instanceof @Test String;
     }
}
```

Other examples of weird Type Use / Type Parameter annotations:
https://dzone.com/articles/java-8-type-annotations

**Comment by matozoid** [comment]
Thanks! That seems to be more of a printer issue though. Can you move it to a separate issue?

**Comment by edefazio** [comment]
sure, hey thanks for being so prompt! (btw this tool is great)

**Comment by matozoid** [comment]
And thank you too from me and the other 108 contributors :-)

**Comment by matozoid** [comment]
Well, it's surprising to find a bug in the grammar nowadays, but that's what it was. And of course you were right and the issues were connected :-)

**Comment by edefazio** [comment]
hey thanks again... I follow the talk on Gitter and you guys don't get enough love, but you deserve it

TBH I found the "bug" whilst trying to break my code which heavily uses JP, _(so I'm trying every odd corner case and crazy thing Java devs can do)..._ I've sometimes found (what I thought were bugs) in JP and they **turned out to be a bug my code**, so I try to be careful and not waste everyones' time.

Keep on rocking though... I've been real happy with making the decision/investment with JavaParser a few years ago 

(also... fwiw... I almost wonder if a rename of JavaParser is in order... not that its a bad name, but it does so, so much more than just "parsing"... the real good stuff IMHO is the model (and walking, visiting/listening) stuff... great great stuff)... 

cheers,
eric

**Comment by matozoid** [comment]
Thanks again :-) Drop all your ideas in the Gitter channel, because I have to close this issue now - it's release time!
