### ISSUE TITLE
ArrayIndexOutOfBoundsException when resolving lambda paramter

### ISSUE THREAD

**Issue by stefanleh** [javaparser/javaparser#1815]
java.lang.ArrayIndexOutOfBoundsException: 16
		at javassist.bytecode.ByteArray.readU16bit(ByteArray.java:27)
		at javassist.bytecode.LocalVariableAttribute.nameIndex(LocalVariableAttribute.java:207)
		at javassist.bytecode.LocalVariableAttribute.variableName(LocalVariableAttribute.java:217)
		at com.github.javaparser.symbolsolver.javassistmodel.JavassistUtils.extractParameterName(JavassistUtils.java:230)
		at com.github.javaparser.symbolsolver.javassistmodel.JavassistMethodDeclaration.getParam(JavassistMethodDeclaration.java:136)
		at com.github.javaparser.resolution.MethodUsage.<init>(MethodUsage.java:51)
		at com.github.javaparser.symbolsolver.model.typesystem.ReferenceTypeImpl.getDeclaredMethods(ReferenceTypeImpl.java:150)
		at com.github.javaparser.resolution.types.ResolvedReferenceType.getAllMethodsVisibleToInheritors(ResolvedReferenceType.java:406)
		at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveMethod(JavaParserTypeDeclarationAdapter.java:118)
		at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveMethod(ClassOrInterfaceDeclarationContext.java:98)
		at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.solveMethodInType(MethodResolutionLogic.java:563)
		at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:156)
		at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:245)
		at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:128)
		at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:136)
		at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:309)

for ResolvedMethodDeclaration:

    JavassistMethodDeclaration{ctMethod=javassist.CtMethod@158c43f8[private lambda$0 (Lcom/companyname/open/framework/messaging/Message;Lcom/oxaion/open/Request;)V]}

The lambda is an implicit one, which is created by java itself cause of a hasNext() call implemented in class the current one extends from. This means the method which calls hasNext() got the parameters shown in the ResolvedMethodDeclaration above. 

    @Override
    public void execute(Message message, Request request) {
    ...
    if (hasNext()) {
      return;
    }
    ...
    }

**Comment by stefanleh** [comment]
The bug might be in JavaAssist, please see `com.github.javaparser.symbolsolver.javassistmodel.JavassistUtils.extractParameterName(CtBehavior, int)`.

**Comment by Julien-JLT** [comment]
This issue is quite old but it doesn't appear to be resolved, and I'm experiencing it on my projet.

I have the exact same message (ArrayIndexOutOfBoundsException: 16) and stack, although it does not appear on a lambda expression, but on a regular method definition in an interface when trying to resolve the parameter name:
```
@Override 
<T extends MyObject> List<T> criteriaLookup(MyObject myObject) throws ProjectFunctionalException;
```

I have found nothing out of the ordinary on that class or method declaration that could explain this behavior.

@stefanleh did you manage to resolve this issue on your side, which could give me a clue to resolve mine ?

**Comment by MysterAitch** [comment]
Could you provide a reproducible JUnit test (or similar) please?

**Comment by stefanleh** [comment]
> @stefanleh did you manage to resolve this issue on your side, which could give me a clue to resolve mine ?

Hate to say that, but, after investing like 2-3 workdays in the problem, i moved on to Spoon cause of this issue. I had a long and good discussion on the matter with the JavaParser guys and understood that its really complicated to resolve method signatures right in Java. Please read on in https://github.com/javaparser/javaparser/issues/1783#issuecomment-415432154

**Comment by jlerbsc** [comment]
Hi @Julien-JLT could you provide us a simple test case to reproduce this issue. Thanks.

**Comment by jlerbsc** [comment]
We have no test case to reproduce this issue so i close it. You can reopen this issue if you have new information to provide us.

**Comment by Blackgen** [comment]
I think I found a solution for this issue:

In JavaassistUtils the name of parameters  is retrieved with `attr.variableName(int)` however it shoud use `attr.variableNameByIndex(int)`

The javadoc of "variableNameByIndex" states the following:
```
/**
* Returns the name of the local variable with given index.
* If you want to get the parameter name of method with correct order,
* you should using this method.
*
* @param index         the index of the local variable.
*/
```

I've been debugging this exception for some time and found out that `attr.variableName(int)` doen't always return the correct name  -  `attr.variableNameByIndex(int)` seems to be correct all the time.
I only did some tests, with static & non-static methods and various param counts. 
So please check before adding this fix.

I don't need the actual parameter name, I just wanted to get rid of the exception. 

Example of the fix:
https://github.com/Blackgen/javaparser/commit/8b64c6e18fabe04c7313bc6ad0b3756134a575fd

**Comment by jlerbsc** [comment]
Hi @Blackgen do you want to make a pull request for this fix?

**Comment by Blackgen** [comment]
Maybe, I just found a case where the replacement method does not work, but the old one does.
I'll look into this for a bit and if I find a reliable fix I'll create a PR.

**Comment by Blackgen** [comment]
I did some tests where I logged each invocation of `extractParameterName` and the results of both options.

In total I have 1338 unique entries (~18k with duplicates).

- Implementation with `attr.variableName(int)`
  - resulted in an error 297 times (22.19%)
  - differed in its result against `attr.variableNameByIndes(int)` 218 times (16.29%) (errors not counted)
- Implementation with `attr.variableNameByIndex(int)`
  - resulted in an error 11 times (0.82%)
- In the 11 cases where `attr.variableNameByIndex(int)` failed:
  - `attr.variableName(int)` was correct 2 times, but also failed in 7 cases

I've checked about half of the methods where the result differed and there `attr.variableNameByIndex(int)` was correct all the time. This would mean that the old implementation is not correct in about 38% of all unique cases.

In my testing the error cases were consistent, the jars I've used are obfuscated or compiled without debug symbols.

I'd suggest to change the implementation to use `attr.variableNameByIndes(int)`.
I also want to suggest to surround it with a try/catch for the ArrayIndexOutOfBoundsException and return an empty Optional, although it's a RuntimeException. In many cases the parameter name is not actually needed. This happes for example when a signature is beeing created. The types of the parameters are resolveable, even if the name is not found. In those cases it would be better to get a result, instead of the exception.

I'll try to create a jar which would force such errors, then this could be added as a testcase.

**Comment by jlerbsc** [comment]
First, can you provide a simple test case that demonstrates the problem?

**Comment by Blackgen** [comment]
I've added a test in my fork:

https://github.com/Blackgen/javaparser/commit/af63fb1eb9516ab40fd36ba58433f764a3c79856

In the unittest is a second visitor to print the error for all methods of the class in the jar.


The error is forced with a obfuscated jar. No parts of the classes have been obfuscated, only some random code was added by an obfuscator.
However such jars cause the issues for me.
With the other method ("attr.variableNameByIndex(int)") those parameters can be retrieved without any issues.


Edit - Here is my suggestion for a fix for this issue:
https://github.com/Blackgen/javaparser/commit/eec0b021297a08868a56ace9e552505b39a82a56

**Comment by jlerbsc** [comment]
It is possible that this is a bug on Javassists in which case it would be better to request a fix in the Javassists project rather than trying to fix this bug in JavaParser.

It is also possible that it is a bug in Javaparser because the javadoc indicates this and the code does not seem to correspond to this documentation.

In both cases, the context of the appearance of this problem should be highlighted in order to possibly determine its origin. Then highlight the bug(s) using unit tests to verify the effectiveness of the fix.

> /**
     * Returns the {@code paramNumber}th parameter of a method or constructor, if it is available.
     * The name is not available, if
     * . the method is abstract, i.e. explicitly declared as abstract or it is a non-default interface method
     * . methods and constructors from jar files, which have been compiled without debug symbols
     * 
     * The parameters are counted from 0, skipping the implicit {@code this} parameter of non-static methods.
     */
    static Optional<String> extractParameterName(CtBehavior method, int paramNumber)

**Comment by jlerbsc** [comment]
Thanks for this suggestion and your patience.
