### ISSUE TITLE
Question about extracting file call dependency by using javaparser

### ISSUE THREAD

**Issue by wx930910** [javaparser/javaparser#1855]
Hello,

I am using javaparser and I think it's a very powerful package!

Is there a chance to extract file call dependency by using javaparser or java symbol solver?

For example if I have a the source code for file A, and file A call a method in file B.
```
import B;
class A {
	public void method() {
	       B.print();
	}
}
```

```
class B {
	public static void print() {
		System.out.println("test");
	}
}
```
Can I use javaparser to extract this dependency without the source code for file B?

Any help will be greatly appreciated!

**Comment by matozoid** [comment]
Hello! Do you have class B in a jar as a class file, or don't you have class B at all?

**Comment by wx930910** [comment]
Hello!
@matozoid Thanks for the prompt reply!
In my case, I don't have class B at all.

**Comment by matozoid** [comment]
Well, have to call in @ftomassetti then.

**Comment by ftomassetti** [comment]
ftomassetti answering from Luxembourg City :)

If you do not have class B at all then currently JavaSymbolSolver would tell you that it has no idea what class B is. The problem is this: when you import `a.b.c.d.e` you could import different things like a class named `e` in a package named `a.b.c.d` or a class `e` inside a class `c` in a package named `a.b.c`. In order words this is ambiguous, therefore we cannot conclude from the import what classes exist, we need their definitions in a jar, or the source code or access them through reflection. Any of these three

**Comment by wx930910** [comment]
Thank you so much for ur response @matozoid @ftomassetti :)

I see the problem here! I will try another way to achieve my goal!

**Comment by wx930910** [comment]
@ftomassetti Thanks a lot for your perivous reply and it really helps!
Now I am able to include all the classes into the combinedTypeSolver, the problem is:
If a child class extend his parent class and the child class didn't import the parent class (if two classes are in the same folder, they don't need to import  parent class to extend it), I cannot solve the type of the parent class by using ClassOrInterfaceType.resolve() function.
Is there anyway to resolve the parent class in this case?

Any help will be greatly appreciated!

**Comment by ftomassetti** [comment]
Glad it helped!

Well, that seems as a bug to me. Could you provide a small and reproducible example of this and open an issue? This would help us a lot

**Comment by matozoid** [comment]
Closing because inactive.
