### ISSUE TITLE
Print source code based on line range

### ISSUE THREAD

**Issue by un0btanium** [javaparser/javaparser#1865]
Hello :)

I am currently trying to extract code snippets from a source file. I am already using the begin and end Position ranges the Node objects provide to determine the start and end line. I could now just open the file and extract the lines and print them, but I would like to know if JavaParser already provides such function.

I tested the PrettyPrinter and LexicalPreservingPrinter, however they dont seem to able to print the full lines, but only the node itself (which is the expected functionality).

I am interested in the full lines with the indentation.
For PrettyPrinter I get the following. It is missing the indentation for all lines (since the method is in a class).

```Java
public void myNotRecursiveMethod()
    int testVar = 10;
    myRecursiveMethod(testVar);
}
```

For LexicalPreservingPrinter I get the following. It is more accurate to the original. But it is missing the indentation for the first line.

```Java
public void myNotRecursiveMethod()
        int testVar = 10;
        myRecursiveMethod(testVar);
    }
```

Since only the Node object gets printed for Variables and Parameters I only get stuff like

```Java
new ArrayList<>()
```
instead of the whole line

```Java
        List<Integer> list = new ArrayList<>();
```

This is only a small annoyance. If there is no functionality of JavaParser directly, I will manually extract the lines from the source file. The Printing functionality is already very impressive, it would be impressive if it could do this as well ;)

**Comment by matozoid** [comment]
Hi! I'm afraid JavaParser is not as impressive as you would like then ;-) The problem is just as you found out: nodes don't correspond nicely to lines. They start and end on a character somewhere. Which makes sense, since Java syntax is not really end-of-line aware like Python or so.

Then again, with the newer Java functionality like `Files.readLines` (or so) it would be very easy to ask a node which lines it occupies, and then print those lines.

**Comment by un0btanium** [comment]
That's okay :)

Indeed. It is not a huge deal to just do it manually.
