### ISSUE TITLE
Symbol solver with MethodCallExpr exception

### ISSUE THREAD

**Issue by wozuo** [javaparser/javaparser#1868]
Hi all,

First of all I want to say thank you for this great project, I really appreciate it! 

I'm trying to resolve the types of "MethodCallExpr" expressions. And I noticed some inconsistent behavior while doing so. Take for example the following code:
```
SSLSocket vSocket = (SSLSocket) socket;
vSocket.setEnabledProtocols(supportedProtocols.toArray(new String[supportedProtocols.size()]));
List<String> ciphers = new ArrayList<String>(Arrays.asList(vSocket.getEnabledCipherSuites()));
```
The first MethodCallExpr `vSocket.setEnabledProtocols(supportedProtocols.toArray(new String[supportedProtocols.size()]))` is not resolved and the following exception is thrown:
```
Exception: java.lang.RuntimeException: Unable to calculate the type of a parameter of a method call. Method call: vSocket.setEnabledProtocols(supportedProtocols.toArray(new String[supportedProtocols.size()])), Parameter: supportedProtocols.toArray(new String[supportedProtocols.size()])
```
The second MethodCallExpr `vSocket.getEnabledCipherSuites()` on the other hand is resolved just fine to the correct type `SSLSocket `.

The code I'm using to resolve the type is: `typeString = ((MethodCallExpr) expr).resolve().getClassName();`

Am I doing something wrong? 

Thanks for your help and best regards,
Marc

**Comment by malteskoruppa** [comment]
The problem seems to be that the symbol solver cannot resolve the type of the expression used as a method argument, namely, `supportedProtocols.toArray(new String[supportedProtocols.size()])`. Therefore, it cannot resolve the method call expression where this argument is used in.

Now why the symbol solver isn't able to resolve the type of that expression, I can't tell. In order to resolve the type of this expression, it has to do a number of steps (e.g., resolve the type of the variable `supportedProtocols`, resolve the method declaration that corresponds to the call expression `supportedProtocols.toArray(...)`, for which the type of the argument to that method call has to be determined, etc.). Somewhere, this fails. It could be a configuration problem, i.e., maybe the symbol solver doesn't have all the necessary information (e.g., the type of `supportedProtocols` is a class that's defined in a piece of code that was not passed to the symbol solver); it could also be a bug in the symbol solver.

To narrow down the problem: What happens if you try to resolve the (simplified) expression `vSocket.setEnabledProtocols(new String[0])` ?

**Comment by wozuo** [comment]
Thanks for your detailed answer! That makes sense, is there a way to tell the symbol solver to ignore the arguments? Because at this point I'm only interested in the type of vSocket. 

And to elaborate on the code snippets I gave above, `supportedProtocols` is declared and initialized in the same method, here is the full method:
```
private Socket secureSocket(Socket socket) {
        if (!(socket instanceof SSLSocket)) {
            return socket;
        }

        SSLSocket vSocket = (SSLSocket) socket;

        List<String> supportedProtocols = new ArrayList<String>(
                Arrays.asList(vSocket.getSupportedProtocols()));
        supportedProtocols.remove("SSLv3");
        vSocket.setEnabledProtocols(
                supportedProtocols.toArray(new String[supportedProtocols.size()]));

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT_WATCH) {
            List<String> ciphers = new ArrayList<String>(
                    Arrays.asList(vSocket.getEnabledCipherSuites()));
            ciphers.remove("TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA");
            ciphers.remove("TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA");
            vSocket.setEnabledCipherSuites(ciphers.toArray(new String[ciphers.size()]));
        }
        return vSocket;
    }
```

**Comment by malteskoruppa** [comment]
> is there a way to tell the symbol solver to ignore the arguments? Because at this point I'm only interested in the type of vSocket.

You can't tell the symbol solver to ignore the arguments when resolving a method call expression, because resolving the arguments is a necessary precondition to resolve the method call expression.

However, if you are only interested in resolving the _scope_ of the method call expression `vSocket.setEnabledProtocols(supportedProtocols.toArray(new String[supportedProtocols.size()]))`, i.e., given that method call expression, you want to resolve the name expression `vSocket`, then you could do it like so:

    methodCallExpr.getScope().get().asNameExpr().resolve()

Note that this code assumes two things:
* That the method call expression has a scope (i.e., `methodCallExpr.getScope()` is not an empty optional); and
* That this scope is a name expression (generally, the scope of a method call expression could be one of many things, such as a field access expression for example, or another method call expression, etc.)

Obviously, you should check these things in your code, or you will run into runtime exceptions if you use the above code for arbitrary method call expressions. For the particular method call expression discussed here, these assumptions are true (the method call expression has a scope, and that scope is a name expression), but for other method call expressions, they may not be.

**Comment by malteskoruppa** [comment]
> And to elaborate on the code snippets I gave above, `supportedProtocols` is declared and initialized in the same method, here is the full method ...

Your code is fine, so the problem has to be in the symbol solver. I just checked, and the reason that you cannot resolve the whole method call expression is indeed that you cannot resolve the argument in that method call expression, and the reason that you cannot resolve the argument is indeed a bug in the symbol solver.

To help whomever will fix this bug in the future, I narrowed it down a little bit. Consider this statically perfectly valid piece of Java code:

```
class A {
    public void foo() {
        toArray(new String[0]);
    }

    public void bar() {
        B b = null;
        b.toArray(new String[0]);
    }

    public <T> T[] toArray(T[] tArray) {
        // ...
    }
}

class B {
    public <T> T[] toArray(T[] tArray) {
        // ...
    }
}
```

Note that:
1. The methods `A.toArray` and `B.toArray` are identical.
2. The return type of these methods depends on the type of their first argument. Therefore, resolving the return type of these methods is particularly tricky for the symbol solver.
3. The method `A.foo` calls `A.toArray`, while the method `A.bar` calls `B.toArray`.

Now, let's try to resolve the type of these method call expressions using `methodCallExpr.calculateResolvedType()`, respectively. The results are:

- When we try to resolve the method call expression `toArray(new String[0])` in method `foo`, it works. The result is:

      ResolvedArrayType{ReferenceType{java.lang.String, typeParametersMap=TypeParametersMap{nameToValue={}}}}

    Pretty neat, because this was not trivial! The symbol solver had to deduce the return type from the argument type, and it successfully did so.

- When we try to resolve the method call expression `b.toArray(new String[0])` in method `bar`, it *does not* work. The result is a runtime exception:

        java.lang.RuntimeException: java.lang.String[] T[]

    This doesn't work, even though here the symbol solver has to do something very similar as in the previous case. It appears that the fact that the method call expression is scoped _in combination_ with the generic return type of the called method confuses the symbol solver.


Now back to your problem. The argument of the method call expression you're trying to resolve is: `supportedProtocols.toArray(new String[supportedProtocols.size()])`. The declaration of this `toArray()` method is the same as in the code snippets above, i.e., `public <T> T[] toArray(T[] tArray)`. In other words, you are basically in the second scenario depicted above (scoped method call expression with generic return type), and the same runtime exception occurs. Ultimately, this then triggers an `UnsolvedSymbolException` while trying to resolve the method call expression that uses this argument.

As long as you don't need to resolve the whole method call expression (but only the scope), you're fine, as explained in my previous post. Unfortunately, currently there is no way for you to resolve this particular method call expression as a whole.

**Comment by jlerbsc** [comment]
This issue is now resolved.

    public class Issue1868Test extends AbstractSymbolResolutionTest {

    @Test
    public void test() {
        
        Path testResources= adaptPath("src/test/resources/issue1868");
        
        CombinedTypeSolver typeSolver = new CombinedTypeSolver();
        typeSolver.add(new ReflectionTypeSolver());
        typeSolver.add(new JavaParserTypeSolver(testResources));

        StaticJavaParser.setConfiguration(new ParserConfiguration().setSymbolResolver(new JavaSymbolSolver(typeSolver)));

        String s = 
                "class A {\n" + 
                "    public void foo() {\n" + 
                "        toArray(new String[0]);\n" + 
                "    }\n" + 
                "    public void bar() {\n" + 
                "        B b = null;\n" + 
                "        b.toArray(new String[0]);\n" + 
                "    }\n" + 
                "    public <T> T[] toArray(T[] tArray) {\n" + 
                "        // ...\n" + 
                "    }\n" + 
                "}";
        
        CompilationUnit cu = StaticJavaParser.parse(s);
        
        List<MethodCallExpr> mces = cu.findAll(MethodCallExpr.class);
        
        System.out.println(String.format("%s resolved to %s", mces.get(0), mces.get(0).resolve().getQualifiedName()));
        System.out.println(String.format("%s resolved to %s", mces.get(1), mces.get(1).resolve().getQualifiedName()));
        
    }

}
