### ISSUE TITLE
Error in PrettyPrintVisitor.visit

### ISSUE THREAD

**Issue by baumato** [javaparser/javaparser#1907]
I just updated from version 3.5.2 to 3.6.27. Now I have following issue:

Take this class:

```java
package de.baumato.loc;


public class SomeClass
{

    private int x;
    private int y;
		public SomeClass(int x, int y)
		{
			super();
			this.x = x;
			this.y = y;
		}
    
		
		/**
		 * mutli line comment	
		 */
		public void add(int x, int y) 
		{
			// single line comment
			this.x+= x;
			this.y+= y;
		}


		
		public int getX() 
		{
			return x;
		}


		
		public int getY() 
		{
			return y;
		}
		
		
}
```
and process it with:

`String code = JavaParser.parse(someClass).toString()`

then the resulting `code` always contains one space more in front of 'multi line comment' than the original source code.

I assume it has something to do with the logic in 
`PrettingPrintVisitor.visit(final JavadocComment n, final Void arg)`
The variable `prependSpace` is always evaluated to true for multi line comments.

**Comment by baumato** [comment]
I think, it should be:
boolean prependSpace = Arrays.stream(lines).anyMatch(line -> !line._trim()_.isEmpty() && !line.startsWith(" "));

**Comment by matozoid** [comment]
Yes, something is wrong here. Thanks!

**Comment by matozoid** [comment]
@baumato - I made a test case PR that is not failing - can you help me make it fail?

**Comment by MysterAitch** [comment]
@matozoid The issue is that if *any* of the lines of the comment do not contain a leading space, then *every* line of the multi-line comment gets indented by a single space. 

In @baumato 's case, his whitespace is what is exposing this (he has leading tab characters in the code snippet above).

Also note that the existence of the leading space is "looked for" on the left-hand side of the asterisk, while the space indentation gets added to the right-hand side of the asterisk.

See below for some failing test cases (the first passes, the second two don't).

```java

    private String expected = "public class SomeClass {\n" +
            "\n" +
            "    /**\n" +
            "     * tester line\n" +
            "     * multi line comment\n" +
            "     *   multi line comment\n" +
            "     * multi line comment\n" +
            "     *    multi line comment\n" +
            "     */\n" +
            "    public void add(int x, int y) {\n" +
            "    }\n" +
            "}\n";

    @Test
    public void javadocIssue1907_allLeadingSpaces() {
        String input_allLeadingSpaces = "public class SomeClass{" +
                "/**\n" +
                " * tester line\n" +
                " * multi line comment\n" +
                " *   multi line comment\n" +
                "   * multi line comment\n" +
                "    multi line comment\n" +
                " */\n" +
                "public void add(int x, int y){}}";

        CompilationUnit cu_allLeadingSpaces = JavaParser.parse(input_allLeadingSpaces);
        assertEqualsNoEol(expected, cu_allLeadingSpaces.toString());
    }

    @Test
    public void javadocIssue1907_singleMissingLeadingSpace() {
        String input_singleMissingLeadingSpace = "public class SomeClass{" +
                "/**\n" +
                "* tester line\n" +
                " * multi line comment\n" +
                " *   multi line comment\n" +
                "   * multi line comment\n" +
                "    multi line comment\n" +
                " */\n" +
                "public void add(int x, int y){}}";

        CompilationUnit cu_singleMissingLeadingSpace = JavaParser.parse(input_singleMissingLeadingSpace);
        assertEqualsNoEol(expected, cu_singleMissingLeadingSpace.toString());
    }

    @Test
    public void javadocIssue1907_leadingTab() {
        String input_leadingTab = "public class SomeClass{" +
                "/**\n" +
                "\t * tester line\n" +
                " * multi line comment\n" +
                " *   multi line comment\n" +
                "   * multi line comment\n" +
                "    multi line comment\n" +
                " */\n" +
                "public void add(int x, int y){}}";

        CompilationUnit cu_leadingTab = JavaParser.parse(input_leadingTab);
        assertEqualsNoEol(expected, cu_leadingTab.toString());

    }
```

**Comment by matozoid** [comment]
Cool! I've updated the testcase PR.

**Comment by matozoid** [comment]
@baumato @MysterAitch - all these tests are running now in the PR, thanks to @MysterAitch discovery that I was looking at the wrong side of the *... I completely missed that :-( Can you okay it?

**Comment by MysterAitch** [comment]
Oops, didn't intend that tinkering from yesterday's commit message to become publicly linked! It's what was work-in-progress from yesterday when I was looking into it and I suppose it got pushed when I revisited it this evening. _(my fault for not being disciplined with my "local"/forked branches!)._

Since it did get linked, if anyone does end up looking at it, I should add that that branch normalises the minimum indentation to be precisely one space. This includes adding it in if it needs indenting (i.e. this issue), but ALSO de-indenting the content which is different to current behaviour (e.g. if all lines of the comment have ten spaces it'll de-indent them all to be one space).

Later commits on that branch fix it up better (stealing Danny's much more elegant approach!) and also normalise annotations in the javadoc (e.g. `@param` and `@return`) to always be indented by a single space even if they're indented further in the original.

Current work in progress attempts to handle tab characters in the leading whitespace that gets trimmed. These changes/suggestions are perhaps better suited to a suggestion in a separate issue rather though, sorry!!

**Comment by matozoid** [comment]
@MysterAitch whatever you do, remember that the pretty printer can do whatever it likes to Javadoc, because there is no standard. It's just what we think is "pretty" :-)

Do open a new issue!

Can I get you to work on symbol solver of the Java 12 switch expression instead?
