### ISSUE TITLE
I m not able to get one particular 'then part' of IF-statement

### ISSUE THREAD

**Issue by omkarendra** [javaparser/javaparser#1911]
Hi, 
I have one code segment as below

if (fMap.containsKey(filename))
            return (Image) fMap.get(filename);

Now, I am using following iterative process to extract each statement within then block; generally it is successful until I found an issue.

'for (Node n : ifstmt.getThenStmt().getChildNodes())' 
{
//Do something with 'n'
}

Here, n is omitting that statement within Then-part is a 'return' stmt ; It is showing it as 'CastExpr'

Thank you.

**Comment by matozoid** [comment]
I assume this is because usually the statement in the then-clause is a `BlockStmt` containing child statements, because usually the then clause has `{` and `}`. In this case there is only the return, so now there is no `BlockStmt`, only a `ReturnStmt`. The child of that statement is the cast to Image.

Consider...
- checking the type of the statement in getThenStmt, or
- using a visitor on it to find the types of nodes you are interested in, or
- using one of the find-methods on it to find the type of node you are interested in

`getChildren` is mostly not the best approach to anything.

**Comment by omkarendra** [comment]
Thanks.

Yes! I did put a check if it is ReturnStmt.

Thanks for a quick response. :)

**Comment by matozoid** [comment]
Good! Remember that you can find any kind of statement there, not just return :-)

**Comment by omkarendra** [comment]
okay! :)

**Comment by matozoid** [comment]
@omkarendra - did you intend to reopen this? :-)

**Comment by omkarendra** [comment]
Ohh!! no. That was accidental :(. All is fine. :D
