### ISSUE TITLE
ForeachStmt (< 3.6) vs ForEachStmt (>= 3.7)

### ISSUE THREAD

**Issue by nkratzke** [javaparser/javaparser#1918]
I found a small difference in a Statement class naming. The foreach statement concept was named in

- in version 3.6 as `ForeachStmt` (partly camel-cased)
- and in version 3.7 as `ForEachStmt` (fully camel-cased).

That is not a big thing, however, it means that the 3.7 API is not fully downward compatible with the 3.6. I am unsure, whether there are simlar "camel-case" renamings happended throughout the project. I had a broken gradle build due to that seconds ago.

It would be nice for API users to keep the former `ForeachStmt` for a while and mark it as `@Deprecated`.

**Comment by ftomassetti** [comment]
We decided on purpose to introduce API breakage in JP 3.7. The reason is that we have been waiting for a long time to move to JP 4.0 but we simply do not have the energies necessary for a new release, so we decided instead to introduce these very limited API breaking changes in 3.7.

They are clearly stated in the [changelog](https://github.com/javaparser/javaparser/blob/master/changelog.md).

We could leave the old class together with the new one but anyway all methods would return the new one, so I am not sure if that would help.

**Comment by ftomassetti** [comment]
I forgot:
thank you for opening this issue, these kinds of conversations help us learning how to communicate better and learn how to reduce the impact of the changes we introduce. We appreciate you taking the time to explain the issue you are facing to us because in general it is difficult for us to obtain feedback

**Comment by nkratzke** [comment]
OK, seems RTFM issue on my side ;-)
You may close this issue then.

**Comment by ftomassetti** [comment]
I would not dare saying that to a Professor, of course ;)

Jokes aside, we realize this can be surprising and surprises in general are bad, so we are learning the best way to do these things

**Comment by matozoid** [comment]
@nkratzke so for learning: what would you say is the best place to announce breaking changes like this?

**Comment by nkratzke** [comment]
Hard to say. I would not say that there is the one and best answer. However, a best practice from my experience is to announce such changes via @Depracated annotations in the upfront of the change - and of course in the changelog as you have done (or in special documents explaining version upgrades from version x.y.z to x.y+1.z).
