### ISSUE TITLE
How to refactoring variable quickly

### ISSUE THREAD

**Issue by immerser** [javaparser/javaparser#1921]
How to refactoring variable quickly

from

```
public Class A {
   private String a;

  public void print() {
    System.out.println(a);
 }
}
```

to

```
public Class A {
   private String b;

  public void print() {
    System.out.println(b);
 }
}
```

**Comment by matozoid** [comment]
Hi @immerser! This functionality is currently not in scope of the project. But the tools you need are there: you will need the symbol solver to find out which "a" is the same variable as another "a", then you need to rename all of them.

If it doesn't need to be 100% correct, you can simply use a visitor to rename all "a" SimpleNames.

**Comment by immerser** [comment]
How about supply util class to solve this

**Comment by matozoid** [comment]
How about you start an open source project that supplies refactorings

**Comment by pvojtechovsky** [comment]
You can look at the algorithms used in Spoon on https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/refactoring/Refactoring.java
There are similar refactorings already done ... just field rename is not there too. But it is somehow similar to other refactorings. So may be it will be helpful while writing he same for JavaParser

**Comment by ftomassetti** [comment]
The point is that writing those refactorings on top of Javaparser would be relatively simple, as other users have already implemented them themselves. What we are careful about is to add new features simply because we would have to _maintain_ them. Javaparser is used by a lot of people on a lot of contexts, having different requirements and also aim to support new releases of Java as soon as they are released. So that means that ensure a new feature is maintained is not trivial. For this reason we would love to have these features in a separate project. This is also what we did with the JavaSymbolSolver: it was born as a separate project and eventually it was merged in Javaparser. So I propose a deal: we help you implementing this and you could just put it in a simple utility class that could become the seed of a new small library built on top of javaparser.
Would that be of interest?

**Comment by ftomassetti** [comment]
@pvojtechovsky thank you for the pointers but I think the API used by Spoon is very different in nature, so when replying to issues in the Javaparser issue tracker it would be best to help users by providing examples based on the JP API
