### ISSUE TITLE
[Question] visit/accept method arg parameter

### ISSUE THREAD

**Issue by KaiNahrgang** [javaparser/javaparser#1937]
Hi,
I was wondering about the purpose of the arg parameters in the visit and accept methods - for example:

com.github.javaparser.printer.PrettyPrintVisitor#visit(com.github.javaparser.ast.stmt.IfStmt, java.lang.Void)
com.github.javaparser.ast.stmt.IfStmt#accept(com.github.javaparser.ast.visitor.VoidVisitor<A>, A)

Can someone please give me clarification on how to I use this correctly?

Thanks and best regards,
Kai

**Comment by SmiddyPence** [comment]
Hello Kai

Can I suggest you try the book, it is free if you move the slider: https://leanpub.com/javaparservisited

If you're impatient you can jump to page 13, otherwise I recommend starting from the beginning :)

There is also our chat room for general support and questions: https://gitter.im/javaparser/javaparser

Thanks!
