### ISSUE TITLE
comment after method param but before parentheses incorrectly associated.

### ISSUE THREAD

**Issue by JLLeitschuh** [javaparser/javaparser#199]
Originally declared:

``` java
@Namespace("cv") public static native void cornerMinEigenVal( @ByVal Mat src, @ByVal Mat dst,
                                     int blockSize, int ksize/*=3*/,
                                     int borderType/*=cv::BORDER_DEFAULT*/ );
```

Given the preceding example the comment `/*=3*/` is being associated with `int borderType`.
Meanwhile `/*=cv::BORDER_DEFAULT*/` isn't associated with anything.
Unsure how to resolve this problem as the entire library that I'm parsing is written this way.

After parsing it becomes (new lines have been retained):

``` java
@Namespace("cv")
public static native void cornerMinEigenVal(@ByVal Mat src, @ByVal Mat dst, int blockSize, int ksize, /*=3*/
int borderType);
```

I can't even get the `/*=cv::BORDER_DEFAULT*/` as an orphan of the parameter.

**Comment by ftomassetti** [comment]
This is not trivial to solve I think. Associating comments to node is based on a few heuristics.

Now, the comment `/*=3*/` is not inside the formal parameter definition `int ksize` because that definition ends at the identifier. It is instead inside the `FormalParameters` node, representing the whole list of parameters. It precedes the node of the following `FormalParameter` (borderType) so it is associated with it.

`/*=cv::BORDER_DEFAULT*/` is instead an orphan comment of the method definition

Comments attribution is performed on the AST where the commas do not exist. We should probably consider those comments retrieving them from the original source in order to be able to associate these comments as intended.

These are my initial thoughts. What do you think? Anyone has suggestions?

**Comment by ftomassetti** [comment]
We could verify if a comment is followed by a comma or an open parenthesis and in that case associate it with the node preceeding it

**Comment by JLLeitschuh** [comment]
Alternatively, I could preprocess the input text and rearrange it as necessary so the parser will read it correctly. I'm not sure if I can figure out a regex that will do this well though.

**Comment by JLLeitschuh** [comment]
I found a solution that works for my particular case.
I basically hijack the input stream, rewrite it as it comes in and provide the parser with what it expects.

``` java
/**
     * Regex splits the parameter into three distinct capture groups.
     * <ol>
     *     <li>The type and the param with an optional varargs.</li>
     *     <li>The comment that is after the parameter.</li>
     *     <li>The various ways that the parameter can end.</li>
     * </ol>
     */
    protected static final String methodReorderPattern = "([A-Za-z1-9]+ (?:\\.\\.\\.)?[a-z][A-Za-z0-9]*)(/\\*=[^ ]*\\*/)((?:,)|(?: \\)))";
    /**
     * Reorders the {@link FileParser#methodReorderPattern} capture groups so the JavaParser can correctly
     * associate the params with their respective comments.
     */
    protected static final String methodNewOrder = "$2$1$3";

    private static InputStream preProcessStream(InputStream stream){
        java.util.Scanner s = new java.util.Scanner(stream).useDelimiter("\\A");
        String input = s.hasNext() ? s.next() : "";
        input = input.replaceAll(methodReorderPattern, methodNewOrder);
        return new ByteArrayInputStream(input.getBytes(StandardCharsets.UTF_8));
    }
```

**Comment by matozoid** [comment]
This is unsolvable with the `CommentsInserter` class, and it seems a workaround was found.
