### ISSUE TITLE
Why is it valid to create a `LambdaExpr` with `isEnclosingParameters=false` with non-single parameter list?

### ISSUE THREAD

**Issue by l0rinc** [javaparser/javaparser#1997]
Hey,

```java
new LambdaExpr(new NodeList<>(), ..., false)
```
would result in illegal Java code, i.e. (`-> ...`, without params).
Is there maybe a way to ignore the `isEnclosingParameters` param in case it doesn't make sense?
Also, for multiple parameters it should also be ignored, i.e. the `isEnclosingParameters` parameter only makes sense for parameter lists with single values.

Would it make sense to only include this option for a constructor that accepts a single parameter and make it `true` for `NodeList`s?

**Comment by ftomassetti** [comment]
In my opinion something like this could be catched by successive checks. We have a mechanism for checks that I am not very familiar with but @matozoid could help us figuring out, when he is back grom holidays.

In general I think that the APIs should allow for building partially incorrect ASTs for several reasons. One of them being the fact that "illegal code" can still be parsed. We do not expect all code processed by JavaParser to be stricly compilable.

**Comment by matozoid** [comment]
Currently there is no check for this because the checks are all written for post-parse validation. This would be a post-ast-modification check. I'm hesitant to start writing those checks, because I don't think they'll get used much (unless we call these check from JP itself, before pretty printing and such. But that will cost performance for what are probably easily caught problems (resulting code does not compile...) ).

I've added a bunch of utility constructors because `LambdaExpr` was lacking them.

**Comment by l0rinc** [comment]
Thanks @matozoid, added comments to the PR

**Comment by matozoid** [comment]
Fixed those, and this will be released next Sunday.

**Comment by l0rinc** [comment]
Thanks @matozoid :)
