### ISSUE TITLE
Add `asString` to class `Node`

### ISSUE THREAD

**Issue by MysterAitch** [javaparser/javaparser#2032]
I'm currently investigating the best way to print the content of an arbitrary node, and there doesn't seem to be a reliable means of (programmatically) determining whether `toString` or `asString` should be called.

A single interface that can be checked against using `instanceof` or similar would make this significantly more straightforward, as would implementing `asString` within the class `Node` (or similar?). 

How might this be done best? 

1. A simple default implementation is to delegate to `toString` and have subclasses override it as required.
    - This would provide exactly what is currently available, but it doesn't meet the definition of `asString` (i.e. [the node minus comments and annotations](http://javaparser.org/making-strings-in-javaparser/)).   
1. A more robust implementation would be to clone the node, strip it of comments and annotations, and then call `toString` on the clone.
    - This doesn't "feel" right though and I can't quite put my finger on why. 
    - Perhaps it's due to not having a single location to strip out both annotations and comments? (`Node` has comments, but a range of other classes have annotations).

**Comment by matozoid** [comment]
Good thing you've made this an issue first. `asString` is the opposite of a print function: it gives you something you can use programmatically, as a key in a hashmap, or to compare to something in a configuration file. Now that I'm writing this I'm thinking the name might be all wrong.

The best way to print the content of an arbitrary node is to use the pretty printer, or the lexical preserving printer, or a custom pretty printer. This sounds like you want a copy of the pretty print visitor and delete the annotations and comment printing in there. Or yeah, your point two, it's fine what you're doing there :-)

**Comment by MysterAitch** [comment]
I'm not sure I quite follow what you're saying and I'm getting a little muddled. It's likely I'm not familiar enough to understand the use case for it (and my motivation for using `asString` is a rather vague feeling based on "`asString` is probably better" rather than anything more concrete) so shall ponder on a little longer :) 

Fair point re: use of printers - pretty sure you're spot on there and I'll dig a little further along those lines for my immediate needs. Somehow the connection with 'toString` using printers was completely missed!

**Comment by matozoid** [comment]
Do keep asking, it educational to see what happens when people use JP!

- Lexical Preserving Printer: tries to print with indentation and whitespace as much as the parsed original.
- Pretty Printer: happily forces its formatting rules on everything.
- asString: concrete case: Name.asString returns something like "a.b.c", which is usable in comparisons with other strings. toString might give "/* hi */a.b.c", which will fail the comparison, even when the intention was to match a.b.c with a.b.c. Now, for something like a for-statement it makes no sense to have an asString. Nobody here is nonchalantly comparing for statements, and I don't know what it would mean to compare two for statements.

Having toString() being a pretty printer has probably caused many subtle bugs in user code.

**Comment by matozoid** [comment]
@MysterAitch - this is over a year old already, time passes quickly! Do you want to continue this discussion?
