### ISSUE TITLE
JavaParser and Unicode Escaping

### ISSUE THREAD

**Issue by cdietrich** [javaparser/javaparser#209]
Hi

is it intended that parsing and serializing turns

```
public class Sample {

    public static final String SAMPLE="\u00DCbung";

}
```

into

```
public class Sample {

    public static final String SAMPLE = "Übung";
}
```

**Comment by ftomassetti** [comment]
This one is interesting. Right now the DumpVisitor aims to produce a sort of canonical form of the source code, so I guess it could make sense to transform the first one in the later or viceversa.
However javac would read the code using the default encoding for the platform unless it is told to do otherwise:

```
Sets the source file encoding name, such as EUC-JP and UTF-8. If the -encoding option is not specified, then the platform default converter is used.
```

(See: http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html)

While the strings are internally always in UTF-8 format the source code itself can be in another format. So the safest thing would be to escape as many characters as possible.

However there are people who want just to use explicitly an umlaut or or accent or a cedilla because they are very common in their language and they know what they are doing. They either pass the -encoding option when compiling or have a default encoding which permits to use those characters.
In such case perhaps not escaping those characters would be the best option.

Perhaps we could by default keep the same format we parsed and have options in DumpVisitor to escape/unescape characters considering a specific encoding. Right now I think it is possible to specify the encoding while parsing but not while dumping.

**Comment by ftomassetti** [comment]
And thank you for reporting this one!

**Comment by ptitjes** [comment]
Note that the problem comes from javacc which tries to comply to the Java Language Specification (see javacc docs here: https://javacc.java.net/doc/javaccgrm.html#prod6). As `JAVA_UNICODE_ESCAPE` is set to true in the grammar, unicode `\u` escaping is done before lexical analysis as specified by the JLS (beginning of the spec 'Lexical structure' or something like this - can't reference it with my phone...). Thus, the tokens given to the parser itself do not contain any `\u` anymore.

Obviously, this creates problems when you not only want to consume but also recreate source code. I tried this summer to fix this by trying all the combinations of `JAVA_UNICODE_ESCAPE` and `UNICODE_INPUT` options, reifying regular expressions in the lexical definitions in the grammar and make the escaping in code... without success. Also this makes the grammar horrible has you have to use complex regexp for simple things such as keywords.

The only solution I see for now is get rid of javacc. This is what I personally plan to do at a point. However, I'm all ears for any other fix idea.

**Comment by matozoid** [comment]
I'll create a new issue to replace JavaCC, since this one seems to "work as designed."
