### ISSUE TITLE
BinaryExpr, AssignExpr & UnaryExpr child nodes

### ISSUE THREAD

**Issue by rajatnarang94** [javaparser/javaparser#2105]
When I try to get children of say a BinaryExpr like "1&&2", I only get [1, 2]. I understand that I can use getOperator to get 'AND' but I'm trying to parse the whole tree and get children of each node. To incorporate the fact that 'AND' is not a child, as per javaparser, I might need to hard-code some conditions, because essentially I'm using recursion to parse the tree. I found same thing for AssignExpr & UnaryExpr too, so was wondering if there's a general way to deal with this? I basically need child nodes of "1&&2" to be returned as [1, 2, AND]. Python ast library does treat the "and" as a child of the expression "1 and 2" so was wondering if I can do the same thing with javaparser. Also, I'm actually okay if these three are the only "discrepancies", but if there are more then kindly tell me a way to handle those.
I'm not sure if I explained my concern properly, do let me know if any clarifications are needed. Looking forward to your response, thanks!

**Comment by matozoid** [comment]
Hi! I'll assume you are talking about `Node.getChildren()` here. Yes, I can understand the need for this - for example: we just changed modifiers like "public" from enums to real `Node`s so that we can keep more information on them, and make them visitable.

I guess that right now, using `JavaParserMetaModel` is the easiest approach. It is a tree of information about all of the nodes, including which fields they have and what type they are. You should be able to figure out which fields are not `Node`s so that you can evaluate if you want some special case code to include these in your results.

I can't promise any changes soon though, they are breaking, demand seems to be low, and in the end it's a little arbitrary how "abstract" the AST is anyway.

**Comment by rajatnarang94** [comment]
Okay, thanks, I was currently trying to use Java's Reflection API to handle this but it was definitely not easy. I'll look into JavaParserMetaModel. Thanks again!

**Comment by matozoid** [comment]
Cool, the meta model is more or less nice reflection for the nodes, so sounds good :-)

**Comment by rajatnarang94** [comment]
Okay, thanks! I've got an exam tomorrow so unfortunately I can't spend much time on exploring this option right now, but I'll get back to you if in case I face any trouble! Thanks!
