### ISSUE TITLE
Set Annotation on specific line

### ISSUE THREAD

**Issue by askary94** [javaparser/javaparser#2188]
Hello
How can I set an Annotation on a particular line?

```
 1. public class exm 
 2. {
 3.	classC c=new classC();
 4.	int a=0;
 5.	protected void methodA()
 6.	{
 7.		c.foo();
 8.	}
 9. }
```
For example, I want to set up a Annotation after line 4.

**Comment by matozoid** [comment]
Hi! You can add an annotation to a node that you want it on. Then, depending on your setup:

- the pretty printer will print it where it thinks it is "pretty".
- the lexical preserving printer will position it according to its formatting rules.

Or maybe something else, because you did not say how you are outputting the code.

**Comment by askary94** [comment]
Thank you very much for your answer.
 No matter how to print.
my problem was that:
 I was not concerned that annotation could not be added to the `methodExper`, but it should be added to the `methodDeclaration`.
From your comments, I noticed my mistake.
Thankyou.....

**Comment by matozoid** [comment]
Ah, I see! Good to see it works now.
