### ISSUE TITLE
Setting modifiers of a non-primitive FieldDeclaration throws UnsupportedOperationException

### ISSUE THREAD

**Issue by MarvinWyrich** [javaparser/javaparser#2189]
When setting the modifiers of a `FieldDeclaration` and the field is of a non-primitive type, an `UnsupportedOperationException` is thrown.

```
FieldDeclaration field = ...;   // existing field in a compilation unit
field.setModifiers(new NodeList<Modifier>());
```

- works if field is of type int, e.g. `public final static int a = 1;`
- does not work if field is of type String, e.g. `public final static String b = "2";`

In the latter case, the following error message is thrown:

```
java.lang.UnsupportedOperationException: kept child(ClassOrInterfaceType) vs "String"   <89>   (line 6,col 22)-(line 6,col 27)
	at com.github.javaparser.printer.lexicalpreservation.Difference.applyKeptDiffElement(Difference.java:449)
	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:141)
	at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator.calculatePropertyChange(LexicalDifferenceCalculator.java:122)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concretePropertyChange(LexicalPreservingPrinter.java:170)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.propertyChange(PropagatingAstObserver.java:62)
	at com.github.javaparser.ast.Node.lambda$notifyPropertyChange$3(Node.java:554)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at com.github.javaparser.ast.Node.notifyPropertyChange(Node.java:554)
	at com.github.javaparser.ast.body.FieldDeclaration.setModifiers(FieldDeclaration.java:143)
	...
```

`Difference.applyKeptDiffElement(...)`:

```
...
                if (kept.isPrimitiveType()) {
                    originalIndex++;
                    diffIndex++;
                } else {
                    throw new UnsupportedOperationException("kept " + kept.getElement() + " vs " + originalElement);
                }
...
```

Can someone who is more familiar with this code location explain whether and why this differentiation by type is necessary here? Thanks for your support.

**Comment by MarvinWyrich** [comment]
Additional info: setting modifiers in the same way as described above works for a `MethodDeclaration`, for both primitive and non-primitive return types (e.g. `public final static String a() { return "3";  }`).

**Comment by jlerbsc** [comment]
@Marvin, I don't know the response to your question but the difference class is hard to understand and difficult to change because of neested if statement. The goal is to generate the node data value (NodeText) from two lists : 
- diffElements (a list of DifferenceElement) which define the meaning of the operation (add, remove, keep...). This list is managed by the diffIndex.
- orginalElements (a list of TextElement) which is the sequence of the tokens from the original expression. This list is managed by the originalIndex.

Unfortunately, the lists do not contain the same element type. For example, the declaration List<String> a is represented by 2 nodes in diffElements list and 6 tokens in orginalElements.
So Difference class needs to sync the 2 lists to rebuild the NodeText and preserve the lexcial representation of the declaration.
For example, when we keep the List<String> part of the declaration, we have to increment the diffIndex to manage, in the future, the next element, and synchronize the originalIndex to the 'next' token (so we have to pass this sequence of tokens [List][<][String][>]) before to compute the next part of the declaration. I hope this helps you understand this algorithm. Not sure! ;-)

**Comment by MarvinWyrich** [comment]
@jlerbsc Thank you for taking the time to explain the algorithm to me. Will surely be relevant and helpful again in the future if this code location causes problems again :D
And I am glad that the problem could be solved by your implementation. Thanks for that!
