### ISSUE TITLE
Get fully qualified symbol name for classes/methods/fields

### ISSUE THREAD

**Issue by olivergondza** [javaparser/javaparser#222]
I am looking for a way to generate fully-qualified symbol name. Perhaps there is a way to do so and I just missed that. Something like:

``` java
java.io.File
java.io.File#separatorChar
java.io.File#getName()
java.io.File#renameTo(java.io.File)
java.io.File.TempDirectory#tmpdir
```

**Comment by ftomassetti** [comment]
If you mean that given a method or a field definition you want to find the fully qualified name then yes, you can do that using JavaParser (read below). If you instead want to find the fully qualified name for a method call or a field reference than no, you cannot do that because you would need a symbol resolver to do so.

To find the fully qualified name from a definition I do not think there is a method to do so but you basically need:
- to find the class containing the field or the method 
- to find if a class is contained in another class
- to find the package definition of the file hosting the class

The first two points are solved by recursively invoking [getParentNode](http://static.javadoc.io/com.github.javaparser/javaparser-core/2.3.0/com/github/javaparser/ast/Node.html#getParentNode--) until you find the class containing the element.

For the third point you instead call getParentNode until you find the CompilationUnit (which represents the whole file). Once you get the CompilationUnit you can call [getPackage](http://static.javadoc.io/com.github.javaparser/javaparser-core/2.3.0/com/github/javaparser/ast/CompilationUnit.html#getPackage--) to get the package declaration from which you can find the package name.

**Comment by olivergondza** [comment]
I was hoping there ware a convenience method for that already. Let me see if I can come up with something reusable.

**Comment by olivergondza** [comment]
After some digging in this I found out it is not really possible. Consider `void foo(List a){}` method. It is not possible to resolve `List` to fully qualified name without inspecting imports. Not even that in case of star imports are used.

@ftomassetti, thanks for the hint. Feel free to close this if you think it is worth to implement something similar.

**Comment by ftomassetti** [comment]
For such things you need to use a symbol solver for Java. I wrote one on top of Java parser (https://github.com/ftomassetti/java-symbol-solver) but it still need some polishing

**Comment by SmiddyPence** [comment]
This looks agreed too close
