### ISSUE TITLE
The save() Method of CompilationUnit should not hardcode its encoding

### ISSUE THREAD

**Issue by Funkschy** [javaparser/javaparser#2237]
Hey guys, I noticed something while working on a codebase which has to be encoded using ISO-8859-1. The save Function of CompilationUnit currently has no way of specifying the Charset.
```java
public void save(Function<CompilationUnit, String> makeOutput) {
    try {
        Files.createDirectories(path.getParent());
        final String code = makeOutput.apply(getCompilationUnit());
        Files.write(path, code.getBytes(UTF8));
    } catch (IOException e) {
        throw new RuntimeException(e);
    }
 }
```
Shouldn't it be possible to pass an optional Charset to this Method? Like this:

```java
public void save(Function<CompilationUnit, String> makeOutput, charset: Charset) { 
    ...
    Files.write(path, code.getBytes(charset));
    ...
}
```
Or is there any reason for this behaviour? If you want me to, I could create a PR for this

**Comment by matozoid** [comment]
Hi! Thanks for reporting this.
Yes, there should be an option to specify it.
I'm thinking if it would be nice if Compilation.Storage would also store the charset that was used when loading the source file, because then we could do:

- if explicitly specified charset: use that charset.
- use the one that was used for loading.

No more default UTF-8!

**Comment by matozoid** [comment]
Please do make a PR, by the way!
