### ISSUE TITLE
No method visit(AnnotationExpr, A arg) 

### ISSUE THREAD

**Issue by csmym** [javaparser/javaparser#2275]
Hi,

Why there is no method visit(AnnotationExpr, A arg) in public class ModifierVisitor<A> ?

Thanks

**Comment by csmym** [comment]
Sorry, I found myself
There is a NormalAnnotationExpr visit(NormalAnnotationExpr fd, Void arg)

**Comment by matozoid** [comment]
Hi! A little addition: there are several node types for annotations.

`MarkerAnnotationExpr`, `NormalAnnotationExpr`, `SingleMemberAnnotationExpr`

The Javadoc can tell you what exactly they are for.

**Comment by csmym** [comment]
> Hi! A little addition: there are several node types for annotations.
> 
> `MarkerAnnotationExpr`, `NormalAnnotationExpr`, `SingleMemberAnnotationExpr`
> 
> The Javadoc can tell you what exactly they are for.

Hello

Yes, thanks a lot. 

I am not sure if my question does make sense, but here it is. Why there is not a visit(AnnotationExpr, A arg) method in order to handle at the same time MarkerAnnotationExpr, NormalAnnotationExpr, SingleMemberAnnotationExpr ?

**Comment by edefazio** [comment]
(not to interject, but)
I think because if you have an interface with BOTH
`visit( AnnotationExpr ae)`
and
`visit(MarkerAnnotationExpr ae)` ...

then it would be ambiguous what happens when I encounter a single MarkerAnnotationExpr 
(do i call visit on BOTH?... in which case, you might "double visit")

...I think it makes sense as it is, if you want ALL annotations, you can always adapt the visitor in your own code (i.e. delegate all of the visits to your custom visit method:

```java 
visit(MarkerAnnotationExpr ae, Object arg){
    visitAnno( ae, arg);
}
visit(SingleMemberAnnotationExpr ae, Object arg){
    visitAnno( ae, arg);
}

visitAnno(AnnotationExpr ae, Object arg){
    //..custom code here
}
```

**Comment by matozoid** [comment]
Yes :-)

The rule is: all the concrete (non-abstract) classes inherited from `Node` have a visit method.

**Comment by matozoid** [comment]
(Related to #757)

**Comment by csmym** [comment]
Thank you very much for all this information. It was very useful to me.
Friendly.
