### ISSUE TITLE
CompilationUnit#addImport produces duplicate imports 

### ISSUE THREAD

**Issue by gitmotte** [javaparser/javaparser#2391]
<artifactId>javaparser-core</artifactId>
<groupId>com.github.javaparser</groupId>
<version>3.14.159265359</version>

```
public CompilationUnit addImport(ImportDeclaration importDeclaration) {
        if (getImports().stream().noneMatch(im -> im.toString().equals(importDeclaration.toString()))) {
            getImports().add(importDeclaration);
        }
        return this;
    }
```
should be
```
public CompilationUnit addImport(ImportDeclaration importDeclaration) {
        if (getImports().stream().noneMatch(im -> im.getNameAsString().equals(importDeclaration.getNameAsString()))) {
            getImports().add(importDeclaration);
        }
        return this;
    }
```
otherwise comments and other nodes affect the result. 
i.e.
```
package a.b.c;

/*
a package comment
*/

import x.y.z.Type;
import x.y.z.Type;
```

Maybe we should improve this method to ignore implicit imported packages like "java.lang" ?
```
public CompilationUnit addImport(ImportDeclaration importDeclaration) {
        if (!importDeclaration.getNameAsString().startsWith("java.lang") && getImports().stream().noneMatch(im -> im.getNameAsString().equals(importDeclaration.getNameAsString()))) {
            getImports().add(importDeclaration);
        }
        return this;
    }
```

**Comment by matozoid** [comment]
Sounds good. There are various addImport methods though, and they all seem to work differently. Also the Javadoc is way outdated.

Would you like to do a little clean up and submit a PR?

**Comment by edefazio** [comment]
While we are at it...
can we also check if the package is already wildcard imported?

i.e.
```java
CompilationUnit cu = Ast.of("public class A{}");
cu.addImport(new ImportDeclaration("java.util", false, true));
cu.addImport(new ImportDeclaration("java.util.Map", false, false));
System.out.println( cu );

// prints:
import java.util.*;
import java.util.Map;

public class A {
}

//maybe it should be:
import java.util.*;

public class A {
}
```

...just a thought.

**Comment by gitmotte** [comment]
Just saying this does not fix the bug, if an import has been parsed with a comment, and the second was added at runtime, because they are not equal any more. 
```
package a.b.c;

/*
a package comment
*/
import x.y.z.Type;
import x.y.z.Type;
```
Well, i'm reorganizing imports before writing the java - file now in my project code, because i have only one comment between package- and import-declarations (the license-header) . Never heard about anyone commenting imports ...

**Comment by matozoid** [comment]
They are not equal anymore? Not sure I understand?

**Comment by gitmotte** [comment]
The importdeclarations are not equal, because the first import has a comment, the second not, nevertheless the names of the imports are equal.

**Comment by edefazio** [comment]
Ohh... one issue with this logic...
`!importDeclaration.getNameAsString().startsWith("java.lang")`

I had logic similar to this, but there are subpackages under "java.lang" that are NOT auto imported
i.e.
"java.lang.annotation.Documented.class"

alternatively maybe:
`!importDeclaration.getNameAsString().equals("java.lang")`

**Comment by gitmotte** [comment]
@edefazio Please have a look at the fix, not the first proposal. https://github.com/javaparser/javaparser/issues/2392

**Comment by edefazio** [comment]
sorry I was half paying attention and watching football... my mistake... thanks for the fix

**Comment by edefazio** [comment]
I apologize... I didn't do my due diligence here and I'm sorry, but the changes that are made in this are causing some tests I did (outside of JavaParser) to fail... the problem is that the change made in `CompilationUnit.addImport(...)` will fail if we add an import with any name containing a '$' in it:

(as explained on the Gitter)
It revolves around importing Classes and Interfaces which begin with $ (or have $ in their names)... I actually use quite a few classes that START with $ so that I can keep that class names short ($ in my tool "means" "a pattern"... so I have $class which "means" : "a pattern for a class"...And I didnt want to spell out "APatternForAClass" each time because its just alot of work....

Anyways, 3.15.0 made a change in `CompilationUnit.addImport( String s )`
`i.append(name.replace("$", "."));`

I understand why we might want to do this (when we use the Name, not canonical name for a Class and we get back it's something like this:
`System.out.println( Character.UnicodeBlock.class.getName());`
will return
`java.lang.Character$UnicodeBlock`

...and we want to change the $ to a '.'...

but seems to me we should always use the `getCanonicalName()` method instead so we avoid using the $ notation in `Class.getName`:
`System.out.println( Character.UnicodeBlock.class.getCanonicalName());`
//returns
`java.lang.Character.UnicodeBlock`

...and therefore we should treat $ as that character and NOT convert it to a dot... you just have to be aware and use the Canonical class name for imports and not the `getName()` method

the downside of "auto converting" $ to '.' is that, if any classes have a $ in their name, we cant import it... and while this wont occur often it happens "enough" (its usually not good practice certainly to Start with the $, but it is not completely uncommon to use the $ within class names...

I havent looked at the entirety of the change and the impact analysis to change it, but I figured I'd write a description here (Im sorta busy, and maybe the original opener and fixer can look into it?)
Thanks
Eric

**Comment by edefazio** [comment]
Here's two test cases to illustrate the failures:
```java
    public class $tartsWith${ }

    public void test$ImportStarts(){
        CompilationUnit cu = StaticJavaParser.parse("class C{}");
        cu.addImport($tartsWith$.class); //fails with exception
        //com.github.javaparser.ParseProblemException: Encountered unexpected token: "." "."
        //    at line 1, column 31.
    }

    public class F$F{ }

    public void test$Import(){
        CompilationUnit cu = StaticJavaParser.parse("class C{}");
        cu.addImport(F$F.class);
        //doesnt fail, but imports class "F.F"
        assertTrue(
                cu.getImports().stream().filter( i -> i.getNameAsString().equals(F$F.class.getCanonicalName())).findFirst().isPresent() );
    }
```

**Comment by gitmotte** [comment]
@edefazio thanks for the hint with ```Class#getCanonicalName()```

In my last PR i moved the replacement ```name.replace("$", ".")``` from ```addImport (Class)``` to ```addImport (String)``` not considering that this is not a universal rule.
