### ISSUE TITLE
Solving generic type of method paramters or return type fails

### ISSUE THREAD

**Issue by andrewhabib** [javaparser/javaparser#2397]
Hi, 

For ```MethodDeclaration```s in each ```ClassOrInterfaceDeclaration```, I am trying to obtain resolved return type as well as resolved type of each method parameter. 
I get ```java.lang.UnsupportedOperationException: Unable to get the resolved type of class ResolvedReferenceType from ...``` when calling ```solve()``` on the corresponding return or method parameter type if the type is parametrized. 

The following are examples of code I am trying parse and resolve.

Ex1:
```
static final class ConstantFuture<T> implements Future<T> {
        private final T value;
      
        @Override
        public T get() {
            return value;
        }
}
```

Ex2:
```
    public static <T> T[] toArray(final T... items) {
        return items;
    }
```

Any idea why is this happening?

**Comment by MysterAitch** [comment]
Just documenting some thoughts so far: 

- At parse time `T` is treated as a `ClassOrInterfaceType`, thus when it is resolved it resolves to `ResolvedReferenceType` (per the snippet quoted below), but when we attempt to resolve a type variable it tries to return a `ResolvedTypeVariable`

```java
// ClassOrInterfaceType.java
@Override
public ResolvedReferenceType resolve() {
    return getSymbolResolver().toResolvedType(this, ResolvedReferenceType.class);
}
```

- Note that while `ResolvedReferenceType` and `ResolvedTypeVariable` both implement `ResolvedType`, they are not interchangeable
- Because the two types are not interchangeable, the `isInstance()` check returns false (line 241) thus is treated as unresolvable
https://github.com/javaparser/javaparser/blob/e8e890a36cec779ada65889bf6d2d02c26708747/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/JavaSymbolSolver.java#L237-L247



```java
//// Fails: java.lang.UnsupportedOperationException: Unable to get the resolved type of T (resolves as ResolvedTypeVariable, expecting ResolvedReferenceType)
Type type = this.methodDeclaration.getType();
ResolvedType resolvedType = type.resolve();
System.out.println("resolvedType = " + resolvedType);
System.out.println("resolvedType.describe() = " + resolvedType.describe());
```


- As a workaround, if we resolve the method and THEN call `.getReturnType()`, this correctly returns a `ResolvedTypeVariable`
```java 
// JavaParserMethodDeclaration.java
@Override
public ResolvedType getReturnType() {
    return JavaParserFacade.get(typeSolver).convert(wrappedNode.getType(), getContext());
}
```
```java 
//// Works fine
ResolvedMethodDeclaration resolvedMethodDeclaration = methodDeclaration.resolve();
ResolvedType returnType = resolvedMethodDeclaration.getReturnType();
System.out.println("returnType = " + returnType); // returnType = TypeVariable {JPTypeParameter(T, bounds=[])}
System.out.println("returnType.describe() = " + returnType.describe()); // returnType.describe() = T
 ```

**Comment by MysterAitch** [comment]
Here is the relevant parts of the grammar that deal with the return types of method declarations.

--- 

It seems that the grammar file doesn't necessarily match the language spec (i.e. `ReferenceType` includes a mention of a primitive type but no mention of a type parameter?)

I'm not yet sure what this means or if it's relevant/important, but again I'm leaving this to document current thoughts/progress. 

Maybe someone with more experience of javacc / grammar files might be able to comment?

--- 

---
### MethodDeclaration -- Mostly matches?

- This part describes the grammar of defining a method.
  - JLS 8.4 describes a method declaration as: 
  -  ```
     MethodDeclaration:
       {MethodModifier} MethodHeader MethodBody
     MethodHeader:
       Result MethodDeclarator [Throws]
       TypeParameters {Annotation} Result MethodDeclarator [Throws]
     ```
  - https://github.com/javaparser/javaparser/blob/e8e890a36cec779ada65889bf6d2d02c26708747/javaparser-core/src/main/javacc/java.jj#L999-L1026

--- 
### ResultType - Matches, but reversed?

- This part describes the grammar of a result type (i.e. the result type is either `void`, or `Type`)
  - JLS section 8.4.5:
  - ```
     Result:
       UnannType
       void
    ```
  - https://github.com/javaparser/javaparser/blob/e8e890a36cec779ada65889bf6d2d02c26708747/javaparser-core/src/main/javacc/java.jj#L1379-L1390

---
### Type -- Matches, but reversed?

- This part describes a `Type` (i.e. is a `ReferenceType` or `PrimitiveType`)
  - JLS section 8.3: 
  - ```
    UnannType:
      UnannPrimitiveType
      UnannReferenceType
    ```
  - https://github.com/javaparser/javaparser/blob/e8e890a36cec779ada65889bf6d2d02c26708747/javaparser-core/src/main/javacc/java.jj#L1218-L1229

---
---
--- 
### ReferenceType -- MISMATCH? Has `PrimitiveType` instead of `TypeVariable`?

- This part describes a `ReferenceType` (i.e. is a `PrimitiveType` or `ClassOrInterfaceType` -- or the array equivalents thereof)
  - JLS section 8.3 --- NOTE: The JLS refers to `UnanTypeVariable`, whereas `java.jj` refers to `PrimitiveType` ????
  - ```
    UnannReferenceType:
      UnannClassOrInterfaceType
      UnannTypeVariable
      UnannArrayType
    ```
  - https://github.com/javaparser/javaparser/blob/e8e890a36cec779ada65889bf6d2d02c26708747/javaparser-core/src/main/javacc/java.jj#L1231-L1244

**Comment by himamis** [comment]
I have the same problem when parsing the field `private T listener`:
* `T` is parsed as `ClassOrInterfaceType`, and cannot be resolved.
* The parent node is a FieldDeclarator, can be resolved, and resolves `T` as `TypeParameter`

**Comment by matozoid** [comment]
@MysterAitch  @himamis - there are now about five different topics in this issue. To improve the chances of these getting attention, open a new issue for each.

**Comment by 4everTheOne** [comment]
Hello guys,

I think i found the solution for the issue. The issue was related with the ClassOrInterfaceDeclaration, since it required the return of a ResolvedReferenceType. When we are working with TypeParameters, we needed to return a ResolvedTypeVariable that doesn't extend the ResolvedReferenceType. The only interface in common between them is the ResolvedType. 

So to make it work, had to demote the ResolvedReferenceType into ResolvedType.
It's importante to note, that this change implies that all of the old code that use the method resolve, need to be updated, since it now returns a new type. An example of the change can be see below:

**Oldcode:**
```java
ResolvedReferenceType resolvedReferenceType = classOrInterfaceType.resolve();
```
**New code:**
```java
ResolvedType resolved = classOrInterfaceType.resolve();
ResolvedReferenceType resolvedReferenceType = resolved.asReferenceType();
```

**Comment by oneturkmen** [comment]
Any updates on this issue? I seem to have the same problem. In my case, I am getting `Future<X>` instead of `java.util.concurrent.Future<X>` where `X` is not resolvable.

**Comment by 4everTheOne** [comment]
Hi @oneturkmen,

At the moment doesn't seem to exist an official fix for it yet, but there is a suggestion with a fix at PR #3034. 
I have been using it in my own experiments and it seems to work fine. 

Could you give it a try, and see if it also solves yours? 

Best regards

**Comment by jlerbsc** [comment]
Hi @MysterAitch what do you think of @4everTheOne 's solution. Note that there is a change of public API.

**Comment by MysterAitch** [comment]
> Hi @MysterAitch what do you think of @4everTheOne 's solution. Note that there is a change of public API.

It seems reasonable, but I haven't yet been able to come to a firm view one way or the other.
