### ISSUE TITLE
Generate COde based on Annotations

### ISSUE THREAD

**Issue by tijanssen** [javaparser/javaparser#2464]
Sorry for eht title but i could not come up with a better one at the moment.

I want to something similar like lombok does. For example the @Getter Annotation generates a getter method if it does not exist.
My first idea was to use ModifierVisitor.visit(FieldDeclaration ...). But the returned FieldDeclartion is the one that should be changed. But I don't want just change the Field (remove the annotation) but also add method based on want kind of annotation is on the Field. but if I add a method then would I not change de ClassAndInterfaceDeclaration. 
So do I need to use the visit method that takes a ClassandInterfaceDeclaration and look in that method for all fields and look if the field has an nnotation? 

Thansks

**Comment by jlerbsc** [comment]
Once you get a fieldDeclaration you can find ClassAndInterfaceDeclaration or all MethodDeclaration from it or add a new MethodDeclaration if you want. What is your question?

**Comment by tijanssen** [comment]
Sorry my misunderstanding was that the return type should be the same as the first parameter type. THe examples I have seen did this always.
If this is correct then this issue can be closed.

**Comment by edefazio** [comment]
I actually implemented this with a tool I wrote on top of JavaParser...
FWIW understand that Lombok is a little crazy how it plugs into the Compiler infrastructure / Annotation Processing
(Here are the creators of Lombok talking about how complex it is to integrate Lombok
https://www.youtube.com/watch?v=MmLnJVlZAvk)  

What I did (instead) is: 
start a Java program
pass in a Runtime Class
find and read in the source code for a Runtime Class at runtime, (NOT compile time) 
parse the String from a file to an AST using JavaParser
the annotations i.e "@get" are RUNTIME ANNOTATIONS so we can use reflection to get the details

I'm just saying that this issue is a little more involved and I wasted lots of time trying to "emulate" what Lombok is doing... 

Here's the core of what I an doing in a macro class 
https://github.com/org-jdraft/jdraft/blob/cf5bf7168c49ef0206d7b927ad4404299b1be818/src/main/java/org/jdraft/macro/macro.java#L98-L194

Its actually looking over all fields, methods, parameters, constructors, looking for Runtime Annotations, and finding out if there is a (internal) implementation (on the Runtime Annotation)

Here is a @_get annotation (creates getter methods) 
https://github.com/org-jdraft/jdraft/blob/master/src/main/java/org/jdraft/macro/_get.java

which INCLUDES as a static nested class (Act) how to process the macro:
https://github.com/org-jdraft/jdraft/blob/cf5bf7168c49ef0206d7b927ad4404299b1be818/src/main/java/org/jdraft/macro/_get.java#L19

Perhaps you can look at this for some inspiration (it doesn't HAVE to work this way, but I found it to be MUCH more straight forward than with or modify Lombok, YMMV)

**Comment by tijanssen** [comment]
I didn't want to do anything with lombok. But I wanted to make a maven plugin that does something similar like delombok. This is more of an experiment nad practice project. We do have very good buildsystem in the java world like maven and gradle. We can add plugins that the community has written and thereby enrichen the bild process. I don't see any reason to use the ehe in my eyes complicated AnnotationProcessing through the javac compiler, when we can much easier implement buildsystem plugins which achieve the same effect.

**Comment by edefazio** [comment]
I agree,
actually that's a big part of what my project (building on JavaParser) is "about"... 
bringing Java metaprogramming to the mainstream... 
(i.e. write simple Java programs to generate or modify Java code)

anyways good luck... here's a link to my main project... 
https://github.com/org-jdraft/jdraft
maybe it'll give you ideas or an alternative way of doing things... (Still working on the documentation, but you get what you pay for)

**Comment by matozoid** [comment]
Side note: most of the internal code generators for JavaParser do inline code modifications: they modify the source directory, adding and modifying methods and classes. A rather unconventional approach, but it works well. 

Edit: they do this using JavaParser. The compiled code is modifying its source files :-D

**Comment by tijanssen** [comment]
Thansk for the informations. I will look at the provided links.

**Comment by MysterAitch** [comment]
Hi @tijanssen, it looks like the question has been answered and it has been over a month since the last reply, so I'm going to close this issue to help keep the issue tracker tidy.

Please do reply/follow up if there is anything outstanding!

Stay safe and take care :)
