### ISSUE TITLE
Resolving TypeParameter

### ISSUE THREAD

**Issue by himamis** [javaparser/javaparser#2481]
Resolving a `TypeParameter` from `ClassOrInterfaceType` fails with `java.lang.UnsupportedOperationException`.

**How to reproduce**
```
TypeSolver solver = new ReflectionTypeSolver();
ParserConfiguration parserConfiguration = new ParserConfiguration();
parserConfiguration.setSymbolResolver(new JavaSymbolSolver(solver));
JavaParser parser = new JavaParser(parserConfiguration);
ParseResult<CompilationUnit> cu = parser.parse("class A<T> { T t; }");
cu.ifSuccessful( c -> {
    c.accept(new VoidVisitorAdapter<Void>() {
        @Override
	public void visit(ClassOrInterfaceType n, Void arg) {
	    super.visit(n, arg);
	    n.resolve();
	}
}, null);
```
**Expected**
`n.resolve()` returns with `ResolvedTypeVariable`

**Result**
`n.resolve()` throws an exception.

**Comment by himamis** [comment]
Related to  #2397.

**Comment by voxelbustersold** [comment]
Any timeline for this fix?

**Comment by MysterAitch** [comment]
> Any timeline for this fix?

Afraid not! Personally I took a look at this issue this morning but didn't get anywhere substantial, though I can't speak on behalf of others who might take a look.

@himamis has provided a really good bug report and I'm grateful for the clear and concise reproduction information, so we can't really ask for much more! 


If you have additional test cases that you might be able to share, or perhaps some thoughts on what the root cause might be, please do add comments here as it might help nudge in the right direction! :smile:

**Comment by jlerbsc** [comment]
I am closing this issue as it seems to have been resolved in the current version.
