### ISSUE TITLE
Comment is not setted to the correct node 

### ISSUE THREAD

**Issue by jlerbsc** [javaparser/javaparser#2482]
It seems that in the statement bellow the comment is not setted to the correct node

    // a comment before parent
    if (file != null) {}

is parsed to 

    if (// a comment before parent
      file != null) {
    }

It seems that CommentsInserter.insertComments(..) postprocessor run on child nodes but in this case it should take into account the node itself.

What do you think about this?

**Comment by matozoid** [comment]
Is it *set* or *printed* the wrong way?

**Comment by jlerbsc** [comment]
Setted. It is considered as an orphan comment but at this stage it's not affected to a node.

**Comment by edefazio** [comment]
FWIW I did a little digging to see how this manifested itself in different scenarios 
(i.e. with `LambdaExpr`s and `BlockStmt`s)

```java
LambdaExpr le = (LambdaExpr)StaticJavaParser.parseExpression(
    "//a comment before parent"+System.lineSeparator()+
    "()->{return 1;}");
System.out.println(le);
```
expected:
```java
//a comment before parent
()->{return 1;}
```

actual:
```java
() -> // a comment before parent
{
    return 1;
}
```
BlockStmts
```java
Statement st = StaticJavaParser.parseBlock( 
    "// a comment before parent"+System.lineSeparator()+
    "{ if (file != null) {} }");
    System.out.println(st);
```

expected:
```java
// a comment before parent
{ 
    if (file != null) {} 
}
```

actual:
```java
{ 
    // a comment before parent
    if (file != null) {} 
}
```
...So it seems the problem is not isolated to parsing Statements... but rather parsing things in the body where the FIRST thing being parsed is a comment, and its attribution is not to the top level entity.

**Comment by edefazio** [comment]
FWIW, in the above, I would have expected each entity 
(the `LambdaExpr`, and the `BlockStmt`) 
1) to have a comment attached to the Node 
2) have an empty OrphanedComments List
3) have a single comment in getContainedComments()
i.e.

```java
LambdaExpr le = (LambdaExpr)StaticJavaParser.parseExpression(
    "//a comment before parent"+System.lineSeparator()+
    "()->{return 1;}");
assertTrue(le.getComment().isPresent());//FAILS
assertTrue(le.getOrphanComments().isEmpty()); //passes
assertEquals(1, le.getAllContainedComments().size());//passes
```

(I'm just pointing this out because it's not a "printing" issue, but rather a Comment Attribution issue)   
Also, it's sorta in this "strange" limbo situation where the comment: 
IS NOT in the `OrphanedComments` List
IS NOT on the Node
...but it IS retrievable in `getContainedComments()`

**Comment by matozoid** [comment]
Is this also present in 3.15.6? Range.overlapsWith changed behaviour there, and is typically something used for comments.

**Comment by edefazio** [comment]
looks broken in  3.15.9 (latest)
also tried: 
3.15.8 still broken
3.15.6 still broken
3.15.3 still broken
