### ISSUE TITLE
SymbolResolver on MethodCallExpr fails if method parameter is of kind Class<? extends y>

### ISSUE THREAD

**Issue by jofroe** [javaparser/javaparser#2484]
I have a simple class where I want to resolve MethodCallExpr.

```java
public class MyClass {
    private Ibaz m_something;

    public interface Ibaz {
    }
    
    public void foo(Class<? extends Ibaz> clazz) {
    }
    
    protected void bar() {
        foo(null); // this works
        foo(m_something.getClass()); // this doesn't work
    }
}
```

In `MethodResolutionLogic.findMostApplicable(..)` the methods with matching name seems to be correct, nevertheless it fails to find a matching method:

`List<ResolvedMethodDeclaration> methodsWithMatchingName =
[JavaParserMethodDeclaration{wrappedNode=public void foo(Class<? extends Ibaz> clazz) {
}, typeSolver=com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver@74d1dc36}]`

In my above example, the first call on `foo(null)` with a null parameter works, whereas the second call, passing the class of `m_something` does not.

**Comment by MysterAitch** [comment]
Additional test example showing that it seems to work without throwing an exception when the value is passed indirectly using a variable, but not when it is passed directly.

```java
public class MyClass {
    private Ibaz m_something;
    
    public class Ibaz {
    }
    
    public void foo(Class<? extends Ibaz> clazz) {
    }
    
    protected void bar() {
        foo(null); // this works
        foo(Ibaz.class); // this works
        
        Class c1 = m_something.getClass();
        foo(c1); // this works
        
        Class<Ibaz> c2 = m_something.getClass();
        foo(c2); // this works
        
        Class<> c3 = m_something.getClass();
        foo(c3); // this works
        
        Class<Object> c4 = m_something.getClass();
        foo(c4); // this doesn't work
        
        foo(m_something.getClass()); // this doesn't work
    }
}
```


```
Unsolved symbol : We are unable to find the method declaration corresponding to foo(m_something.getClass())
UnsolvedSymbolException{context='null', name='We are unable to find the method declaration corresponding to foo(m_something.getClass())', cause='null'}
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:167)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
	at com.github.javaparser.symbolsolver.Issue2484Test.lambda$test$0(Issue2484Test.java:100)
	at com.github.javaparser.ParseResult.ifSuccessful(ParseResult.java:65)
	at com.github.javaparser.symbolsolver.Issue2484Test.test(Issue2484Test.java:91)

.....

```

**Comment by MysterAitch** [comment]
I'm somewhat stumped here -- noting that the method signature is `public final native Class<?> getClass();`, as far as I can see `m_something.getClass()` seems to be resolving "correctly" as:

> ReferenceType{java.lang.Class, typeParametersMap=TypeParametersMap{nameToValue={java.lang.Class.T=WildcardUsage{type=EXTENDS, boundedType=ReferenceType{java.lang.Object, typeParametersMap=TypeParametersMap{nameToValue={}}}}}}}


Where things get a little funky is, per the JavaDoc, `Class <?>` is not the "true" return type of `getClass()`: 
> The actual result type is Class<? extends |X|> where |X| is the erasure of the static type of the expression on which getClass is called. For example, no cast is required in this code fragment:
> `Number n = 0;  Class<? extends Number> c = n.getClass();`

As shown in the comment above, JSS seems to handle this fine when assigning to a variable but insists on returning `Class<? extends Object>` when the method call is used directly as a parameter. The issue here arises due to the incompatibility between `Class<? extends Object>` not being "assignable to" `Class<? extends Ibaz>`.

It seems that first assigning to a variable doesn't fall foul of this.

> `Class c1 = m_something.getClass();'
> '// ReferenceType{java.lang.Class, typeParametersMap=TypeParametersMap{nameToValue={}}}`

and 

> `Class<Ibaz> c2 = m_something.getClass();`
> `// ReferenceType{java.lang.Class, typeParametersMap=TypeParametersMap{nameToValue={java.lang.Class.T=ReferenceType{MyClass.Ibaz, typeParametersMap=TypeParametersMap{nameToValue={}}}}}}`



It might be that I'm missing something obvious, but for now I'm going to take a breather and step away. 

---

PS: For anybody following this (and possibly myself because future-me is likely to forget this!), `JavaParserTypeDeclarationAdapter#solveMethod` appears to be where the "candidate methods" are picked out -- it is here that the `argumentsTypes` variable is first populated (and then passed down through the various other methods).

https://github.com/javaparser/javaparser/blob/7d77dc58d62e5b7f4a9f76e9b0e810f557391c04/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/JavaParserTypeDeclarationAdapter.java#L133-L176

**Comment by jlerbsc** [comment]
> I'm somewhat stumped here -- noting that the method signature is `public final native Class<?> getClass();`, as far as I can see `m_something.getClass()` seems to be resolving "correctly" as:
> 
> > ReferenceType{java.lang.Class, typeParametersMap=TypeParametersMap{nameToValue={java.lang.Class.T=WildcardUsage{type=EXTENDS, boundedType=ReferenceType{java.lang.Object, typeParametersMap=TypeParametersMap{nameToValue={}}}}}}}

MethodResolutionLogic.isAssignableMatchTypeParametersMatchingQName(..) tries to compare the qualified name from each type parameters. MyClass.Ibaz is different from java.lang.Object so the MethodResolutionLogic.findMostApplicable(..) method fails.

**Comment by maartenc** [comment]
The getClass() method is something special which is not treated well by the symbolsolver.

The javadoc of getClass() states:
> The actual result type is {@code Class<? extends |X|>} where {@code |X|} is the erasure of the static type of the expression on which {@code getClass} is called.
