### ISSUE TITLE
How to do a complete walkover of the generated AST?

### ISSUE THREAD

**Issue by codeBlooded29** [javaparser/javaparser#2509]
Hi, first thanks a lot for a wonderful tool like JavaParser! :)

I am trying to build a Java to target language translator for which I want to do a complete walkover of the AST to identify each and every element of my Java source code. Then I will translate each of these components to my target language. Any help would be appreciated.

**Comment by codeBlooded29** [comment]
After going through the documentation, I realised that using **getChildNodes()** function will help us to visit each and every node of the AST from root to leaf nodes. Thanks again for such a good **JavaParser**.

**Comment by matozoid** [comment]
Hi! You'll find a lot of information on this page: https://javaparser.org/getting-started.html

Using getChildren is not recommended - instead use visitors or varieties of the walk method.

**Comment by codeBlooded29** [comment]
Hi, thanks for the reply. I have visited that website and gone through the related tutorials and examples. Could you please throw more light on the varieties of the walk method?

**Comment by matozoid** [comment]
A very good question, because it seems these never got documented :-#

The methods can be found on every `Node` in the AST. The idea is that we want to walk from the node you have, through the tree in some way. The most basic method is `walk`, which has two arguments: `treeTraversal` (the way we want to walk) and `consumer` (what to do when we step on a node.) Other methods are based on that method: a `walk` that assumes pre-order traversal (which does probably exactly the same as your approach with `getChildren`), the `findAll` methods which let you filter the nodes while walking and delivers a list of the nodes that passed the test, the `findFirst` methods which do the same, but only the first one that is found is returned. To find all the varieties, use your IDE's autocompletion, or check the Javadoc: https://www.javadoc.io/static/com.github.javaparser/javaparser-core/3.15.10/com/github/javaparser/ast/Node.html

Varieties are `stream` which is like `walk` but gives you a Java 8 `Stream`, and `treeIterator` on which all of this is based: it gives you a good old Java `Iterator`.

**Comment by codeBlooded29** [comment]
Thanks a lot for elaborating it out :)
