### ISSUE TITLE
Problem matching ConstructorDeclaration with ExplicitConstructorInvocationStmt

### ISSUE THREAD

**Issue by TCke83** [javaparser/javaparser#254]
Hi,

i'm working on a project to analyse certain files.

``` Java
public class A {
  public A(String var) {
    // Do something
  }
}

public class B extends A {
  private static final String VAR = "Some string";

  public B(Object obj, String var) {
    super(var);
    // Do something more
  }

  public B(Object obj) {
    this(obj, VAR);
  }
}
```

Now this is a simple case, a lot of files that extend class A have more than two constructors. I want to be able to get the value 'var' that is send to the super-constructor (of class A).

If I get the constructors of B I get 2 ConstructorDeclaration instances. If I check the one with 2 parameters, is see the call to the super-constructor, but i'm unable to determine the value passed, because it is a input variable of the constructor.

If I parse the constructor with 1 parameter I see the call to a constructor as a ExplicitConstructorInvocationStmt. But i'm unable to match the ExplicitConstructorInvocationStmt to the correct ConstructorDeclaration. 

This is an easy example, one could argue it should be the other one of the two constructors. But like I said, a lot of cases have 3 or more constructors. Is there a way to figure out which ConstructorDeclaration will be called with the ExplicitConstructorInvocationStmt? I was thinking of type checking the parameters of the call but the ExplicitConstructorInvocationStmt doesn't contain any type information.

Thanks in advance for your support.

Regards,

Tom

**Comment by ftomassetti** [comment]
Hi Tom,
what you are trying to do is to solve symbols: in this case you want to associate a constructor invokation to a constructor declaration. This can be done on top of JavaParser but JavaParser itself does not provide this functionality. JavaParser produces an Abstract Syntax Tree (AST) and this is it.
To distinguish between different possible constructors in some cases you can just look at the number of parameters (let's ignore variadic parameters). In the other cases you need to calculate the type of the expressions used as parameters. This is not trivial and require a symbol solver.

In this discussion (https://github.com/javaparser/javaparser/issues/221) @JamesXNelson hinted at the fact he is working on a symbol solver. I have also worked on one which is available at https://github.com/ftomassetti/java-symbol-solver.

In some simple cases you can do without a symbol solver and if you can I suggest doing so. However if you want to solve the problem in general than it is a lot of work.

**Comment by JamesXNelson** [comment]
Federico,

Your project looks amazing.  My work is more directed towards translating the javacc ast into a malleable, queryable, composable AST suitable for generating new code.  I have all sorts of bits and pieces: codegen libs, a javassist fork for querying annotations and types, javax.model, javassist and Gwt wrappers for an AST abstraction (that works on the member level, but not on the statement level), and the only thing I was really missing was a much more competent java parser (so I could get the statements as well).  That was why I picked up javacc, to use as the source parser because the one I rolled on my own is not up to my own standards (and way too much work to consider fixing).

So, I am very glad you came along with your project; this will likely save me a lot of work.

I'm not sure if I'll be able to keep everything in your namespace, but I will try to submit pull requests rather than make another fork...  The very first thing I am doing with my library is going to be an automated source rewrite of javassist source.  I used it for a prototype of a classpath scanner, and I needed to make a lot of little changes (upgrading class visibilities to public, adding accessors to private values, etc.), and I didn't keep up with rebasing, so now it's kind of stuck and growing stale.

So, my current plan/project is to create manifest files for classes and members to rewrite / add / delete; add a file with, say META-INF/xapi/rewrite/javassist/CtClass.java/checkModify() that contains some arbitrary source (scripting language for source rewriting).  Then, create a module which inherits the source dependency and runs a javac plugin which has access to all the rewrite rules, and as it encounters any files, use the javax.model to check if it has members to rewrite, and if so, use javacc to load the source file, perform the rewrite, and emit a new source file.  If I limit the scope of the rewrite rules for now, I really only need javacc to tell me the start / end source positions of the member to rewrite...  But if I can get symbol resolution as well, I will definitely go for it!

I'm not far enough along that I want to make it public, but, as I said, I have all the pieces now, and will find great use in the work you have done so far.  If I can't get my API and yours to agree, I may have to just put a credit link back to your repo, if that is fine with you?

I'm finishing up V2 of my sourcegen framework this weekend.  Once that is done, this is my next task (using javassist as my test example, since I need it anyway for my classpath scanner).  After that, I want to see if I can take the javacc parser itself and see if I can use its AST to generate an implementation of my source gen framework's abstract bits, so that you can take the same BNF and get both the AST and tools to generate that AST cleanly in a programmatic way.

That last part is super ambitious and I'm not sure if I will ever get the time to do it (or if it is 100% possible), but this is the stuff I really love about programming, so I'm going to give it a shot.  If it works out for the simple AST I have (generating a generator), I may try to apply it to the java parser as well, though I am much less optimistic about that actually working.  For the source-rewriter, I had planned to rely on javac to provide me with type resolution, and javacc to parse snippets (either from file or hardcoded).   If I can get both from javacc, and not rely on javac, so much the better.

And, if in a couple years I can make a generic source transformation framework for any language via JavaCC, I would consider that really freaking cool.  So, life goals, I guess. :-)

**Comment by ftomassetti** [comment]
Just to be sure there are no misunderstanding:
- JavaParser produces an AST from source code. The project has many contributors, I am just one of them and @matozoid is the mantainer
- java-symbol-solver has be written by me: it processes the AST produced by JavaParser to find out types and link references to corresponding declarations

If we could combine your project with mine that would be great (of course I can change the namespace). In any way your work is beneficial to the JavaParser community so I think it should be promoted among JavaParser users.

I think what you are working on is very interesting and inspiring and I would love to publish something about it on my blog (http://tomassetti.me).

If we can help with any question about taking advantage of JavaParser please feel free to open as many issues as you want or contact us on the gitter channel (https://gitter.im/javaparser/javaparser). For things not strictly related to JavaParser but more on symbol solving you can reach me at federico _at_ tomassetti.me

I hope you will share soon your great work!

**Comment by matozoid** [comment]
Feel free to continue chatting over here: https://gitter.im/javaparser ;-)
