### ISSUE TITLE
Subsequent Java comments cause Javadoc comments to be orphaned/lost

### ISSUE THREAD

**Issue by mernst** [javaparser/javaparser#2600]
Consider this code:

```
class MyClass {

  /** Documentation for method m. */
  // An implementation comment about method m
  void m() { }

}
```

If you run the `javadoc` tool, the generated HTML shows "Documentation for method m." associated with method `m`.

However, when JavaParser creates a `MethodDeclaration` for `m`, calling `getJavadocComment()` on it results in a non-present Optional value.

This discrepancy seems to be a bug:  JavaParser should not say that a node has no Javadoc comment when the `javadoc` tool says that the node does have a Javadoc comment.

The underlying problem is that JavaParser can only associate one comment with each node.  (See https://github.com/javaparser/javaparser/issues/263, https://github.com/javaparser/javaparser/issues/498, https://github.com/javaparser/javaparser/issues/1190, https://github.com/javaparser/javaparser/issues/2346, ...)  This manifestation if it is different, though, and perhaps can be fixed without correcting the underlying limitation.  The Javadoc comment is more important and authoritative than the implementation comments.  Could JavaParser associate the Javadoc comment with the method, and turn the implementation comments into orphans, even if they happen to be lexically closer to the method definition?

**Comment by edefazio** [comment]
Yes, JavaParser does sometimes have issues with Comments...
I believe this is still relevant:
https://tomassetti.me/java-comments-parsing/
How "attribution" works for comments was made a while back, and how comments are stored does have certain limitations (the cardinality is 1-to-1 for nodes with comments)

To change this would cause alot of user code to have to adapt to avoid issues ...(and adding new comment methods might confuse the issue further IMHO)

but as to your question:

> 
Could JavaParser associate the Javadoc comment with the method, and turn the implementation comments into orphans, even if they happen to be lexically closer to the method definition?

this might be something that could be done in your own code... (i.e. if a javadoc comment is not directly associated with a Node...you could get the range of the node (w/o a javadoc comment) then find the orphaned comments in the compilationUnit `node.findCompilationUnit().getAllOrphanedComments()` then see if there is a preceeding comment... not ideal I know, but doable... 

At some point we might want to consider an API breaking refactor of how comments work.  If you are interested in contributing we'd welcome some ideas and design. I believe comments were "tacked on" as a side effect of parsing and they can sometimes feel that way.

thanks

**Comment by mernst** [comment]
> To change this would cause alot of user code to have to adapt to avoid issues

I'm sorry to hear that.  Can you give specific examples of the large quantities of user code that has to adapt?

**Comment by edefazio** [comment]
this is a library, which is used by 1000s of people use, its used in Groovy, and Drools, so big codebases.

all the implementers of `Node` 
have to change (so everything), since Node has
```java
    @OptionalProperty
    private Comment comment;
```
Comments were sorta placed in later (after the project got resurrected)

**Comment by mernst** [comment]
Thanks for the response, but I think you misinterpreted my question.

This discussion (here in issue #2600, which is titled "Subsequent Java comments cause Javadoc comments to be orphaned/lost") is about:

> Could JavaParser associate the Javadoc comment with the method, and turn the implementation comments into orphans, even if they happen to be lexically closer to the method definition?

Can you give an example of how that change would require large quantities of user code to adapt?

**Comment by edefazio** [comment]
Ohh, ok, well in that case, I was responding to this:

>The underlying problem is that JavaParser can only associate one comment with each node. (See #263, #498, #1190, #2346, ...) 

we'd have to either:
1) update the code for comment attribution
2) build a method to "fix" the comment attribution in a post-process fashion

I'd opt for 2), where we could write a tool to accept an AST and implement the strategy you defined (changing the attribution from one line comment to the javadoc comment as you mention).
```java
class MyClass {

  /** Documentation for method m. */
  // An implementation comment about method m
  void m() { }

}
```

That'd be doable and wouldn't require anyone to have to change their existing code or assumptions.  (I like the optionality of building a separate Attribution function, verses changing the default assumptions) Perhaps this strategy (or post processing) becomes the default strategy, but it'd be nice to make it an opt-in separate thing.

**Comment by MysterAitch** [comment]
Personally I take the same broader view as @mernst that this is a bug, with the caveat that what has been written is working exactly as intended/designed per the comment attribution spec linked to by @edefazio . 

In other words, the code isn't "buggy", but as described it is inconsistent with what the "official" tools do. So, bug vs improvement? Does it really matter, other than how this issue gets labelled? 

My view is that we should aim to be consistent with the other tools wherever possible, meaning that we should _at least_ provide an option for behaviour that matches official tools (defaults are a separate debate).

_EDIT: Splitting out a suggestion of a potential way forward, from this comment which is more of a hot-take on how to describe the problem reported by @mernst_

**Comment by MysterAitch** [comment]
Per the edit, here are some thoughts. I'm not particularly invested in these suggestions on how to move forward (strong views weakly held, and all that), and even now in the few hours since posting I've moved away from them. I leave it in full for the record/for discussion, however.

In particular I'd highlight that #638 exists and might where effort should be directed, but I'll defer to @edefazio and @matozoid who have thought it through more fully than I :) 

---

To do this, in the same way that we have multiple printers and can swap them out (e.g. pretty printer/lexical preserving printer), I would like to see the same done with comment attribution.

Alternatively (though not mutually exclusively), we could introduce a comment attribution config (akin to the parser config) which has config options whether to aggregate comments that appear before a node, whether to attribute javadoc to the next non-comment node (skipping lite comments), perhaps even which javadoc processor to use, and possibly more that doesn't come to mind.

---

With respect to if this is a breaking API change, I'm unsure. Perhaps we could additively introduce a new `getComments()` method that returns a collection of comments (which can be empty), keep the current `getComment()` method which iirc returns an optional, and have the two co-exist. I'd actually have to revisit the code to come to a meaningful opinion on this, but on the face of it I (perhaps naively) don't see why not.
