### ISSUE TITLE
Method to obtain orphaned comments

### ISSUE THREAD

**Issue by mernst** [javaparser/javaparser#2603]
A common request from users is a way to collect all the comments that precede a node.
`PrettyPrintVisitor.printOrphanCommentsBeforeThisChildNode` contains such logic, interspersed with printing code.

Please extract the code for collecting orphaned comments that precede a node into its own method, and advertise it so that users don't have to reinvent the wheel by rewriting that logic.
Also, please simplify `printOrphanCommentsBeforeThisChildNode` by using that method.

This is related to #2600, but each has value independently.  The new method is useful everywhere, not just for Javadoc comments.  #2600 would eliminate the need for clients to use the new method, when they are most interested in Javadoc.

**Comment by MysterAitch** [comment]
Hi, Sounds like a reasonable request but, in my limited understanding, it is a rather tricky problem to solve reliably enough to include as a public method (note that `printOrphanCommentsBeforeThisChildNode()` is a private method). 

Some of the significant gotchas will revolve around updating ranges when the AST is manipulated. Beyond this simple note, I really must defer to the experiences of @edefazio and @matozoid who will have both done a lot more than me in this area.

Definitely open to accepting tested PRs btw!

**Comment by MysterAitch** [comment]
That said, am I naive in believing this request to be as simple as this? 

If it turns out to be this trivial, I suggest it's unlikely to be added in until the issues I mentioned above re: the updating of ranges are fixed _(also noting the complexities of the exact position of comments/nodes depending on which printer is being used)_.

```java
// Scope being however we're defining "before" -- within the same block / method / class?
parent = child.getParentNode();
comments = parent.getOrphanedComments()
    .stream()
    .filter(n -> n.range().isBefore(child.range()))
    .collect(Collections.toList)
```

**Comment by edefazio** [comment]
From Gitter chat:
edefazio @edefazio Apr 11 14:35
problem I'm finding WRT "fixing" this issue (and frankly many issues) is that Positions/Ranges seem unreliable in certain scenarios,
(not in scenarios where you read in something and then "Print" it, but rather after you mutate something (i.e. the "new" AST additions are either dont have Ranges, or the ranges they have are "wrong" with respect to where they are being added)

It's nice we can sort based on position, but it's also not really reliable if the positions you have are either not accurate or empty... I think the LPP was an attempt to shore up this, but the only reliable way I've found to do this is to write out the whole AST and read it back in... (Not efficient, and also couples the positions based on some desired "formatting" when you write out and AST and read it back in)

edefazio @edefazio Apr 11 14:54
Here's an example of what I mean:
```java
//create AST from String
        CompilationUnit cu = StaticJavaParser.parse("public class G{\n"+
                "    static public final int i = 0;\n"+
                "}");

        //print original tree
        ASCIITreePrinter.print(cu);

        //simple modification
        cu.getType(0).setStatic(true);

        //print out modified AST
        ASCIITreePrinter.print(cu);
```
prints:
```java
"public class G {...}" CompilationUnit : (1,1)-(3,1)
└─"public class G {...}" ClassOrInterfaceDeclaration : (1,1)-(3,1)
  ├─"public" Modifier : (1,1)-(1,6)
  ├─"G" SimpleName : (1,14)-(1,14)
  └─"static public final int i = 0;" FieldDeclaration : (2,5)-(2,34)
    ├─"static" Modifier : (2,5)-(2,10)
    ├─"public" Modifier : (2,12)-(2,17)
    ├─"final" Modifier : (2,19)-(2,23)
    └─"i = 0" VariableDeclarator : (2,29)-(2,33)
      ├─"int" PrimitiveType : (2,25)-(2,27)
      ├─"i" SimpleName : (2,29)-(2,29)
      └─"0" IntegerLiteralExpr : (2,33)-(2,33)
```

...and after modification:

```java
"public static class G {...}" CompilationUnit : (1,1)-(3,1)
└─"public static class G {...}" ClassOrInterfaceDeclaration : (1,1)-(3,1)
  ├─"G" SimpleName : (1,14)-(1,14)
  ├─"static public final int i = 0;" FieldDeclaration : (2,5)-(2,34)
  │ ├─"static" Modifier : (2,5)-(2,10)
  │ ├─"public" Modifier : (2,12)-(2,17)
  │ ├─"final" Modifier : (2,19)-(2,23)
  │ └─"i = 0" VariableDeclarator : (2,29)-(2,33)
  │   ├─"int" PrimitiveType : (2,25)-(2,27)
  │   ├─"i" SimpleName : (2,29)-(2,29)
  │   └─"0" IntegerLiteralExpr : (2,33)-(2,33)
  ├─"public" Modifier : (1,1)-(1,6)
  └─"static" Modifier : (-)
```

(You'll notice the "static" modifier node has (-) meaning no range... so it's not easy just to "get children" then sort... also looks like the modified NodeList<Modifier> changed positions in the children list (from top to bottom))

Danny van Bruggen @matozoid Apr 11 15:00
Not sure what you mean. It is known at which position the child gets inserted. That information should somehow reach the place where it is added to the children list, which seems to be when its parent is set, which is always done by the library itself, so it is under control.

edefazio @edefazio Apr 11 15:01
When you say position... do you mean Range, or position within a list of Nodes?

Danny van Bruggen @matozoid Apr 11 15:02
Position in a list of nodes, like "I'm inserting this new parameter between nr. 3 and nr. 4"

edefazio @edefazio Apr 11 15:03
Ohh, I'm talking about Range... but let me test something

Danny van Bruggen @matozoid Apr 11 15:03
Yeah, this should not be using ranges.

edefazio @edefazio Apr 11 15:04
(I'm preety sure LPP uses them, also comments uses ranges, and thus multiple bugs)

Danny van Bruggen @matozoid Apr 11 15:04
Looks like it will need some rethinking of where/when the parentnode gets sets
Or so

edefazio @edefazio Apr 11 15:07
also WRT `getChildNodes()`, when you `getChildNodes()` the first time:
```java
[public , G, static public final int i = 0;]
```

...after you make a change:
```java
[G, static public final int i = 0;, public , static ]
```

the order changes...
(thats nothing to do with Ranges)
Danny van Bruggen @matozoid Apr 11 15:07
I'm looking at who adds things to the childlist. It's only this one: https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/ast/Node.java#L393
@edefazio so it's worse than I thought!

edefazio @edefazio Apr 11 15:07
yea, its probably behind lots o problems IMHO

Danny van Bruggen @matozoid Apr 11 15:08
Can't figure why that happens. Someone needs to throw a debugger at this.
This is the kind of issue where you really get to know a piece of software, so I will give you all the gift of debugging it :-)

edefazio @edefazio Apr 11 15:10
Geez thanks
:)

Danny van Bruggen @matozoid Apr 11 15:10
No problem!

edefazio @edefazio Apr 11 15:12
In truth I kinda suspected this and already have a bug assigned to me about Orphan Comments related to this...
javaparser/javaparser#2578

**Comment by mernst** [comment]
It seems that the discussions in this issue are about a different bug:  when the AST is updated, position information may become incorrect.  I'm glad that that other bug is being addressed.  I feel it is an independent problem that should not block this one.

Extracting code into a publicly-accessible method will not introduce any new problems, and it has benefits:
 * Client code will become shorter, simpler, and clearer.
 * The extracte method will work for clients that don't modify the AST
 * If problems are found in the method, then bug fixes can be made in one place, by the JavaParser experts, and clients will automatically get bug fixes when they upgrade to a new version of JavaParser.  That is better than the current situation, where every client of JavaParser has to try to re-implement and may get it wrong.

**Comment by edefazio** [comment]
I am closing this issue and the other one unless you are willing to commit to investing in coding the solution or find someone who is willing to do the work. (Mutation is a part of the tool and if you dont account for it, then no solution makes sense)  If you do decide to invest and write tests for the problem they need to include mutation testing.

Also, as an aside, there is a difference between ASKING for something and TELLING someone or commanding someone to do something, and your Issue Reports come across as very entitled ... If you wish to make the investment, then I am willing to verify that its acceptable, otherwise, your attitude is one I dont appreciate... Here I am on Easter morning getting angry at some entitled person telling me to fix his problem.

We arent going to change the public API for your use case, because it is a library that many people use, and to do so would cause confusion.

**Comment by mernst** [comment]
@edefazio I'm willing to do the work.  But I don't want to waste time making a pull request that will simply be denied.  That's why I opened the issue first:  I wished to get feedback.

Are you open to the the change suggested in this issue?

If so, I will open a pull request.  Can you tell me in which class the new method should appear?  That's something that you may have an opinion about but I don't.

Thanks.

**Comment by mernst** [comment]
@edefazio Could you answer my questions, so that I can get working on the pull request?

**Comment by edefazio** [comment]
You should write the code to solve for your cases in your own repo/fork/project.

As to where this belongs, I don't understand what you want , but it should be natural WRT the library.

I tried to explain why in previous comments (and spent quite a bit of time doing so, time that I'd rather be doing something productive) this is a "No Go", but you keep deflecting based on "misunderstandings"

I would ask that you stop being a burden, because I would rather spend time fixing the real/ underlying architectural issues than debating some theoretical nonsense about an issue you reported 3 years ago.

In the end, though, "code wins arguments" so if you can build what you want and show/explain how it wont be a disaster to maintain & it solves your (and other peoples problems) then please do so.  But frankly you've already wasted my time and put me in a bad mood numerous times so maybe @MysterAitch can look into your PR.

Also, the beauty of open source is that you don't need my permission to fix YOUR problem, I just don't believe its a problem the JavaParser team wants to absorb.

**Comment by mernst** [comment]
@edefazio Thanks for the answer to whether you are open to such a change.

@MysterAitch Are you open to a pull request that would create a method to obtain orphaned comments?  If so, in which class should the method appear.  Thanks.
