### ISSUE TITLE
Eclipse Problem

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [javaparser/javaparser#2606]
One of the plugins that is require for Eclipse is "m2e-connector for maven-dependency-plugin"

However, when I want to install it I get the following warring  "The following solutions are not compatible with this version of Eclipse"

Do you have any suggestion?

**Comment by MysterAitch** [comment]
Hi @Amirfarhad-Nilizadeh , 

Unfortunately this sounds like it's a general Java/Eclipse question rather than a question about using or building JavaParser, so is not appropriate for the JavaParser issue/bug tracker here.

That said, I shall give this advice: find out which versions are compatible with the plugin, and see if you can use that version. Alternatively, see if you can use a version of the plugin that is compatible with your version of Eclipse. 

If neither of those help, https://stackoverflow.com/ may be a better venue for this question.

Hope this helps, and please do feel free to get in touch if you have any further JavaParser-related questions or queries!

Kind regards
