### ISSUE TITLE
SymbolSolver to work with JGit

### ISSUE THREAD

**Issue by shaifulcse** [javaparser/javaparser#2607]
Consider the following code:

`mt.resolve().getQualifiedSignature();
`Here mt is of type MethodDeclaration.

Now in order it to work accurately, I need to set the following:

```
CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
combinedTypeSolver.add(new ReflectionTypeSolver());
combinedTypeSolver.add(new JavaParserTypeSolver(new File("src/java1/")));
combinedTypeSolver.add(new JavaParserTypeSolver(new File("src/java2/ ")));

```
This is easy, except I have two issues considering my scenario.

1) I can not set the root source directories manually. I need to find them automatically.

2) I can not give path like the above, because I am using jGit to checkout to different commits. So the paths are not fixed and might vary based on the different checkout commits. So the path should be accessed using JGit tree.

Any help would be highly appreciated.

**Comment by MysterAitch** [comment]
Hi @shaifulcse ,

Does this blog post help you at all? It describes one way to analyse a whole project in one go!

https://javaparser.org/setting-up-for-analysing-a-whole-project/

I can't really comment on the jgit bits though -- hopefully the `ProjectRoot` will be enough, but if not then you'll need to write something which helps you to extract some paths from jgit.

Hope you're staying both safe and well!

**Comment by shaifulcse** [comment]
Thanks for your reply. The blog post actually did not help. I tried that before posting this issue, but was having StackOverflow errors.

**Comment by MysterAitch** [comment]
Hi @shaifulcse I've listed my understanding of what you describe you are trying to achieve. It sounds like the problem you have is with step 2 - is this correct? 

1. Checkout project using JGit
2. Extract project/source roots from the checked-out project 
   2a. Manually
   2b. Using `ProjectRoot` (given the directory that JGit checked out to)
3. Pass those paths into JavaParser
4. Parse the project
5. ...
6. Profit!

If you are trying to do this manually (2a) then this sounds like a project-specific or JGit problem, not JavaParser. 

If you are trying to use `ProjectRoot` (2b) to do this but it isn't helping (due to errors or incorrect output), then it would be extremely helpful if you would be more precise about the errors you are receiving and the inputs that are causing them. 

Either way, until more information is given (e.g. a reproducible test case, or detailed information about the errors) there's not much we can do to help!

Kind regards.

**Comment by shaifulcse** [comment]
Thanks so much. Unfortunately, there can't be any manual step. I will see what I can do, but thanks  a lot.
