### ISSUE TITLE
Have the language level take account of preview features or not

### ISSUE THREAD

**Issue by MysterAitch** [javaparser/javaparser#2701]
An extension of #2686 will be to include additional detail for including/excluding incubator/preview features.

I've added this as a separate issue as it's a bit more of a substantial change and needs some additional thought on how to achieve this.

Initial ideas:

- Additional enum values e.g. `LanguageLevel.JAVA_14` and `LanguageLevel.JAVA_14_ENABLE_PREVIEW`
- Add a configuration option that mirrors the cli arguments e.g. `parserConfiguration.setEnablePreview(boolean isEnabled)`
- Maybe something else...?

The validators will also need to be extended/created to take the above into account.

**Comment by MysterAitch** [comment]
Question: Are there any examples of preview features changing substantially between versions? e.g. TextBlocks is now on 2nd preview

If there are substantial changes, then it might be the case that Java 14 preview textblocks implementation might need to be different to the Java 13 preview textblocks implementation.

My presumption is that this is minimal and won't affect us **IF** there are any examples of this, but if there are any examples then this should be added as a separate issue rather than blocking this one.

**Comment by matozoid** [comment]
Switch expressions moved from "break 123" to "yield 123". I decided not to support the first version anymore because it made the BreakStatementNode less specific, which is less user friendly. I guarantee that nobody will ever miss it because it needed a compiler switch to turn it on, it is no longer implemented in any supported Java compiler, and no sane person will have released code based on it. My suggestion would be to see the preview features as a nice preparation for the final feature, not something to support forever. When you implement a preview, the next iteration (the next preview or the final feature) will probably be a lot easier to implement.

**Comment by MysterAitch** [comment]
I think where this is coming from is surprise that if I specify "JAVA_14", then by default this includes the preview features.

Perhaps additional documentation might reduce this surprise as a way of solving this?

> My suggestion would be to see the preview features as a nice preparation for the final feature, not something to support forever.

100% I am wary of this potential rabbit hole -- and I'm not volunteering to take this work on _(we're not building a compiler! :wink:)_, but at the same time I would really like to have the feature support for each version be more explicit. 

The case of break vs yield could easily be handwaved away as an exception/exclusion -- anybody who cares enough can submit a PR and/or make the case for it.

**Comment by matozoid** [comment]
Everything depends on how much effort you want to spend on it. I can imagine only supporting previews for the latest version, for example, and taking them out of older versions. Or maybe not support the in-between releases from the last years at all. Some of the older language levels are there more for fun, for example. Who is ever going to use those seriously? Did any Java 1.0 code survive? Who wants to put this into JavaParser? I bet that adds up to 0 users :-)

I think the easiest way to toggle preview features would be to introduce extra language levels. JAVA_14 and JAVA_14_WITH_PREVIEW_FEATURES. No extra code paths required, only an extra validator and processor, which neatly show what gets enabled. So your option 1 then :-)

**Comment by MysterAitch** [comment]
The main thing being that if somebody wanted to use JavaParser to upgrade a Java 1.0 codebase to Java 14, then we (presumably) currently support it -- a rather nifty thing to be able to brag about :wink:

> I think the easiest way to toggle preview features would be to introduce extra language levels. JAVA_14 and JAVA_14_WITH_PREVIEW_FEATURES. No extra code paths required, only an extra validator and processor, which neatly show what gets enabled. So your option 1 then :-)

+1

**Comment by MysterAitch** [comment]
How would you feel about defaulting to whatever the runtime java version is?

It would be a pretty clear message that "you get the language features of your current JRE/JDK, but if you care about specific features then you should edit the configuration" and would avoid surprises like not being able to parse e.g. module info files even if you're running the latest JDK.

That said, it could lead to some surprises if you upgrade or switch machines.

.. a bit of a trade-off, but it seems a reasonable one to me!

Thoughts welcomed!

**Comment by matozoid** [comment]
I was thinking that it was a nice idea until I thought: but what if someone makes an application using JP, spreads it to users, and now those users get parse errors because they are using an older JRE that the developer? Maybe defaulting to the latest Java version is better, or what someone else suggested: making a clearer error that your language level is set wrong.
