### ISSUE TITLE
BreakStmt without a label - break empty?

### ISSUE THREAD

**Issue by PELock** [javaparser/javaparser#2717]
I have just updated my Maven dependency (core) to 3.16.1 and I'm using this:

`BreakStmt breakStmt = new BreakStmt();`

and getting this in output source code

`break empty;`

I have tried to do it like this:

`BreakStmt breakStmt = new BreakStmt("");`

but at runtime it throws an error that the label is empty 

`java.lang.AssertionError: A string was unexpectedly empty.`

So how am I suppose to generate a "break" command with an empty break label?

**Comment by PELock** [comment]
Meh I have found this method:

`breakStmt.removeLabel();`

but it broke my old code and by default the label should be null if initialized like this:

`BreakStmt breakStmt = new BreakStmt();`

**Comment by MysterAitch** [comment]
Hi @PELock -- What version are you upgrading from? 

Looking at the file history, there haven't been any code changes in the last six months or so (just javadoc changes) so I can only presume there has been a change somewhere else.

I don't use the code generation side of things, so I'm not familiar with how it normally behaves etc.

**Comment by matozoid** [comment]
Quick background: the default constructor initializes every field that cannot be null to a default value like "empty". Since this parameter *can* be null, it was a mistake to initialize it with "empty". (My bad.) I suggest to change the initial value of this parameter to null. Nobody should be using the default value, so this should not break anything.

**Comment by MysterAitch** [comment]
My understanding based on @matozoid 's update is that this should be easy enough to fix (just change the default value), so can be targeted at the next release (hopefully before the end of this week).

We can always undo this if it looks tricky or if I have misunderstood!

@PELock - would you be interested in submitting a PR to address this? 😊

**Comment by navkumar258** [comment]
Hi team, looking for my first contribution here, is someone working on it or can i take it up...? thanks :smile:

**Comment by MysterAitch** [comment]
> 
> 
> Hi team, looking for my first contribution here, is someone working on it or can i take it up...? thanks smile

@navkumar258 - you would be very welcome to take this up! :)

**Comment by navkumar258** [comment]
@MysterAitch As suggested by @matozoid , did the below change in my fork, but don't know how to proceed with testing the change whether it breaks something or not...please suggest. thanks !

![image](https://user-images.githubusercontent.com/7344604/90269916-0552ac00-de77-11ea-9343-7f53499dc1f3.png)

**Comment by MysterAitch** [comment]
Tests break down into the following steps: 

1. **Setup the pre-conditions** -- what is true/setup before we do anything? 
	e.g. if we want to test adding a record to a database, we first need a database connection (in our case, we need to setup JavaParser with the relevant configuration).
2. **Do something with a side-effect** -- this is the action we're testing
	e.g. trigger adding a record to the database (in our case, create a new object with no `label` parameter)
3. **Test the post-conditions** -- what is true after we have done something
	e.g. we should have one more record in the database, and the one that we added should be present (in our case, we need the constructor to succeed and the values in that object should be what we expect them to be -- null not empty)

Ideally you should see that the test case fails before you make your modification, and then passes afterwards. This way, you can be sure that it was your change that made things better (as opposed to the test case coincidentally passing).

Note that not all stages are explicitly needed all of the time, but you can see some other tests here in this file (some more are in the same directory):

https://github.com/javaparser/javaparser/blob/a46e20794b1fd7ebef85a5f72fec9b5d6ee5bf5b/javaparser-core-testing/src/test/java/com/github/javaparser/ast/stmt/BreakStmtTest.java#L31-L35


I have been deliberately vague here with respect to precisely what code to write or how to run the tests (i.e. broadly describing actions, rather than how to run JUnit). If you need a hand with these bits give a shout and we'll give you some more pointers! :)
