### ISSUE TITLE
JavassistClassDeclaration isAssegnableBy throws NotFoundException when a class/interface is defined in another Jar

### ISSUE THREAD

**Issue by corradomio** [javaparser/javaparser#2762]
There is a "problem" with the current implementation of

JavassistClassDeclaration::isAssegnableBy(ResolvedType)   (line 267)

the problems are in lines:

281:  this.ctClass.getSuperclass()
285: for (CtClass interfaze : ctClass.getInterfaces())

when ctClass is of type:  CtClassType.

For example, the implementation of "CtClassType::getInterfaces()" is

```java
@Override
    public CtClass[] getInterfaces() throws NotFoundException {
        String[] ifs = getClassFile2().getInterfaces();
        int num = ifs.length;
        CtClass[] ifc = new CtClass[num];
        for (int i = 0; i < num; ++i)
            ifc[i] = classPool.get(ifs[i]);                  // <<===

        return ifc;
    }
```

where the implementation of "ClassPool.get(classname)" is

```java
public CtClass get(String classname) throws NotFoundException {
        CtClass clazz;
        if (classname == null)
            clazz = null;
        else
            clazz = get0(classname, true);

        if (clazz == null)
            throw new NotFoundException(classname);
        else {
            clazz.incGetCounter();
            return clazz;
        }
    }
```

Now, you suppose 

1) to have a JarTypeSolver for the JDK and ANOTHER JarTypeSolver for another library LIB.
2) to have a class/interface in LIB (used inside the code) that implements the interface "java.io.Serializable" (or extends/ implements some class/interface in the JDK)

BECAUSE the classes & interfaces are resolved in the SAME classpool of the current class, the code throws the exception "NotFoundException".

The CURRENT SOLUTION is to collect in an UNIQUE classPool ALL external libraries PLUS the JDK.
That is, the classPool must be used like a Java class loader.

Obviously, this is not limited to JDK and LIB, but it is general.

The CORRECT SOLUTION is to resolve classes & interfaces starting ALWAYS from the root type solved.

**Comment by jlerbsc** [comment]
@corradomio Thanks for reporting this issue.

**Comment by jlerbsc** [comment]
Hi @matozoid , @maartenc , @ftomassetti The easiest way to solve this problem is probably to make the JarTypeSolver.addPathToJar (..) method public and offer the possibility to initialize JarTypeSolver with multiple jar files like this. What do you think of this proposal?

    JarTypeSolver jSolver= new JarTypeSolver("src/test/resources/jar1.jar");
    jSolver.addPathToJar("src/test/resources/jar2.jar");
    typeSolver.add(jSolver);

or if addPathToJar returns the JarTypeSolver instance :

    JarTypeSolver jSolver= new JarTypeSolver("src/test/resources/jar1.jar").addPathToJar("src/test/resources/jar2.jar");
    typeSolver.add(jSolver);

**Comment by matozoid** [comment]
I think there is some issue where we were trying to have JarTypeSolver contain only a single jar, because it is pretty confusing to have multiple in there.

**Comment by maartenc** [comment]
I think the real problem here is that we use the `CtClass.getSuperClass()` and `CtClass.getInterfaces()` methods directly. This requires that the jars containing these ancestor classes should be known to Javassist.

Providing extra methods to add these jars to the javassist classpool would be good, but the real fix is imho not to use these 2 methods mentioned above, but instead use the TypeSolver to find the superclass and interfaces.

**Comment by jlerbsc** [comment]
Hi @matozoid, @maartenc  you are referring to the issue #2547.  I think this issue was due the statement below that add the same JarTypeSolver instance multiple time.

    combinedTypeSolver.add(JarTypeSolver.getJarTypeSolver(jar));

This is not the same as adding a single instance of JarTypeSolver which contains all the jar files.
I tested this solution which passes all the tests. It may be a temporary fix before someone implements a new algorithm.

**Comment by jlerbsc** [comment]
Hi @matozoid, @maartenc I think an alternative would be to share a single instance of Javassist ClassPool between all instances of JarTypeSolver.

**Comment by maartenc** [comment]
Hi @jlerbsc , I don't think a shared Javassist ClassPool across all instance of JarTypeResolver is a good idea, because that way different CombinedTypeSolver instances could see each others classes.

```
CombinedTypeSolver solver1 = new CombinedTypeSolver();
solver1.add(new JarTypeSolver("foo.jar"));
solver1.add(new ReflectionTypeSolver());

CombinedTypeSolver solver2 = new CombinedTypeSolver();
solver2.add(new JarTypeSolver("bar.jar"));
solver2.add(new ReflectionTypeSolver());
```

If the ClassPool is shared, solver1 could see classes of bar.jar and vice versa.

**Comment by maartenc** [comment]
Hmz, it seems `JarTypeSolver` only can find classes that are present in it's jars. So ignore my previsous comment.
Although I still think it's not a good idea to 'share' some state accross the different TypeSolvers.

**Comment by jlerbsc** [comment]
and vice versa 

    CombinedTypeSolver solver1 = new CombinedTypeSolver();
    solver1.add(new JarTypeSolver("foo.jar"));

    CombinedTypeSolver solver2 = new CombinedTypeSolver();
    solver2.add(new JarTypeSolver("foo.jar"));

loads the same classes twice in different ClassPool

In fact ClassPool acts as a classpath for javassists. So I don't understand your apprehension but I don't know JP enough to say that it wouldn't be a problem. In any case what I can say is that all the unit tests pass.

**Comment by jlerbsc** [comment]
Hi @ftomassetti Could you share your opinion on this topic please?

**Comment by MysterAitch** [comment]
My feeling/preference is to wholly avoid shared state (including statics/singletons) wherever possible, which aligns with @maartenc 's comments above.

This might be a naive assumption (still catching up on all of the threads), but does a `CombinedTypeSolver` not work when provided with multiple JARs? 

My (naive) understanding is that including multiple solvers within a `CombinedTypeSolver` is analogous to setting up the the class paths when running a jar. For example, I would expect the following examples to work fine (but the open issues and this discussion seems to suggest it doesn't?).

```java
CombinedTypeSolver solver1 = new CombinedTypeSolver();
solver1.add(new JarTypeSolver("foo.jar")); // contains interface Foo
solver1.add(new ReflectionTypeSolver());

CombinedTypeSolver solver2 = new CombinedTypeSolver();
solver2.add(new JarTypeSolver("foo.jar")); // contains interface Foo
solver2.add(new JarTypeSolver("bar.jar")); // contains class Bar which implements interface Foo (from foo.jar)
solver2.add(new ReflectionTypeSolver()); 
```

... and I would expect this to fail due to not having `foo.jar` available "in the class path":

```java
CombinedTypeSolver solver3 = new CombinedTypeSolver();
solver3.add(new JarTypeSolver("bar.jar")); // contains class Bar which implements interface Foo (from foo.jar)
solver3.add(new ReflectionTypeSolver()); 
```

**Comment by maartenc** [comment]
I think the problem with solver2 is that the JarTypeSolvers don't share the same javassist ClassPool. This can give issues if a class A in foo.jar for instance extends a class B in bar.jar. In that case, the first JarTypeSolver cannot find the superclass B through javassist (which is the root cause of the problem in my opionion because JavaParser shouldn't use javassist in the first place to find the superclass).

But the easiest fix (not the best fix) imho is to allow to add extra jars to be added to JarTypeSolver which was @jlerbsc first suggestion above.

**Comment by MysterAitch** [comment]
A few more test cases / descriptions of desired behaviour that completely ignores what JavaParser _currently_ does, instead focusing on what it _should_ be doing.

.... and lots and lots of questions to consider! :grin: 

----

```java
CombinedTypeSolver solver2 = new CombinedTypeSolver();
solver2.add(new JarTypeSolver("foo.jar")); // contains interface a.b.c.Foo
solver2.add(new JarTypeSolver("bar.jar")); // contains class Bar which implements interface a.b.c.Foo (from foo.jar)
solver2.add(new ReflectionTypeSolver()); 
```

1. Trigger solving `a.b.c.Foo` as an interface of `Bar`
2. Fail, because `a.b.c.Foo` isn't defined within the same JAR as `Bar`
3. (catch the failure/error and) Escalate to the "parent context" (i.e. the parent solver - in this case `solver2` to attempt to solve `a.b.c.Foo`
4. The `CombinedTypeSolver` then iterates through it's child solvers to attempt to solve `a.b.c.Foo`

It seems, based on the descriptions, steps 3 and 4 aren't happening.

----

```java
CombinedTypeSolver solver4 = new CombinedTypeSolver();
solver4.add(new JarTypeSolver("foo2.jar")); // contains interface a.b.c.Foo
solver4.add(new JarTypeSolver("bar.jar")); // contains class Bar which implements interface a.b.c.Foo (from foo.jar and/or foo2.jar)
solver4.add(new JarTypeSolver("foo.jar")); // contains interface a.b.c.Foo
solver4.add(new ReflectionTypeSolver()); 
```

Question -- in this case, where there are multiple definitions of `a.b.c.Foo`, should `a.b.c.Foo` resolve to `foo.jar` or `foo2.jar`? 

- Maybe an error is thrown due to not being able to distinguish which one to use? 
- Maybe default to using the first found definition? 
- Maybe go through in reverse order and assume that later additions overwrite/override previous declarations? 
- Maybe the order within the combined solver is important, and only the solvers added prior to `bar.jar` are used?

---- 

```java
CombinedTypeSolver solver5 = new CombinedTypeSolver();
solver5.add(new JarTypeSolver("bar.jar")); // contains class Bar which implements interface a.b.c.Foo (probably from foo.jar)
solver5.add(new JarTypeSolver("foo.jar")); // contains interface a.b.c.Foo
solver5.add(new ReflectionTypeSolver()); 
```

Depending on the answers to questions above about the importance of ordering, should this `solver5` example succeed?

If order is important, we also need to consider the other solvers -- e.g., would the place that `ReflectionTypeSolver` is added be important (where it MUST be first to be used within later solvers?).

**Comment by maartenc** [comment]
I think order is important: just like the java compiler/runtime takes the first class on it their classpath, JavaParser should do the same.
So solver4 should take the one from foo2.jar. Solver5 should work without a problem.

The issue here is caused because we use constructs like `CtClass.getSuperClass()` and `CtClass.getInterfaces()` at several locations, instead, we should use the typesolvers to find the superclass or interfaces.

**Comment by MysterAitch** [comment]
> I think order is important: just like the java compiler/runtime takes the first class on it their classpath, JavaParser should do the same.
> So solver4 should take the one from foo2.jar. Solver5 should work without a problem.

I agree :+1: 


> The issue here is caused because we use constructs like `CtClass.getSuperClass()` and `CtClass.getInterfaces()` at several locations, instead, we should use the typesolvers to find the superclass or interfaces.

There might be a good reason it can't happen, but if there turns out to be a good reason to use `CtClass.get...` but could we not just catch the exception and _then_ retry using alternative typesolvers?

Note that both methods mentioned [throw `NotFoundException` ](http://www.javassist.org/html/javassist/CtClass.html#getSuperclass()) when the superclass/interfaces can't be found. 


_(I have no strong views either way here -- this comment is coming from an assumption that Javassist is better (faster) at getting info out of JARs than JavaParser is, so we should first default to using Javassist wherever possible before re-implementing it ourselves)_

**Comment by maartenc** [comment]
Agreed, if we catch that exception and retry finding the type with the TypeSolvers.
Although probably not 100% correct, I think it will be good enough for almost all JavaParser use cases.

**Comment by MysterAitch** [comment]
Let's aim for 100% correct! :+1:

**Comment by maartenc** [comment]
Well, the 100% correctness is always to use the TypeSolvers I'm afraid, probably losing some performance. (maybe we should test this, it might be not an issue ?)

Consider this example:

CombinedTypeSolver solver = new CombinedTypeSolver();
solver.add(new JarTypeSolver("foo.jar")); // contains interface a.b.c.Foo
solver.add(new JarTypeSolver("foobar.jar")); // also contains interface a.b.c.Foo and class Bar which implements a.b.c.Foo
solver.add(new ReflectionTypeSolver()); 

When you ask the interfaces of the class Bar, you want the get a.b.c.Foo from foo.jar.
At least, this is how javac and java behave...

Also note that it should also work with self-made typesolvers:
CombinedTypeSolver solver = new CombinedTypeSolver();
solver.add(new MyCoolTypeSolver("foo.jar")); // contains interface a.b.c.Foo
solver.add(new JarTypeSolver("foobar.jar")); // also contains interface a.b.c.Foo and class Bar which implements a.b.c.Foo
solver.add(new ReflectionTypeSolver()); 

So simply sharing the ClassPool accross all JarTypeSolvers (within the same solver) wouldn't 100% correctly solve the issue.

**Comment by jlerbsc** [comment]
You have debated this subject and raised a lot of interesting ideas. It is a pity that the creators of the project do not intervene to tell us what they wanted to put in place or what should be put in place. 
Anyway even if I think that the most common case is solved using a single instance of Classpool and that the marginal case where we could have several versions of the same class is not, it seems to me that the question that we must ask ourselves now should be the following :
"Initially, is a solution which solves the common cases sufficient because it unblocks many users of JP or it is necessary to set up a solution which answers all the cases (including the marginal cases)?"
It seems reasonable to me to think that the problem raised relates to a very common case of software architecture (separation of interfaces and implementations) and although it has been several years since this bug was raised for the first time, it is not still corrected. Unfortunately, faced with this difficulty in solving this bug, it is quite possible that many users have turned to other solutions (such as spoon).
What do you want to do concretely? Moreover if you do not agree with the solution I have proposed you can perfectly revert on it. I would understand perfectly well that it does not correspond to what you want to set up to correct this bug.
@ftomassetti @matozoid  do you have an opinion?

**Comment by 4everTheOne** [comment]
Looking into the issue, I think maartenc has a point when he says that sharing a ClassPool could solve the problem.

> So simply sharing the ClassPool accross all JarTypeSolvers (within the same solver) wouldn't 100% correctly solve the issue.

Based on that principle I got a suggestion for the implementation, but not sure if it's simple to use for the end user. The ideia is to add a "special" combined type solver (that i'll call it `SharedClassPoolTypeSolver`) that can only accept `JarTypeSolver's`. This type solver has a `ClassPool` in it that can be accessed by it's childs. The `JarTypeSolver's` also have a ClassPool in it, BUT if they have a parent directly attached that's a `SharedClassPoolTypeSolver` then he should use the parent `ClassPool` instead of their own.

I think this logic follows the same principles that have been mentioned above, such:
[X] Don't break the current API;
[X] By analyzing 2 versions of the same program they don't interfere with each other;
[X] We can solve dependencies that are defined in another jar;

Giving an example of code for it, I would imagine something like:
```java
SharedClassPoolTypeSolver sharedSolver = new SharedClassPoolTypeSolver();
sharedSolver.add(new JarTypeSolver("foo.jar")); // contains interface a.b.c.Foo
sharedSolver.add(new JarTypeSolver("bar.jar")); // contains class Bar which implements interface a.b.c.Foo (from foo.jar)

CombinedTypeSolver solver = new CombinedTypeSolver();
solver.add(sharedSolver);
solver.add(new JarTypeSolver("thisDoesNotInterfereWithTheSharedSolver.jar")); 
solver.add(new ReflectionTypeSolver()); 
```

**Comment by jlerbsc** [comment]
> but not sure if it's simple to use for the end user
With a solution of this type, users must know the dependencies between libraries, hoping that this does not raise other issues.

**Comment by 4everTheOne** [comment]
Yes, you right. That may bring more problems than what it solves.

Taking a fresh look at it, and like corradomio has mentioned the issue is related with the USE `ctClass.getSuperClass()` and `ctClass.getInterfaces()` when we need to check if the supper class is assignable by another. The ideal workaround for it (which have also been mentioned by corradomio) would be to solve on type solver instead of relying on `CtClass`. This can be achieved by getting the fully qualified name thru `ctClass.getClassFile().getInterfaces()` and thru `ctClass.getClassFile().getSuperclass();` of the class and then ask the type solver to resolve it.

Lucky for us, this logic is already implemented in `JavassistClassDeclaration#getInterfaces()` and `JavassistClassDeclaration#getSuperClass()`. 

What if we update this part of the code to use the `JavassistClassDeclaration#getInterfaces()` and `JavassistClassDeclaration#getSuperClass()` instead of using the `CtClass` directly?
https://github.com/javaparser/javaparser/blob/c9f679bc2394fb2e163af04e6907f4567d92501b/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistClassDeclaration.java#L280-L292

**Comment by maartenc** [comment]
Yes, I'm trying that approach now.
See #3167 (still work in progress)
