### ISSUE TITLE
what is this concept of "Phantom" nodes

### ISSUE THREAD

**Issue by jlerbsc** [javaparser/javaparser#2935]

**Comment by MysterAitch** [comment]
It's a while since I last looked at them, but my understanding is that phantom nodes are classes/objects which are present in JavaParser but do not necessarily represent an AST node.

IIRC this is typically where we have a `NodeList` of e.g. modifiers or declarations (which are containers containing properties of a node, rather than being a node itself). There might be other examples too.

To give a code example / pointer, note that the nodes within a `NodeList` do not have the `NodeList` as their parent:

```java
    private void setAsParentNodeOf(Node childNode) {
        if (childNode != null) {
            childNode.setParentNode(getParentNodeForChildren());
        }
    }
```

**Comment by MysterAitch** [comment]
Is this something that warrants documentation updates, perhaps?
