### ISSUE TITLE
Russian comments in manual

### ISSUE THREAD

**Issue by digulla** [javaparser/javaparser#304]
There are Cyrillic letters in comments in the last example on the manual page https://github.com/javaparser/javaparser/wiki/Manual

**Comment by ftomassetti** [comment]
Interesting... this proves the spread of this project and our support for cultural diversity I guess. Let's look into how it happened...

**Comment by ftomassetti** [comment]
Ok, the wiki can be edited by everyone and we do not get notification so things can be easily get unnoticed: I am afraid contributors tend not to look at the manual. We should work more on documentation and pay more attention to it because the example with cyrillic letters have also code commented out which is not nice in an example. So thank you very much for taking the time to report this: it is appreciated!
