### ISSUE TITLE
JavaSymbolResolver doesn't support Lombok (and similar libraries) injected code

### ISSUE THREAD

**Issue by corradomio** [javaparser/javaparser#3095]
Project Lombok is able to inject automatically fields (as `log` using `@Slf4j`) and methods (as `getAnInt()` using `@Data`).
Without a specific support, JavaSymbolResolver is not able to resolve these symbols.

```java
package test;

import lombok.Data;
import lombok.extern.slf4j.Slf4j;
import lombok.val;
import lombok.var;

@Slf4j
@Data
public class LombokTest {
    
    private int anInt;

    public static void main(String[] args) {
        var iAmMutable = 10;
        val iAmConstant = 20;
        log.debug("log is defined by @Slf4j");

        LombokTest lt = new LombokTest();
        log.info(String.format("getAnInt is generated by @Data: %d", lt.getAnInt()));
    }
}
```

https://projectlombok.org/
https://github.com/rzwitserloot/lombok
https://github.com/google/auto/tree/master/value

**Comment by jlerbsc** [comment]
It's because JP does not know anything about lombok. It works on java source code and resolve symbols from declared libraries.
When you talk about a code injection are you talking about the build phase of the application or the runtime? Anyway this code does not exist in java source files.
If you use Lombok, you are technically not writing valid Java code and JP will not be able to parse it. The solution could be to use delombok to externalise the code that Lombok generates. You can then use JP to parse this valid Java code.

**Comment by MysterAitch** [comment]
See also #2263 and #2436

It is not possible to do this using JavaParser alone -- other tools such as [Delombok](https://projectlombok.org/features/delombok) allow you to work with the code generated by Lombok.

Alternatively you might package your code into a jar and use that as a source, or perhaps first compile your code and point JavaParser at the generated source code.

**Comment by MysterAitch** [comment]
I'll close this now -- if the linked issues and the comment didn't help, comment again and we'll re-open this :+1:
