### ISSUE TITLE
ResolvedValueDeclaration#isType() throws an exception when the value is resolved to a Parameter

### ISSUE THREAD

**Issue by cargaji** [javaparser/javaparser#3128]
Hi! I'm using JavaParser to create a [program slicer for Java](/mistupv/JavaSDGSlicer), and I think I found a bug.

Most implementations of `ResolvedValueDeclaration#isType()` return either `true` or `false`, but `JavaParserResolvedParameter` throws an exception. Is this the expected behaviour? What check should be performed to avoid the exception when calling `isType()`?

**Comment by MysterAitch** [comment]
Looks like an interesting program @cargaji ! :+1: 

I can't find `ResolvedValueDeclaration#isType()` or `JavaParserResolvedParameter` -- could you double check these for typos?

**Comment by 4everTheOne** [comment]
Hello! Is it related with `JavaParserParameterDeclaration`? 

I can confirm there was an issue with the code of `JavaParserParameterDeclaration` that force the throw of `UnsupportedOperationException` instead of returning the default `false`. 👍 
https://github.com/javaparser/javaparser/commit/a7128210025323a9dbb9a3f20f71fef0a59fc980#diff-61ccf1ba5988e12d1ffa20f3302dbbab7edf0db5a2c5bda9dd3da5151cf81950L71-L75

I think i should be fixed in 3.19.0. Could you check the version you are running on please?

**Comment by cargaji** [comment]
Yes, it is `JavaParserParameterDeclaration`, it seems I'm on 3.17.0 still, and browsing through the repo I found the current implementation without the `throw new UnsupportedOperationException...`. Looks like time to update to 3.19.0. Thank you!
