### ISSUE TITLE
Unable to get types for NameExpr which refer to ClassNames

### ISSUE THREAD

**Issue by antonio-mastropaolo** [javaparser/javaparser#3251]
Hello everyone,
Even if the following issue (#2069) seems to be closed, the problem is still here.

```
Math.abs(2);
String.format("%s://%s:%d", "asd", "host", 23);
```

"Math" and "String" cannot be solved.

Any idea?

**Comment by jlerbsc** [comment]
Hi @antonio-mastropaolo can you provide us a test case that demonstrates this issue?

**Comment by jlerbsc** [comment]
@Test
    public void testIssue2069() {
        
        TypeSolver typeSolver = new ReflectionTypeSolver();
        ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(typeSolver));
        StaticJavaParser.setConfiguration(config);

        String s = 
                "public class Test {\n" + 
                "    public static void main( String[] args )\n" + 
                "    {\n" + 
                "        Math.abs(2);\n" +
                "        String.format(\"%s://%s:%d\", \"asd\", \"host\", 23);\n" +
                "        System.out.println( Math.round( Math.random() * Integer.parseInt( args[0] ) ) );\n" + 
                "    }\n" + 
                "}";
        CompilationUnit cu = StaticJavaParser.parse(s);
        
        List<MethodCallExpr>  mces = cu.findAll(MethodCallExpr .class);
        mces.forEach(mce -> {
            System.out.println( mce.toString()+"->"+mce.resolve().declaringType().getQualifiedName());
        });
    }

returns

    Math.abs(2)->java.lang.Math
    String.format("%s://%s:%d", "asd", "host", 23)->java.lang.String
    System.out.println(Math.round(Math.random() * Integer.parseInt(args[0])))->java.io.PrintStream
    Math.round(Math.random() * Integer.parseInt(args[0]))->java.lang.Math
    Math.random()->java.lang.Math
    Integer.parseInt(args[0])->java.lang.Integer
    
So what is your problem?

**Comment by antonio-mastropaolo** [comment]
Could you also try to resolve a NameExpr instead of a method?
In my specific case, I have a bunch of scenario in which I want to resolve each java token.

For the sake of the discussion this is the method I'm experimenting on
```
1  private URI getEndpointUri(final String host,
2                               final int port,
3                              final Properties props)
4    {
5        final String scheme = getProtocol(props);
6
7        String endpointStr;
8        if (port != -1)
9        {
10            endpointStr = String.format("%s://%s:%d", scheme, host, port);
11       }
12        else
13       {
14            endpointStr = String.format("%s://%s", scheme, host);
15        }
16
17        return URI.create(endpointStr);
18    }
```
By running the following
```String resolved = nameExpr.resolve().getType().describe();```
on line 10 and 15, to resolve "String" -> java.util.String, the exception will be raised

**Comment by jlerbsc** [comment]
java.util.String ?

**Comment by antonio-mastropaolo** [comment]
I apologize for that. I mistyped. I meant java.lang.String

**Comment by jlerbsc** [comment]
If you're trying to get the type of a NameExpr, you need to invoke the calculateResolvedType() method.

Here's what the javadoc for the resolve() method says
"Attempts to resolve the declaration corresponding to the accessed name. If successful, a {@link ResolvedValueDeclaration} representing the declaration of the value accessed by this {@code NameExpr} is returned. Otherwise, an {@link UnsolvedSymbolException} is thrown."

It seems clear to me that this method returns "the declaration of the accessed value". In the case of a static method call, there is no notion of value/symbol, so in this case you need to invoke the calculateResolvedType() method, which returns the corresponding type. A more precise explanation is provided by ftomasseti in the https://github.com/javaparser/javaparser/issues/2069 issue.

I'm closing this issue because I consider that the case specified has been resolved.
