### ISSUE TITLE
LexicalPreservationPrinter fails to add annotation to a class field decalared with fully qualified name.

### ISSUE THREAD

**Issue by nimakarimipour** [javaparser/javaparser#3408]
If in a source file, a class field has its fully qualified name present in it's declaration, ```LexicalPreservingPrinter``` fails to add the annotation to it. 

Please consider the code below where I want to add an annotation to class field ```foo```.

```java
String input = "class Test {\n"
              +"  java.lang.Object foo;\n" \\Here if we change java.lang.Object to Only Object, the error will be resolved.
              +"}";
CompilationUnit cu = LexicalPreservingPrinter.setup(StaticJavaParser.parse(input));
TypeDeclaration<?> clazz = cu.getClassByName("Test").get();
clazz.getMembers().forEach(
    bodyDeclaration ->
            bodyDeclaration.ifFieldDeclaration(
                    fieldDeclaration -> {
                      NodeList<VariableDeclarator> vars =
                              fieldDeclaration.asFieldDeclaration().getVariables();
                      for (VariableDeclarator v : vars) {
                        if (v.getName().toString().equals("foo")) {
                          fieldDeclaration.addMarkerAnnotation("Nullable");
                          break;
                        }
                      }
                    }));
System.out.println(LexicalPreservingPrinter.print(cu));
```

And below is the stack trace I get
```java
Exception in thread "main" java.lang.UnsupportedOperationException: kept child(VariableDeclarator) vs "."   <105>   (line 2,col 7)-(line 2,col 7)
	at com.github.javaparser.printer.lexicalpreservation.Difference.applyKeptDiffElement(Difference.java:519)
	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:179)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concreteListChange(LexicalPreservingPrinter.java:338)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.listChange(PropagatingAstObserver.java:72)
	at com.github.javaparser.ast.NodeList.lambda$notifyElementAdded$1(NodeList.java:490)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.github.javaparser.ast.NodeList.notifyElementAdded(NodeList.java:490)
	at com.github.javaparser.ast.NodeList.add(NodeList.java:72)
	at com.github.javaparser.ast.nodeTypes.NodeWithAnnotations.addAnnotation(NodeWithAnnotations.java:59)
	at com.github.javaparser.ast.nodeTypes.NodeWithAnnotations.addMarkerAnnotation(NodeWithAnnotations.java:123)
	at edu.ucr.cs.riple.injector.Main.lambda$null$0(Main.java:55)
	at com.github.javaparser.ast.body.FieldDeclaration.ifFieldDeclaration(FieldDeclaration.java:301)
```

With best regards,

Nima

**Comment by jlerbsc** [comment]
Hi @nimakarimipour thank you for reporting this bug.

**Comment by msridhar** [comment]
@jlerbsc in case it's helpful I wanted to describe one of our use cases a bit more.  We start with source code that has been formatted by [Google Java Format (GJF)](https://github.com/google/google-java-format), and we want to inject some annotations.  After injecting the annotations, we can run GJF again.  We want the final diff to not have any extraneous changes, to ease code review.  It would seem that we could just use `DefaultPrettyPrinter` since we have run GJF before and after.  But, one problem we encountered was that in cases where there are multiple consecutive empty lines in the source code, `DefaultPrettyPrinter` does not preserve that, so some extraneous line deletions show up in the diff.  @nimakarimipour may recall if there were other cases that were of concern.  To work around this issue, we switched to `LexicalPreservationPrinter`, but it seems it is a bit more fragile than `DefaultPrettyPrinter`.

If you have a suggested "middle ground" between these printers that would be helpful for our use case, that would be very interesting to us.  Also, if you think it'd be relatively easy to implement a variant of `DefaultPrettyPrinter` that avoids the issue around consecutive empty lines (maybe a `GJFPreservationPrinter`?), that would be interesting too (and if we implemented such a solution we'd be happy to upstream it).

**Comment by jlerbsc** [comment]
Hi @msridhar It seems to me that DefaultPrettyPrinter and LexicalPreservationPrinter have two differents aproaches. The first formats the code independently of the current format, the second formats the code respecting the current format. So I don't think we can get a solution that combines the two approaches. The easiest way would be to correct the problem you have encountered.

**Comment by nimakarimipour** [comment]
Hello all

> Hi @msridhar It seems to me that DefaultPrettyPrinter and LexicalPreservationPrinter have two differents aproaches. The first formats the code independently of the current format, the second formats the code respecting the current format. So I don't think we can get a solution that combines the two approaches. The easiest way would be to correct the problem you have encountered.

Hello @jlerbsc @msridhar 

Just to add more details to this issue, the error will reproduce for inner classes as well, please find the input below:
```
Foo.Bar obj;
```
```LexicalPreserverPrinter``` fails to add the annotation to class field ```obj``` as well, hence, this issue is not limited to fully qualified typed names.

Another issue we had as @msridhar mentioned is with array declarations when brackets come after the class field name. I created a separate [issue3419](https://github.com/javaparser/javaparser/issues/3419) for more details.

With best regards,

Nima

**Comment by msridhar** [comment]
I dug into this a bit and I think I figured it out.  The issue is that `com.github.javaparser.ast.body.FieldDeclaration` does not have a child node for the declared type of the field.  So, all the tokens for a fully-qualified type name get attributed to the `FieldDeclaration` itself when trying to add the annotation, leading to a mismatch when applying the change in `com.github.javaparser.printer.lexicalpreservation.Difference#apply`.  `MethodDeclaration` _does_ have a child node for the type, and so this test works fine:

https://github.com/msridhar/javaparser/blob/ee989dedfa15d1bcd000da22f4ceadc116d4c862/javaparser-core-testing/src/test/java/com/github/javaparser/printer/lexicalpreservation/LexicalPreservingPrinterTest.java#L1635-L1653

I think the fix is to add a child for the type to `FieldDeclaration`.  I'll work on a PR along these lines.  @jlerbsc if this seems like a wrong strategy to you, please let me know.

**Comment by msridhar** [comment]
I'm a bit stuck.  I added `FieldDeclaration.type` field:

https://github.com/msridhar/javaparser/commit/1b0e2425f9f1278ba4de5f94b439bb1628401e85

It looks like the constructors are generated code, but I am not sure how to get them re-generated.  I tried running `./run_core_metamodel_generator.sh` followed by `./run_core_generators.sh` (updating the scripts to use `../mvnw` instead of `./mvnw`), and that changed some stuff but didn't update the constructors.  I'm also not sure if it's required to make `FieldDeclaration` implement `NodeWithType<FieldDeclaration, Type>`.

Any tips on how to get the constructor(s) re-generated?  If it's easier I can open a draft PR so others can collaborate / push changes.

**Comment by jlerbsc** [comment]
> I think the fix is to add a child for the type to `FieldDeclaration`

Hi @msridhar I don't think this is the right approach, but I haven't had time to look into this topic yet.

> The type is on all of the variable declarators because, thanks to array brackets, each variable can have a different type.

For exemple this declaration is valid.

> int i[], j;

**Comment by msridhar** [comment]
> > The type is on all of the variable declarators because, thanks to array brackets, each variable can have a different type.
> 
> For exemple this declaration is valid.
> 
> > int i[], j;

I see.  So semantically, each variable in the declaration could have a different type due to a differing number of array dimensions.  But _syntactically_, there is a (possibly fully-qualified) type appearing before the list of variables, so it seems that it wouldn't be wrong to represent it that way in the syntax tree, with a proper child node.  The type of each variable could still be stored in the variable declarators; the existing code must be consulting the declarators anyway when determining the declared type of a variable.  But maybe I'm off and this wouldn't work out.

Another possible issue with my proposed change is that it could impact public APIs.  E.g., if clients were required to provide a separate type for `FieldDeclaration`s, that could break clients that construct `FieldDeclaration`s using current APIs by just putting the type(s) inside the variable declarators.  We could maybe work around this by modifying the code in `FieldDeclaration` to set the type correctly for code that uses the current APIs, but that might get very messy.

The only alternate approach I can think of would be to change `com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter#findNodeForToken` to create a "fake" node for the type of a `FieldDeclaration` and map the relevant tokens to that fake node.  This fake node wouldn't be in the AST, but since this would just be for the purposes of `LexicalPreservingPrinter`, maybe that's ok?

**Comment by jlerbsc** [comment]
> so it seems that it wouldn't be wrong to represent it that way in the syntax tree, with a proper child node. The type of each variable could still be stored in the variable declarators; the existing code must be consulting the declarators anyway when determining the declared type of a variable.

This is a solution that may cause confusion.

**Comment by jlerbsc** [comment]
> The only alternate approach I can think of would be to change `com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter#findNodeForToken` to create a "fake" node for the type of a `FieldDeclaration` and map the relevant tokens to that fake node. This fake node wouldn't be in the AST, but since this would just be for the purposes of `LexicalPreservingPrinter`, maybe that's ok?

I do not know the implications of this type of solution so this is not a way that I will favor. Rather, I think this is a special case of dealing with differences that look like dealing with type references.

I think I have a solution for this case but I have to do some tests before validating a solution.

**Comment by msridhar** [comment]
Ok, I have a WIP almost passing the regression tests based on changing the node-to-tokens mapping as suggested above (by pulling out the `Type` child of the variable declarators and using that node).  It's pushed [here](https://github.com/msridhar/javaparser/tree/issue-3408).  I could clean it up a bit but it will still be a bit hackish.  I'll hold off on further changes to that for now.

**Comment by jlerbsc** [comment]
> based on changing the node-to-tokens mapping as suggested above

That's not what i suggested.

**Comment by msridhar** [comment]
Sorry to be unclear, it is what I suggested 🙂 In any case will hold off on the approach.

**Comment by jlerbsc** [comment]
Thanks for offering solutions to resolve this issue. The computation of syntax differences has become over time very complex and contains a multitude of special cases ... fully qualified names of types are a new special case to handle.

**Comment by msridhar** [comment]
Thanks so much for the fix!! We really appreciate it. If we see another issue like this in the future, I now know which code to look at to attempt to contribute a fix myself.
