### ISSUE TITLE
how can I do beautiful parsing when the "if" block is inside the "if" block

### ISSUE THREAD

**Issue by dr3ws** [javaparser/javaparser#3422]
Here is an example of the code:

>         if (n < 4) {
>             int j = 0;
>             j = a + b;
>             if (n < 2) {
>                 int x = 0;
>                 n = 3;
>             } else {
>                 int x = 1;
>                 c = 2;
>             }
>         } else {
>             return  method(2);
>         }

at the output I get this:

> [n < 2, [int x = 0;, n = 3;], [int x = 1;, c = 2;], n < 4, [int j = 0;, j = a + b;, if (n < 2) {
>     int x = 0;
>     n = 3;
> } else {
>     int x = 1;
>     c = 2;
> }], [return method(2);]]

how to get rid of the code block? ideally, it should turn out something like this:

`[n < 4, [int j = 0;, [n < 2, [int x = 0;, n = 3;], [int x = 1;, c = 2;]], [return method(2);]]`

my algorithm:

>     public void visit(IfStmt ifS, Void arg) {
>         super.visit(ifS, arg);
>         ifList.add(ifS.getCondition().toString());
>         ifList.add(ifS.getThenStmt().asBlockStmt().getStatements().toString());
>         if (ifS.getElseStmt().isPresent())
>             ifList.add(ifS.getElseStmt().get().asBlockStmt().getStatements().toString());
>     }

and why does JavaParser parse the inner "if" block first, and then the outer one?

**Comment by MysterAitch** [comment]
The easy question first! :+1: 

> and why does JavaParser parse the inner "if" block first, and then the outer one?

This is due to the order in which you process the "current" node, as compared to when you move onto the "next" node (using `super.visit()`).

Consider this alternative: 
```java
public void visit(IfStmt ifS, Void arg) {
    // super.visit(ifS, arg); // Moved to bottom
    ifList.add(ifS.getCondition().toString());
    ifList.add(ifS.getThenStmt().asBlockStmt().getStatements().toString());
    if (ifS.getElseStmt().isPresent())
        ifList.add(ifS.getElseStmt().get().asBlockStmt().getStatements().toString());
    super.visit(ifS, arg); // Moved here from the top
}
```

**Comment by MysterAitch** [comment]
re: the rest of your question, I believe it's because of the nested `IfStmt` which is a child of the outer-if`s `ThenStmt`.

If you reformat the array output with nesting/indentation, you'll notice that one of the entries within the list is the inner `IfStmt`:

```
[
    n < 2, 
    [int x = 0;, n = 3;], 
    [int x = 1;, c = 2;], 
    n < 4, 
    [
        int j = 0;,
        j = a + b;,

       //// NOTICE HERE THAT THIS IS ALL A SINGLE ENTRY/ITEM (note no comma)
        if (n < 2) {
            int x = 0;
            n = 3;
        } else {
            int x = 1;
            c = 2;
        }
       //// NOTICE HERE THAT THIS IS ALL A SINGLE ENTRY/ITEM (note no comma)

    ],
    [return method(2);]
]
```

![image](https://user-images.githubusercontent.com/1537214/143618566-84a1410b-6be1-463c-8156-1ceabe236cd4.png)


Specifically note that there are three statements within `ThenStmt`:

![image](https://user-images.githubusercontent.com/1537214/143618833-1817466f-579e-4847-9b26-dda0000aa2ae.png)




https://plugins.jetbrains.com/plugin/14245-javaparser-ast-inspector

**Comment by dr3ws** [comment]
> If you reformat the array output with nesting/indentation, you'll notice that one of the entries within the list is the inner IfStmt

Yes, I noticed с:
That is, is it normal that it is output like this by a whole piece of code?
And is it possible to somehow recursively parse. That is, when the "if" block is encountered inside the "if", parse it, and not output it to get something like this:

`[n < 4, [int j = 0;, [n < 2, [int x = 0;, n = 3;], [int x = 1;, c = 2;]], [return method(2);]]`

**Comment by MysterAitch** [comment]
Yes -- you'll need to do a check to see if the current statement being printed is an `IfStmt` node, and handle that differently (e.g. call `super.visit`).

In practice, this means looping over the statements when you call `getStatements()` (and testing if it's an `IfStmt`) rather than just converting it to a string.

**Comment by dr3ws** [comment]
Thank you, I will try to do c:

**Comment by dr3ws** [comment]
I have this output now:
`[n < 4, int j = 0;, j = a + b;, n < 2, [int x = 0;, n = 3;, x += n;], n < 2, int x = 0;, n = 3;, x += n;]`

But the JavaParser sees 2 "if" - the function is called twice, so the following repetitions:
`n < 2, [int x = 0;, n = 3;, x += n;], n < 2, int x = 0;, n = 3;, x += n;]`

>         for (int i = 0; i < 3; i++) {
>             if (ifS.getThenStmt().asBlockStmt().getStatements().get(i).isIfStmt()) {
>                 ifList1.add(ifS.getThenStmt().asBlockStmt().getStatements().get(i).asIfStmt().getCondition().toString());
>                 ifList1.add(ifS.getThenStmt().asBlockStmt().getStatements().get(i).asIfStmt().getThenStmt().asBlockStmt().getStatements().toString());
>             } else {
>                 ifList1.add(ifS.getThenStmt().asBlockStmt().getStatements().get(i).toString());
>             }
>         }

And there were problems when getting the `ElseStmt` block

**Comment by MysterAitch** [comment]
Sounds like you're nearly there, good! :+1:

The next step seems to only call super.visit in one of your branches or some other logic to only print the conditions once.

I don't have the ability to test this, but maybe just call super.visit instead of duplicating handling of the condition/then/else nodes, perhaps something like this?

> > ```java
> >         for (int i = 0; i < 3; i++) { //presumably this shouldn't be hardcoded as i < 3 and, instead, should be something like: i < ifS.getThenStmt().asBlockStmt().getStatements().size()
> >             if (ifS.getThenStmt().asBlockStmt().getStatements().get(i).isIfStmt()) {
> >                 super.visit(ifS);
> >             } else {
> >                 ifList1.add(ifS.getThenStmt().asBlockStmt().getStatements().get(i).toString());
> >             }
> >         }
> > ```
