### ISSUE TITLE
When to use findAll compared with visitor

### ISSUE THREAD

**Issue by ThanoshanMV** [javaparser/javaparser#3488]
To get a list of `MethodDeclaration` in a file,

1. We could implement a simple visitor with or without the state:

```
public class MethodDeclarationVisitor extends VoidVisitorAdapter<List<MethodDeclaration>> {
    
    // visiting method that returns a list of MethodDeclaration to the caller
    @Override
    public void visit(MethodDeclaration md, List<MethodDeclaration> args) {
        super.visit(md, args);
        args.add(md);
    }
}
```
```
MethodDeclarationVisitor methodDeclarationVisitor = new MethodDeclarationVisitor();
List<MethodDeclaration> methodDeclarations = new ArrayList<>();
methodDeclarationVisitor.visit(cu, methodDeclarations);
System.out.println(methodDeclarations.size());
```

2. We could invoke `findAll()` method on `CompilationUnit` instance directly:
```
List<MethodDeclaration> methodDeclarationList = cu.findAll(MethodDeclaration.class);
System.out.println(methodDeclarationList.size());
```

Please correct me if I'm wrong, we could use the visitor for visiting a specific node and store its data inside a kind of a DTO which then can be utilized later.

Could you please let me know the actual use cases of `findAll()` and visitor and which one is efficient in the above-mentioned code snippets?

**Comment by matozoid** [comment]
(here is an article with some context: http://javaparser.org/functional-tree-traversal/ )

I've built this a long time ago...
- Visitors are recursive and can run into stack overflow errors
- visitors can have concurrency issues when modifying the AST while the visitor is running
- visitors can take more control of what gets visited when
- visitors - when implementing the interface - can make sure you are covering every node type - if you want that
- visitors can be more efficient because a single treewalk can do multiple things

That's what comes to mind.

For your snippet the visitor is probably more efficient, although I doubt it matters much. `findAll(...)` certainly looks a lot cleaner.

**Comment by jlerbsc** [comment]
Hi @ThanoshanMV  `findAll ` find all children of a specified type while the visitor visits all child nodes in a node tree.

**Comment by ThanoshanMV** [comment]
Thank you @matozoid and @jlerbsc.
