### ISSUE TITLE
GeneratedJavaParser, Provider, and many other classes do not exist

### ISSUE THREAD

**Issue by gab8192** [javaparser/javaparser#3500]
I cannot compile javaparser because these classes are not there
![2022-02-21 19_29_29-EpicTest – JavaParser java  javaparser-core](https://user-images.githubusercontent.com/77269168/155009876-ff4ad4d3-68f5-47a3-8978-f671402451fd.png)
Why are these classes not in the project? Do i need to generate them? How?

**Comment by jlerbsc** [comment]
Hi @cndeucoeuic did you take the time to read the documentation?
https://github.com/javaparser/javaparser
https://leanpub.com/javaparservisited
https://javaparser.org/

**Comment by jlerbsc** [comment]
I presume these documentations answer the question

**Comment by MysterAitch** [comment]
For reference, this will be because the JavaCC-generated source files have not yet been generated.

Other similar/roughly equivalent commands also exist, but this will normally done via `./mvnw compile` (which includes the `generate-sources` maven lifecycle phase).

These generated files will be created within the `target/` directory, and are required before an IDE / external tools (e.g., test runners) are able to compile the project.
