### ISSUE TITLE
Rewrite (was: Replace JavaCC)

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#354]
After several complaints about JavaCC being an obscure tool, and about an unfixable problem with unicode escapes, it may be a good idea to replace it.

But with what? Please comment.

**Comment by ftomassetti** [comment]
I would recommend ANTLR 4.
There are several benefits imho:
- it is widely known
- it has decent performance
- it permits to write left recursive rules and to handle precedence
- it can generate for several platforms

The third point means that you can try things like:

`expr = literal | expr '*' expr | expr '+' expr ;`

without having to write all those stupid intermediate rules that you have typically to write to handle operators precedence

**Comment by matozoid** [comment]
Renamed this issue to "rewrite" to make it a little broader. I'm suggesting to make 4.0 a full rewrite where we can do some things right that I just don't see getting fixed in the current code base:
- comment support implementation is currently "interesting"
- continuous parsing
- refactoring while keeping the old formatting

**Comment by matozoid** [comment]
- and symbol solving in a separate module

**Comment by ptitjes** [comment]
@ftomassetti Note however that ANTLR requires a runtime jar. That would make a dependency to javaparser-core. I think it is worth to not forget about that...

**Comment by ftomassetti** [comment]
I agree that this has to be considered: all think equal not having runtime dependencies is a benefit and keeping JavaParser "lightweight" is vital, in my opinion.

Which alternatives do we have? Aside ANTLR do we have other options to consider?
[JParsec](https://github.com/jparsec/jparsec)? [SableCC](http://www.sablecc.org/)?
Writing a parser manually?

Of all the options I have listed I would personally think that ANTLR is the best option, but I think we should list all options and exchange ideas, figuring out what matter most to us and the users.

**Comment by matozoid** [comment]
To me, everything that is not ANTLR or lex&yacc seems obscure :)

**Comment by chmuche** [comment]
Intellij use BNF grammar. but it's maybe too old :smile:

**Comment by ftomassetti** [comment]
I love the tools produced by IntelliJ but their internal APIs scare me a lot...

ANTLR seems to me a conservative, solid choice. It has the drawback of needing a runtime. To me is not a big deal but it is true that one selling point of JavaParser is the fact it is light. I am not sure we would be allowed by licenses to produce one "megajar" with the ANTLR Runtime + JavaParser to simplify the life of people unable to use maven or gradle (believe it or not they exist and they write to us from time to time). Note I am suggesting building _also_ the megajar, but encourage people to use the normal jar together with a build system which handles dependencies.

I like ANTLR because it is widely used, there are books about it and a decent community. It is well mantained and probably it will be in the future.

Anyone has more thoughts, suggestions, critics, ideas, advices, comments about the tools proposed so far or other ones?

**Comment by matozoid** [comment]
A side comment, I have to say I've become more positive about the state of JavaParser.
- comment support is probably fixable in a not too complicated way
- continuous parsing is on the agenda again
- refactoring & formatting should be doable

But my comment at the very top remains.

**Comment by matozoid** [comment]
Now that we have 3.0.0, I'm not worried about the things here anymore.
