### ISSUE TITLE
LexicalPreservingPrinter indentation is broken when new field is added first in class

### ISSUE THREAD

**Issue by ryanwalls** [javaparser/javaparser#3570]
When adding a field to the top of a type that has fields already defined, the `LexicalPreservingPrinter` single spaces the inserted field and the first field that follows it.  Then double spaces the next field.

Example test:
```
  @Test
  void insertFieldFirstExpectsIndentationToBeCorrect() {
    CompilationUnit compilationUnit = StaticJavaParser.parse("package foo;\n"
        + "\n"
        + "public class InsertField {\n"
        + "  private static final String bar = \"bar\";\n"
        + "  private static final String bar2 = \"bar2\";\n"
        + "}\n");

    LexicalPreservingPrinter.setup(compilationUnit);

    VariableDeclarator variableDeclarator =
        new VariableDeclarator(StaticJavaParser.parseType("Foo"), "foo").setInitializer(
            "new Bar()");
    FieldDeclaration fieldDeclaration =
        new FieldDeclaration().addModifier(Keyword.PUBLIC)
            .addMarkerAnnotation("Marker")
            .addVariable(variableDeclarator);
    
    compilationUnit.getType(0).getMembers().addFirst(fieldDeclaration);

    String updatedCode = LexicalPreservingPrinter.print(compilationUnit);

    assertThat(updatedCode).isEqualTo("package foo;\n"
        + "\n"
        + "public class InsertField {\n"
        + "  @Marker\n"
        + "  public Foo foo = new Bar();\n"
        + "\n"
        + "  private static final String bar = \"bar\";\n"
        + "  private static final String bar2 = \"bar2\";\n"
        + "}\n");
  }
```

Assertion output:
```
org.opentest4j.AssertionFailedError: 
expected: 
  "package foo;
  
  public class InsertField {
    @Marker
    public Foo foo = new Bar();
  
    private static final String bar = "bar";
    private static final String bar2 = "bar2";
  }
  "
 but was: 
  "package foo;
  
  public class InsertField {
   @Marker
   public Foo foo = new Bar();
   
   private static final String bar = "bar";
    private static final String bar2 = "bar2";
  }
  "
```

**Comment by jlerbsc** [comment]
Hi @ryanwalls You can work around this issue by adding the declaration at the end.

**Comment by ryanwalls** [comment]
> Hi @ryanwalls You can work around this issue by adding the declaration at the end.

Thanks.  That won't work for my case, so I just manually fix the indentation in a later step.

**Comment by u7133453** [comment]
Hello @ryanwalls , I am interested in working on this issue and would love to be assigned to it. Please let me know if there are any additional details or information I should be aware of before starting. I will try to fix it, Thank you :)

**Comment by jlerbsc** [comment]
It's not really a bug. It's more the sequence of operations that causes a problem.
JP is designed to emit events when certain AST nodes are modified and lexical preservation is activated. At each event, LPP recalculates how to present the modified code. To do this, it generates a list of tokens before and after the modification and calculates the operations to be performed.
In your case, you have built a field declaration independently of the AST, so the LPP is not informed of the addition until you include the field in the AST. For example, adding an annotation is an operation that triggers this mechanism , but in your case it didn't happen. What's more, the annotation is a special case; it is an attribute of the field but it is printed independently of the field. 
A more appropriate way of doing this would be to create the node corresponding to the field and insert it into the AST. LPP then generates a representation of this code. Then you add the annotation, which triggers the mechanism again to take account of the node modification.
In your case, you couldn't have been aware of this because it's really an internal operation.

Your code can be written like this:

    @Test
    void insertFieldFirstExpectsIndentationToBeCorrect() {
    CompilationUnit compilationUnit = StaticJavaParser.parse("package foo;\n"
        + "\n"
        + "public class InsertField {\n"
        + "  private static final String bar = \"bar\";\n"
        + "  private static final String bar2 = \"bar2\";\n"
        + "}\n");

    LexicalPreservingPrinter.setup(compilationUnit);

    VariableDeclarator variableDeclarator =
        new VariableDeclarator(StaticJavaParser.parseType("Foo"), "foo").setInitializer(
            "new Bar()");
    FieldDeclaration fieldDeclaration =
        new FieldDeclaration().addModifier(Keyword.PUBLIC)
    //        .addMarkerAnnotation("Marker")   <-- Don't set the annotation here
            .addVariable(variableDeclarator);
    
    compilationUnit.getType(0).getMembers().addFirst(fieldDeclaration);

    fieldDeclaration.addMarkerAnnotation("Marker"); // <-- Now add the annotation to the field

    String updatedCode = LexicalPreservingPrinter.print(compilationUnit);

    assertThat(updatedCode).isEqualTo("package foo;\n"
        + "\n"
        + "public class InsertField {\n"
        + "  @Marker\n"
        + "  public Foo foo = new Bar();\n"
        + "  \n"
        + "  private static final String bar = \"bar\";\n"
        + "  private static final String bar2 = \"bar2\";\n"
        + "}\n");
     }

**Comment by jlerbsc** [comment]
I'm closing this exit because an explanation has been provided.
