### ISSUE TITLE
Interface WithDeclaration does not belong in the AST

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#359]
It seems to have behaviour for outputting a piece of the AST as a String, which seems to be the job of a pretty printer or some other tool to me. Its only usage seems to be in tests, so we might move it there.

**Comment by matozoid** [comment]
@ftomassetti - what was the idea behind this?

**Comment by ftomassetti** [comment]
It was a loooong time ago :)
Well, I think the idea was to mark the elements which represent declarations. It could be useful to have them to implement things like the outline panel, or diagrams. Or also to provide qualified identifiers because given a node I can collect all the NodeWithDeclaration between the given node and root and build an identifier in this way.
I think you cannot move it in tests because it needs to be applied to the AST nodes with represent declarations. If we think it is not useful I guess we should just drop it.

**Comment by matozoid** [comment]
Well, we have quite a bunch of "marker interfaces" by now, like NodeWithAnnotations, so in that way it can stay. But it contains only print methods, and I don't think that's a task of the nodes (well, no other nodes support any printing anyway.)

**Comment by matozoid** [comment]
I don't really know what to do here. @ftomassetti ?

**Comment by matozoid** [comment]
Leaving this in as it is doing no harm. Would still like to move it out of the nodes someday.
