### ISSUE TITLE
Move to a builder style for the AST

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#363]
- have more methods return this
- have more "with..." methods
- use more (...) as a parameter
- have more factory methods

**Comment by ptitjes** [comment]
This is indeed a really practical style to create ASTs as examplified there:
https://github.com/ptitjes/jlato-bootstrap/blob/master/src/main/java/org/jlato/bootstrap/ast/PropertyAndTraversalClasses.java#L101

**Comment by matozoid** [comment]
Hey, long time no see! I was surprised that our API has to be used through cumbersome constructors and adds, really.

**Comment by DeepSnowNeeL** [comment]
Yes please :+1:

**Comment by matozoid** [comment]
I see we have a volunteer, @DeepSnowNeeL ! :)

**Comment by DeepSnowNeeL** [comment]
This 3k lines javacc file afraid me a bit tbh :stuck_out_tongue_winking_eye: 
Would you like to include the builder pattern inside the AST classes ? Or do it in an external class & call the existing methods of the AST classes ? I might fork & give it a try

**Comment by ftomassetti** [comment]
I guess this is also related to #354 : either way if we generate classes for each type of node using some parser generator we are typically restricted to what the parser generator can produce. We could then write (or generate) adapters or other classes to work with the node classes but I do not think we can instruct JavaCC or ANTLR to generate node classes with builders.
Am I wrong? Am I missing anything?
I am more familiar with ANTLR so I am sure that with ANTLR we could:
- generate the node classes (same as we do in JavaParser, but using JavaCC)
- read the "metamodel" either by parsing the grammar definition or analyzing the generated node classes through reflection
- generate something else (like builders) from the metamodel

so that we would have, for example:
- ConstructorDeclaration (generated by ANTLR/JavaCC)
- ConstructorDeclarationBuilder (generated by our own utility)

**Comment by matozoid** [comment]
Before we inflate this so far that it becomes to big to finish, I think it's fine just to look for easy additions to the current code base for this issue. Add a few methods, make a PR, see what the response is. Maybe try to improve the code in #362 ?

**Comment by DeepSnowNeeL** [comment]
I will give it a try and PR when ready.

To be on the same page, Is it ok to have something like :
CompilationUnit compilationUnit = new CompilationUnit();
ClassOrInterfaceDeclaration c = compilationUnit.addClassDeclaration("className"); 
c.addField(type,"name").setPrivate().createGetter().createSetter(); //<amazing
c.addMethod("name").withModifiers(Modifier.PUBLIC).withReturnType(type).addParam("name",type);

**Comment by matozoid** [comment]
Sure, although I think you will get really tired of adding methods with the granularity of "setPrivate()" ;)

createGetter is nice. We're supposed to have an easy to use package, so that seems to be in scope.

Don't forget to steal @ptitjes 's  ideas ;)

**Comment by ptitjes** [comment]
@DeepSnowNeeL @matozoid
Don't steal too much ! And please make suggestions, they are welcome !

**Comment by DeepSnowNeeL** [comment]
I'm facing a problem:
Let's take DocumentableNode, I want to add a builder-like method addJavaDocComment(String) to every class that implements DocumentableNode.
The problem is that my builder methods need to return "this", the actual class on which I call them.

#### I can do it a few different ways :

1) Create the method setJavaDocComment(String) in every of the 11 classes that implements it directly or via a parent (bad for maintenance, refactor and coding style in general)

2) Use generics and the Curiously recurring generic patterns (more info : http://stackoverflow.com/questions/17164375/subclassing-a-java-builder-class)

This way I add the method only to 8 classes since TypeDeclaration will implement the method for its children
Need to add generics to all the classes in the hierarchy 

3) Use 2 + take advantage that Node has the field holding the comment and Implement it in the interface in a really hackish way :

Still need to add generics to all the classes but removes the code redundancy

```
/**
     * Use this to store additional information to this node.
     *
     * @param comment to be set
     */
    @SuppressWarnings("unchecked")
    public default T setJavaDocComment(String comment) {
        ((Node) this).setComment(new JavadocComment(comment));
        return (T) this;
    }
```

Note that this problems applies to a lot of builder-like method I would like to have, like addAnnotation(), setModifier() setName()... all refering to their respective interfaces: AnnotableNode, NodeWithModifiers, NamedNode.

Moreover we can't use 3) on NamedNode for exemple, which means we still need 11 duplicate setName() methods, but we can't really do better.. (If you think of anything, tell me ! )

Take note that adding generics to all the abstract classes and interfaces woudln't really hurt the usage, it could just feel strange to have for exemple in a TypeDeclaration a list like  `List<BodyDeclaration<?>> members;` and this might break backward compatibility or at least raise some warnings about raw types 

What do you think guys ?

EDIT : after a lot of thinking, I'll probably go with 1) , it will be a pain to have a lot of duplicates but that's better than adding generics to do the trick (since it still require duplicates..)

**Comment by matozoid** [comment]
I think I misunderstand the problem because I have a headache, but isn't added the return node type as a generic type parameter to the interface enough?

Will default methods help anything? Probably not, since they access state?

**Comment by DeepSnowNeeL** [comment]
Default methods doesn't help you are right. (Well actually they do knowing that we only have Node types, I let you check the code after)
If we add the generic  to the interface we need to add it to each "hierarchy step" like :

```
public abstract class TypeDeclaration<T> extends BodyDeclaration
        implements NamedNode, DocumentableNode<T>, NodeWithModifiers {
```

And then
`public final class ClassOrInterfaceDeclaration extends TypeDeclaration<ClassOrInterfaceDeclaration> {`

**Comment by DeepSnowNeeL** [comment]
Allright, almost finished the first part of builder methods ! :)
You can now do things like : 

```
MethodDeclaration toString = enumType.addMethod("toString", ModifierSet.PUBLIC);
toString.setType(String.class);
toString.addMarkerAnnotation(Override.class);
toString.createBody().addStatement(new ReturnStmt(ASTHelper.createNameExpr("lib")));
```

And much more! 

Next phase is builder-like methods for all kind of statements, dunno yet how I will do It.

I renamed all the interfaces of node types to keep a standard naming convention so it's not really backward compatible, we might go for a version 3.0 introducing the new way of creating java class programatically ?

I'm open to critics, check my fork (https://github.com/DeepSnowNeeL/javaparser) :)

I'll do tests in the 3rd phase. (I need to learn how your test framework works)

**Comment by DeepSnowNeeL** [comment]
Allright, almost finished the first part of builder methods ! :)
You can now do things like : 
```
MethodDeclaration toString = enumType.addMethod("toString", ModifierSet.PUBLIC);
toString.setType(String.class);
toString.addMarkerAnnotation(Override.class);
toString.createBody().addStatement(new ReturnStmt(ASTHelper.createNameExpr("lib")));
```
And much more, next phase is builder-like methods for all kind of statements, dunno yet how I will do It.

I renamed all the interfaces of node types to keep a standard naming convention.

I'm open to critics, check my fork :)

I'll do tests in the 3rd phase. (I need to learn how your test framework works)

**Comment by matozoid** [comment]
@DeepSnowNeeL - shall we close this one? Do you think there's more work to do?

**Comment by DeepSnowNeeL** [comment]
Well, I think we covered 90% of the uses cases. If we find new helper/builder methods for code generation from scratch to be handy, well we will just PR :)

+1 to close
