### ISSUE TITLE
NameExpr.resolve() does not take end of inner block scopes into account

### ISSUE THREAD

**Issue by ktul** [javaparser/javaparser#3631]
If a variable in a standalone nested scope shadows a field, subsequent references to the field after this scope are wrongly resolved to the variable.
Example:
```java
class InnerScope {
    int x = 0;
    void method() {
        {
            var x = 1;
            System.out.println(x);   // prints 1
        }
        System.out.println(x);       // prints 0
    }
    public static void main(String[] args) {
        new InnerScope().method();
    }
}
```
Resolving the second `NameExpr <x>` provides the `VariableDeclarationExpr <var x = 1>` instead of the `FieldDeclaration <int x = 0;>`.

However, this is not the case when the inner `BlockStmt` is the body of an `IfStmt`:
```java
void method() {
    if (true) {
        var x = 1;
        System.out.println(x);   // prints 1
    }
    System.out.println(x);       // prints 0
}
```
In this case, `NameExpr <x>` is correctly resolved to  `FieldDeclaration <int x = 0;>`.

**Comment by jlerbsc** [comment]
Thank you @ktul for reporting this bug.

**Comment by adrts-iscte** [comment]
I consider this issue to be related to this post. Sorry if not.
I'm using the "com.github.javaparser:javaparser-symbol-solver-core:3.24.4" release.

Considering de following class:

```
class Class {

    int attribute;

    private int method() {
        int value = attribute;
        double attribute = 0.0;
        return (int) (attribute + 1);
    }
}
```

When resolving the line: 
`int value = attribute;`

Setting the JavaParser with the solver as shown in the following code (Kotlin):
```
StaticJavaParser.setConfiguration(ParserConfiguration().setSymbolResolver(JavaSymbolSolver(CombinedTypeSolver())))
```

The NameExpr <attribute> provides the VariableDeclarationExpr <double attribute = 0.0> instead of the FieldDeclaration <int attribute;>.

**Comment by jlerbsc** [comment]
iI's a mistake on my part this fix can't solve this issue.

**Comment by adrts-iscte** [comment]
Sorry, what is PR?

**Comment by jlerbsc** [comment]
This issue seems to be resolved.
