### ISSUE TITLE
TypedNode implies a get/set when NodeWithModifiers(and others) only implies a get

### ISSUE THREAD

**Issue by DeepSnowNeeL** [javaparser/javaparser#372]
TypedNode implies a get/set when NodeWithModifiers only implies a get, shouldn't it implies a set too ? It's the same for NamedNode.

DocumentableNode is a bit different, should we put in here getComment and setComment ? or should we have set every type of comment and get every type of comment > will conflict with the final modifier of Node#setComment

**Comment by matozoid** [comment]
Hmmmmm... My opinion:
- since the setModifiers() methods are already there, they should be in NodeWithModifiers too. True,
- if it is the same for NamedNode, then this too,
- what I think: every node has comments, but only few have JavaDoc. DocumentableNode is especially for JavaDoc. There is no JavaDoc setter right now because it would just call setComment, which I thought might be confusing. I might be wrong there.

I think this is all the result of JavaParser begin used mostly for reading code, not generating.

**Comment by DeepSnowNeeL** [comment]
If only some nodes can contain javadoc comment we should split it in DocumentableNode and JavaDocumentableNode ?
DocumentableNode would contain setLineComment + setBlockComment with getters.
JavaDocumentableNode would contain setJavaDoc and get.. ?

**Comment by DeepSnowNeeL** [comment]
Same for AnnotableNode by the way. 
I intend to refactor a bit those interfaces to expose some builder methods in them (related to #363 )

**Comment by matozoid** [comment]
- DocumentableNode is just JavaDoc. Every Node can have comments, so that doesn't need an interface. Putting normal comments in DocumentableNode would mean making _every_ node a DocumentableNode, which would make it meaningless.

**Comment by matozoid** [comment]
AnnotableNode seems like a good target for an extra setter.

**Comment by matozoid** [comment]
Be careful to remain backwards compatible. We can break stuff when we go to 3.0 :)

**Comment by DeepSnowNeeL** [comment]
I think that changing interfaces wouldn't interefere with the parsing nor
the usage of the lib, it should be only internal stuff and addditions. I'll
take care :)

Le ven. 15 juil. 2016 11:06, Danny van Bruggen notifications@github.com a
écrit :

**Comment by matozoid** [comment]
@DeepSnowNeeL is this done?

**Comment by DeepSnowNeeL** [comment]
Yep it was included in my first builder PR :)
