### ISSUE TITLE
Issue with interface modifiers

### ISSUE THREAD

**Issue by fmbenhassine** [javaparser/javaparser#379]
Hi,

First, thank you for this wonderful project!

Looks like JavaParser is not correctly parsing interface modifiers. Here is the test:

``` java
import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.TypeDeclaration;
import org.assertj.core.api.Assertions;
import org.junit.Test;

import java.io.StringReader;
import java.lang.reflect.Modifier;
import java.util.List;

public class JavaParserTest {

    @Test
    public void testInterfaceModifiersWithJavaParser() throws Exception {
        CompilationUnit compilationUnit = JavaParser.parse(new StringReader("public interface Foo {}"), false);
        List<TypeDeclaration> types = compilationUnit.getTypes();

        Assertions.assertThat(types).hasSize(1); // OK

        TypeDeclaration typeDeclaration = types.get(0);
        Assertions.assertThat(typeDeclaration.getName()).isEqualTo("Foo"); // OK

        int modifiers = typeDeclaration.getModifiers();
        Assertions.assertThat(Modifier.isInterface(modifiers)).isTrue(); // KO
    }

    @Test
    public void testInterfaceModifiersWithReflectionApi() throws Exception {
        int modifiers = Foo.class.getModifiers();
        Assertions.assertThat(Modifier.isInterface(modifiers)).isTrue(); // OK
    }

    public interface Foo {}
}
```

Getting modifiers through the Java reflection API is fine, I'm expecting `Foo` to be an interface. With JavaParser this is not the case. Is this a bug or Am I missing something?

I'm using java version 1.8.0_73 and java-parser version 2.4.0

Thank you for your help.
Kind regards

**Comment by matozoid** [comment]
Thanks for the compliments from the whole team :)

The problem here is a mixing of API's and lacking documentation. JavaParser has no overlap with the Java reflection API. Therefore, java.lang.reflect.Modifier will not work right. (Actually, it will in all cases except interface, but that's an implementation detail.)

This is the JavaParser way to check if a type is an interface:
`((ClassOrInterfaceDeclaration)typeDeclaration).isInterface();`

This is the JavaParser way to check modifiers:
`ModifierSet.isPublic(modifiers)`

I've added #381 so this mistake can be avoided in the future.

**Comment by fmbenhassine** [comment]
Great. Thank you for your help!
