### ISSUE TITLE
Book no longer available for free on LeanPub

### ISSUE THREAD

**Issue by brodmo** [javaparser/javaparser#3889]
Apparently the book used to be available for free [here](https://leanpub.com/javaparservisited), but it no longer is unless you have a membership to LeanPub. Are there any plans to make the book publicly available again? Since there is little other documentation it's really annoying to use this project without it.

**Comment by jlerbsc** [comment]
We need to ask the authors. @matozoid this is not the first request of this type, do you have a solution?

**Comment by jlerbsc** [comment]
The writing of this book has certainly taken a long time, it is normal that the authors are rewarded for this effort. It is also their prerogative to publish this book free of charge if they agree with your suggestion. For now I am closing this issue.

**Comment by mytlogos** [comment]
The main problem is *not* that it is *not free of charge*, *but* that it *is advertised as free of charge*, while it currently is not.
So either the homepage should change it, or make it free of charge again.
Currently the homepage is misleading every visitor:
![grafik](https://user-images.githubusercontent.com/29383271/236778062-8b2299f2-ea82-4a76-9e4f-379217126d47.png)

**Comment by jlerbsc** [comment]
These are the terms of use of the leanpub site that have changed but the book itself can be free of charge.

**Comment by mytlogos** [comment]
But it is not currently available free of charge.

EDIT: It does not matter who is charging.

**Comment by jlerbsc** [comment]
You have just to subscribe to leanpub, but it's free.

![image](https://user-images.githubusercontent.com/5850581/236793629-2d89bafb-b31b-433e-9390-7405b74eb933.png)

**Comment by mytlogos** [comment]
Yeah, but no.
It is "free" behind a paywall.

**Comment by mytlogos** [comment]
I know we could discuss the meaning of "free" in this context for a long time, but i just want to state my opinion, that currently the homepage is *misleading in a sense*.
Yeah the ebook is free, but behind a paywall not managed by the author.

You could add a disclaimer with a star \*, which states just this, say it is free on leanpub (this indicates that it is dependant on the ToS of leanpub itself, while still being free in itself), just say `Get the book` (remove the "free"), move it somewhere else where it is not behind a paywall (not managed by the author), make it (also) completely free (e.g. pdf on github), while maybe still retaining the leanpub way for providing a way for users to be able to pay, or just ignore this problematic situation and maintain the status quo.

It is just my personal opinion, but i think the author should make a decision (he most likely did it already, by ignoring this thus far, if he even knows about it) and maybe even make a public statement, so that other users are not confused by this.

Thanks for your time thus far.

EDIT: edited `move it somewhere else where it is behind a paywall (not managed by the author),` to `move it somewhere else where it is not behind a paywall (not managed by the author),`

**Comment by brodmo** [comment]
I was about to chime in that an open-source project's documentation really should be freely available, but it looks like something changed at LeanPub again and you can once more download the book for free without a subscription.
