### ISSUE TITLE
Consider adding a lenient mode

### ISSUE THREAD

**Issue by NebelNidas** [javaparser/javaparser#3999]
Currently, JavaParser is extremely strict and fails immediately when it encounters not 100%-compliant Java code. In many use-cases (like when parsing decompiled code), this behavior is undesirable and should be made optional. This includes rules like `super` constructor calls not being in the first line of a subclass's constructor, or inner classes' names starting with numbers.

**Comment by jlerbsc** [comment]
It is a choice that was certainly made when the project was developed. It seems to me very difficult to modify this choice today. Besides, I don't know all the implications of a less strict parsing. To my knowledge it is indeed a pre-requisite to use JavaParser.

**Comment by revusky** [comment]
Well, the reason that JavaParser cannot be fault-tolerant is that it is built using the legacy JavaCC parser generator, which has zero concept of fault tolerance or error recovery. There is a (vastly) more advanced version of JavaCC, [CongoCC](https://github.com/congo-cc/congo-parser-generator) that can generate fault-tolerant parsers. You can read the key information about how this works [here](https://parsers.org/javacc21/the-promised-land-fault-tolerant-parsing/).

I doubt this is the appropriate venue to be discussing this, however. If anybody wants to ask anything about this topic, I would suggest that they post questions or comments on the [CongoCC discussion forum](https://discuss.congocc.org/). That would be my preference, but I'm hardly picky. I guess you could use the built-in issue tracker or discussions feature that is part of git-hub. (But obviously, I mean the ones that are associated with the [Congo parser generator project](https://github.com/congo-cc/congo-parser-generator/).

**Comment by AqilNumber1** [comment]
Hi, I am trying to work on some sort of solution for this issue

**Comment by jlerbsc** [comment]
This subject is too sensitive to be handled by someone who does not have very good knowledge of the JP project.

**Comment by AqilNumber1** [comment]
> This subject is too sensitive to be handled by someone who does not have very good knowledge of the JP project.

Thanks for the heads up on the difficulty. Although I understand I may not create a proper full solution, I am still interested in exploring this problem to strengthen my knowledge on this project :)

**Comment by revusky** [comment]
> This subject is too sensitive to be handled by someone who does not have very good knowledge of the JP project.

As I said in a previous comment, there is simply no prospect of JavaParser having much in the way of fault-tolerant parsing capabilities. This is because it is built on top of a very old parser generator (JavaCC) that itself has zero concept of fault-tolerant parsing, i.e. error recovery or backtracking. 

There is a more advanced version of JavaCC, which is mostly my work, [CongoCC](https://github.com/congo-cc/congo-parser-generator), that has been refactored to allow the generation of fault-tolerant parsers. You can see [here](https://parsers.org/javacc21/the-promised-land-fault-tolerant-parsing/) that the bulk of the work on this problem has been done for a couple of years now. I am very interested in attracting collaborators who are interested in this problem.

Well, if anybody wants to discuss this with me, maybe the best thing is to start a discussion [here](https://github.com/congo-cc/congo-parser-generator/discussions) or [here](https://discuss.congocc.org).

**Comment by jlerbsc** [comment]
Please promote your project on another forum.

**Comment by revusky** [comment]
> Please promote your project on another forum.

Well, you please behave like an adult.

Let me ask you this question:

*Why should people be saddled with inferior, obsolete tools because people like you want to hide that there are more advanced tools available?*

Is that a very nice thing to do to people? What I answered is simply factual. There is no real prospect of this project, JavaParser, being able to support fault-tolerant parsing because it is built using an obsolete tool, legacy JavaCC, that has ZERO support for this! Why should I not tell people this? Particularly when you decline to tell people this.

Another question for you:

*Is there the slightest intention on the part of this "community" to do any work at all on the problem of fault-tolerant parsing?*

It's a rhetorical question. I'm pretty sure the answer is no. If you don't intend to address a problem, why should I not tell people that the problem is addressed elsewhere?

I really think it's time for people like you, you and the other people in this JavaParser project, to start behaving like adults. Is that too much to ask for? (*Unfortunately, it probably is...*)

**Comment by NebelNidas** [comment]
Personally I'm going to go with [OpenRewrite](https://github.com/openrewrite/rewrite) for now. It's far less bloated than e.g. Eclipse JDT, has pretty much all of JavaParser's features and has the additional benefit of being more fault-tolerant. I haven't looked too deep into its internals yet, but maybe the JP team can take some inspiration from the project?

**Comment by jlerbsc** [comment]
Alright so I can close this issue.
