### ISSUE TITLE
Javadoc is put below annotation then could not get comment!

### ISSUE THREAD

**Issue by tlttnz2018** [javaparser/javaparser#40]
## I try to use javaparser to get the comment from this method but it's always null. It's will be ok if the comment first then annotations.

```
@GET
@Path("/original")
/**
 * Return the original user.
 */
public User getOriginalUser(String userName) {
    return userService.getOriginalUser(userName);
}
```

---

**Comment by SmiddyPence** [comment]
I can pick this up.  

Not sure I approve of the style, but legal none the less...

**Comment by SmiddyPence** [comment]
Interesting one.  
The comment is assigned to the return type, in this case User.  So the User node holds the comment.
It behaves the same as the following would.

```
@GET
@Path("/original")
public /* original user */ User getOriginalUser(String userName) {
    return userService.getOriginalUser(userName);
}
```

Essentially the `beginLine` number for a MethodDeclaration is determined by its first annotation. So it is inferring from the line numbers that the comment belongs to a child node of the method rather than the method itself, (as a preceding comment would).  User is then the first comment-able node.

I can craft something to assign the comment to the method instead, but I’m not entirely uncomfortable with the present behavior.  

What does the group think?

**Comment by ftomassetti** [comment]
Well, if I remember correctly I wrote that logic, so it seems fine to me :D
I guess that attribute comments is art more than science: there is not precise semantic, we relay just on conventions and typically a block comment applies to the first entire node following it.
I suppose we could try to add logic specific for some corner cases but it is open to interpretation: a comment in that position could be related to the public modifier, maybe it explains the reason to make that method public instead of private. Or it could explain why that return type was chosen.
However I understand that probably it refers to the method, so in such a case in which more interpretations are possible we could assign it to the method. But how could we write this rule? Should we consider that certain elements (i.e., annotations) are sort-of-external, therefore they do not really mark the beginning of the node and as consequence comments in that position should be applied to the method because it, after all, start at the public keyword instead that at the first annotation?

**Comment by SmiddyPence** [comment]
I agree, I think current behaviour a sensible outcome.

I think due to the ambiguity it is probably worth a documentation section for the comment parsing.  So people know what to expect.

**Comment by ftomassetti** [comment]
Ok, then I wil first focus on providing documentation (issue #49 ) and later, possibly consider the particular case of annotations (to close this issue).

**Comment by ftomassetti** [comment]
Ok, now there is an option also for considering this case. I think the current behavior is the most reasonable, but if a user think otherwise it can use this option. See these examples:

``` java
   @Test
    public void testIssue40CommentsAfterJavadocAreAttributedToTheMethodIfFlagIsActive() throws Exception {
        String source = "class A{\n"+
                        "  @GET\n" +
                        "  @Path(\"/original\")\n" +
                        "  /**\n" +
                        "   * Return the original user.\n" +
                        "   */\n" +
                        "  public User getOriginalUser(String userName) {\n" +
                        "      return userService.getOriginalUser(userName);\n" +
                        "  }\n"+
                        "}";
        JavaParser.setDoNotConsiderAnnotationsAsNodeStartForCodeAttribution(true);
        try {
            CompilationUnit cu = Helper.parserString(source);
            assertEquals(1, cu.getAllContainedComments().size());
            Comment comment = cu.getAllContainedComments().get(0);
            assertFalse(comment.isOrphan());
            assertTrue(comment.getCommentedNode() instanceof MethodDeclaration);
        } finally {
            JavaParser.setDoNotConsiderAnnotationsAsNodeStartForCodeAttribution(false);
        }
    }

    @Test
    public void testIssue40CommentsAfterJavadocAreAttributedToTheMethodIfFlagIsNotActive() throws Exception {
        String source = "class A{\n"+
                "  @GET\n" +
                "  @Path(\"/original\")\n" +
                "  /**\n" +
                "   * Return the original user.\n" +
                "   */\n" +
                "  public User getOriginalUser(String userName) {\n" +
                "      return userService.getOriginalUser(userName);\n" +
                "  }\n"+
                "}";
        JavaParser.setDoNotConsiderAnnotationsAsNodeStartForCodeAttribution(false);
        CompilationUnit cu = Helper.parserString(source);
        assertEquals(1, cu.getAllContainedComments().size());
        Comment comment = cu.getAllContainedComments().get(0);
        assertFalse(comment.isOrphan());
        assertTrue(comment.getCommentedNode() instanceof Type);
    }
```
