### ISSUE TITLE
After building JavaParser (with tests) on MacOS multiple committed files are modified

### ISSUE THREAD

**Issue by abego** [javaparser/javaparser#4077]
When doing a `mvn clean install` of JavaParser on MacOS multiple committed files are modified:
<img width="940" alt="Screenshot 2023-06-22 at 21 59 24" src="https://github.com/javaparser/javaparser/assets/696535/af28c114-ffea-44e4-96f7-26f155124521">

The difference is in the line endings: the files are committed with `"\r\n"` line endings, but after running the tests on MacOS the files have `"\n"` line endings.

Having those files modified is annoying when developing JavaParser code as one always have to rollback those changes or explicitly exclude those files before commiting changes.

_(From what I can tell the files are modified in the `SourceRootTest`, by the test methods `saveInCallback()` and `saveInCallbackParallelized()`.)_

**Comment by jlerbsc** [comment]
After analysis, the cause of this problem comes mainly from the SourceRoot class which uses printing configuration parameters with default values. The default end-of-line character is system-specific (on Windows it's CRLF...). This only raises a problem when this class is asked to parse and save the result, which is done in particular by the SourceRootTest test class. In this case, ideally, one should use the end-of-line character used in the parsed file.
