### ISSUE TITLE
Leaving out comments

### ISSUE THREAD

**Issue by tburmann** [javaparser/javaparser#415]
When i have a parsed methode that contains a for- loop with a comment, then i get the comment within the for- loop when i print it. Is
there a way to get the for loop (or controll structures in general) without any comments even if comments are in the source code?

**Comment by MysterAitch** [comment]
Presumably this old issue can be closed given that the pretty printer has a configuration option `setPrintComments(false)`?

**Comment by matozoid** [comment]
A more specific answer would be: use a visitor to find the nodes you don't want comments for, then use a walk or find method to go through all of its methods and remove their comments. And if you don't really want to remove comments, clone the whole AST first and work on the clone.

But yes, then it can be closed :-) (Lots of comment support issues are long open because it's hard to do it right, and not enough time has been spent on that yet.)
