### ISSUE TITLE
OpenRewrite

### ISSUE THREAD

**Issue by JLLeitschuh** [javaparser/javaparser#4268]
Hi JavaParser Team,

I just wanted to make you aware of a similar-yet-different tool called OpenRewrite that can be used to refactor code at-scale across your entire organization using format preserving LST manipulations.

https://github.com/openrewrite/rewrite

I've, personally, been using OpenRewrite to automate fixing widespread common security vulnerabilities at-scale across hundreds-to-thousands of OSS projects.

I've given a few talks about the work as well:
https://github.com/jlleitschuh#scaling-the-security-researcher-to-eliminate-oss-vulnerabilities-once-and-for-all

**Comment by jlerbsc** [comment]
Hello Thank you for the information. Yes indeed we know this project but Javaparser is positioned more as a tool allowing you to introspect the source code and its dependencies. The 2 tools are absolutely not comparable because they do not aim for the same objectives. I'm also not sure that OpenRewrite has a component equivalent to the Symbol solver.

**Comment by jlerbsc** [comment]
I am closing this issue because it does not report any problem on Javaparser.
