### ISSUE TITLE
Problem while retrieving field value using VariableDeclarator

### ISSUE THREAD

**Issue by soulcarta** [javaparser/javaparser#43]
I'm using VariableDeclarator for retrieving field's init value

``` java
List<VariableDeclarator> variables = fieldDeclaration.getVariables();
for (VariableDeclarator variableDeclarator : variables) {                   
    VariableDeclaratorId fieldName = variableDeclarator.getId();
    Expression fieldValue = variableDeclarator.getInit();
    ...
```

There is a problem.
See the code below. First Case is No problem. 
But In second Case, "variableDeclarator.getInit()" returns "//field2 null"
In other word,  "variableDeclarator.getInit()" returns value include line comment

``` java
//Case 1
private String field1 = null; //field1

//Case 2
private String field2 
                    = null; //field2
```

How Can I retrieve or parse only field value without comment?

**Comment by ftomassetti** [comment]
I cannot reproduce this issue, but I added a test for it. What I supposed happened is that the comment // field 2 was attributed to the expression initializing the field (null). I think this is correct, because a line comment should be attached to the element to is left, in this case the expression null.
Maybe the way it printed it was misleading, but you should not rely on toString, I suppose.

I would finish the test about this issue and leave this issue open for further comments.

**Comment by ftomassetti** [comment]
We recently wrote more tests and documented comments parsing, moreover I cannot reproduce this issue and there were no further comments so I will close this issue. Feel free to re-open it if needed!
