### ISSUE TITLE
Parsing JavaDoc

### ISSUE THREAD

**Issue by chmuche** [javaparser/javaparser#433]
If possible to improve the parsing of a javaDoc comment Block, by adding javaDoc annotation like @return, @param ... .
I think is the last missing things to javaparser.
In the same idea, add some methode to the Generic comment like  isTodoComment() and method like that.
I will try to create a little POC if you think this feature is interesting

**Comment by matozoid** [comment]
Go ahead, create a PR and we'll take a look!

**Comment by matozoid** [comment]
@chmuche are you making any progress on this? I'm curious :-)

**Comment by matozoid** [comment]
Taking this out of 3.0 since it doesn't need to break the API.

**Comment by ftomassetti** [comment]
I think this is something we should prioritize.
I wanted to write a brief post on JavaParser & JavaDoc: maybe this is a good excuse to start working on this one. I will steal the ticket.

For me the easiest way would be to use ANTLR, but that would mean adding dependencies so I will take a look at JavaCC instead. I am not sure the JavaCC mvn plugin can handle two grammars in the same project. Going to figure that out.

**Comment by matozoid** [comment]
Here is my branch where I was making a half-hearted attempt by converting an ANTLR grammar: https://github.com/matozoid/javaparser/tree/issue_433_javadoc_parser

My experience up to now:
- the parser has to be whitespace aware to deal with the *'s at the start of lines
- it's best to consider the first "* @..." combination to end the text part of the javadoc
- it's beyond my knowledge to get our current grammar to do JavaDoc parsing, since it has to jump from normal parsing to comment parsing to normal javadoc parsing
- you have to balance how specific you want to parse the key-value tags. Probably simply parsing everything into a `Map<String,String>` is best, to avoid another "four importdeclarations" mess up.
- you have to consider the same thing for tags in the description text
- since we get a second grammar, we have to consider where that grammar gets triggered. At least a method on JavaParser, but maybe a method on NodeWithJavadoc too. Or will it be implicit when you ask for Javadoc? Or do we put the parsing in JavadocComment?

Having two grammars is easy to do.

Better not do ANTLR since one of our strengths is not having any dependencies.

**Comment by ftomassetti** [comment]
Mmm, I tried building a second JavaCC parser but it seems overkilling. ANTLR is so much easier than JavaCC, but I agree it does not make sense to introduce a dependency.

I would try go for a manual parser

**Comment by ftomassetti** [comment]
Ok, a manual parser seems feasible and simple enough. I started implementing it and then I will adjust after reading this definition:

> The resulting HTML from running Javadoc is shown below
Each line above is indented to align with the code below the comment.
The first line contains the begin-comment delimiter ( /**).
Starting with Javadoc 1.4, the leading asterisks are optional.
Write the first sentence as a short summary of the method, as Javadoc automatically places it in the method summary table (and index).
Notice the inline tag {@link URL}, which converts to an HTML hyperlink pointing to the documentation for the URL class. This inline tag can be used anywhere that a comment can be written, such as in the text following block tags.
If you have more than one paragraph in the doc comment, separate the paragraphs with a <p> paragraph tag, as shown.
Insert a blank comment line between the description and the list of tags, as shown.
The first line that begins with an "@" character ends the description. There is only one description block per doc comment; you cannot continue the description following block tags.
The last line contains the end-comment delimiter ( */) Note that unlike the begin-comment delimiter, the end-comment contains only a single asterisk.
For more examples, see Simple Examples.

source: [http://www.oracle.com/technetwork/articles/java/index-137868.html](http://www.oracle.com/technetwork/articles/java/index-137868.html)

**Comment by ftomassetti** [comment]
So we have a description, which can contain inline tags. It is followed by block tags.
Note that the param block tag is different from others because it has a name

**Comment by matozoid** [comment]
Alright, remember to be gentle when parsing, since we have a validation framework planned that can report semantic problems nicely (tags without content, @param for non-existing parameter, @see that does not point to a class...)

I was going for a JavaCC parser because I figured it would be faster than anything I can write.

**Comment by matozoid** [comment]
Oh, one worry when you're writing a manual parser: remember the tables we have in the grammar for letters, whitespace, etc. Please don't be inconsistent with that, it will lead to annoying bug reports.

**Comment by ftomassetti** [comment]
Which tables?

**Comment by matozoid** [comment]
Check #LETTER for example. Not sure it's relevant though...

Here's someone else's attempt, btw: https://github.com/javaparser/javaparser/pull/475
