### ISSUE TITLE
DefaultPrettyPrinter issue with comment above else if statement

### ISSUE THREAD

**Issue by bruce-ren-sp** [javaparser/javaparser#4352]
Hi team,

I want to report an issue (most likely a defect) related to DefaultPrettyPrinter.  When a java class contains the following snippet of code:

          if (condition) {
             <<code>>
          }
          //some comments
          else if (condition) {
             <<code>>
          }

the print output from DefaultPrettyPrinter (printComments is set as true via config) displays as below:

          if (condition) {
             <<code>>         
          }
          else //some comments
          if (condition) {
              <<code>>
          }

I found this issue in the initial version (3.18) I used in my code. I tested the latest version (3.25.5) and found it has the same issue as well. Please let me know if you want me to provide more information.

Thanks,
Bruce

**Comment by SmiddyPence** [comment]
Hi Bruce 

Apologies for the delayed response, this repository is for the materials in the book (checked rarely). I'll transfer the issue over to the main repo, so people can take a look and get back to you.

Thanks

**Comment by jlerbsc** [comment]
Hi Bruce,

The behaviour you are reporting matches the default printer operation. The comment is assigned to the IF statement and printed before the statement. If you want to preserve the formatted code, you need to use the LexicalPreservingPrinter.

**Comment by bruce-ren-sp** [comment]
hi @jlerbsc,

Thanks for looking at this! In this case, the comment is actually assigned to "ELSE IF" statement, but printed out between "ELSE" and "IF".  

Regards,
Bruce

**Comment by jlerbsc** [comment]
Hi @bruce-ren-sp ,

From the point of view of the AST there is no 'else' or 'else if' node, there is an 'if' node which is a child of the 'else' expression.
The comment is usually associated with the first following node (i.e. the 'if' node). In the case of the printer you're using, because the first 'if' contains an 'else' expression, the 'else' keyword is printed and then the node contained in this expression is printed, starting with the associated comment. This is how this printer works. 

If you don't like the way it works, you need to use the lexical preservation printer.

**Comment by jlerbsc** [comment]
I'm closing this issue because we've answered the question and there don't seem to be any other questions.
