### ISSUE TITLE
Question about switch statements and pattern representation

### ISSUE THREAD

**Issue by johannescoetzee** [javaparser/javaparser#4361]
Related to https://github.com/javaparser/javaparser/issues/4343 and https://github.com/javaparser/javaparser/issues/4217

Java 21 extends patterns in 2 ways that affect patterns directly (relevant syntax shown with some alternatives omitted for brevity):

### Patterns in switch statments can now include guard
```
SwitchLabel:
  case CaseConstant { , CaseConstant }
  case CasePattern [ Guard ]
  case null [ , default ]

CasePattern:
  Pattern

Guard:
  when Expression
```

### Record Patterns
```
Pattern:
  TypePattern
  RecordPattern

TypePattern:
  LocalVariableDeclaration

RecordPattern:
  ReferenceType ( [ PatternList ] )

PatternList : 
  Pattern { , Pattern }
```

### Current state

**Patterns:** JavaParser currently only supports `TypePatterns` in `instanceof` expressions and represents these with a `PatternExpr`. 

**Switch labels:** Switch labels are represented as a list of `Expressions` in the corresponding `SwitchEntry`

#### 1. Switch patterns

Since switch labels are currently represented as a single `Expression` per label, I think the best solution in this case is to add a
```java
class SwitchPattern {
	Pattern pattern; // Using Pattern here, since this could also be a record pattern
	Expression guard;
}
```
class to group these. The other option would be to add an `Optional<Expression> guard` to all patterns and then have it be empty
for all non-switch patterns.

Another syntax change to consider is the `case null [ , default ]` case. Currently, we can tell if a `SwitchEntry` is the default
case by checking if the label list is empty, but with the option of having a shared null/default case, this would no longer be 
true. The best solution I can think of for this is to add an `isDefault` field to `SwitchEntry` that will always be set in the 
empty label case (meaning you can use either the empty label list or `isDefault` to determine whether the entry is a default), 
and will also be set in the shared `null/default` case (in which case the empty label list check will return an incorrect result).

The other option I considered is to add some sort of `DefaultExpr` as a placeholder, but I think that causes more trouble than it's worth.

#### 2. Record patterns

This is the trickier change of the two. The ideal case would be to split `PatternExpr` into 2 separate classes: `TypePatternExpr` and 
`RecordPatternExpr`, both implementing a `PatternExpr` interface/base class for generics. This would be a rather large change for 
anyone currently using `PatternExpr`, so an alternative could be to keep `PatternExpr` as the representation for `TypePattern` and to 
use something like `Pattern` as a common base for that and `RecordPatternExpr`.

An option that avoids having two pattern classes for the different types would be to use `PatternExpr` for both types of patterns.
To do this, we could add a `NodeList<PatternExpr> patterns` field to `PatternExpr`, which would be empty if the pattern is a `TypePattern`
and set to the patterns in the `PatternList` otherwise. We would then also have to change the `name` field of `PatternExpr` to 
`Optional<SimpleName>` and set it to empty if the `PatternExpr` is a `RecordPattern`.

**Comment by johannescoetzee** [comment]
Looking at https://github.com/javaparser/javaparser/pull/4357, adding the `guard` as a field in the `SwitchEntry` is also an option and does avoid an extra `SwitchPattern` class. Using that along with the last idea I mentioned for record patterns means we could do this without having to add any new node types, at the cost of overloading `PatternExpr` somewhat.

**Comment by binis2** [comment]
When https://openjdk.org/jeps/440 is implemented I beleive that we will end up with RecordPatternExpr class naturally.
Now adding PatternExpr that is identical to VariableDeclarationExpr? I'm indifferent.

**Comment by jlerbsc** [comment]
Thank you for your very interesting analysis, which is worth taking a step back from. In the meantime, could you group your comments together to simplify overall understanding.

Generally speaking, I'm in favour of dealing with subjects one after the other and in the direction of the versions. I'm also in favour of trying to match JLS concepts with the configuration of the parser (java.jj). On the other hand, I'm not in favour of integrating preview features too early or even introducing support for preview versions as has been done in the past. Today JavaParser is very late, so it's preferable to concentrate first on the finalised features.

There are a lot of JP features that I haven't mastered because they were handled by people who were more experienced in these areas. These people are no longer contributing to the project, which is why support for the new features has been delayed.

There are several areas of reflection in JP:
- in the 'core' part: the parser (javaCC), code generation, printers (default and LexicalPreservingPrinter 'LPP');
- in the symbol solver part: in particular, there are 3 symbol solving mechanisms (from source code, by reflection, and via javassist).This is certainly the most complex part of the project and the one with the most bugs.

Moving forward with a new feature without ensuring that it is supported by the symbol solver opens the door to even more issues. So you'll understand that I'm not in favour of this approach.

**Comment by johannescoetzee** [comment]
I'm closing this in favour of https://github.com/javaparser/javaparser/issues/4385 since that covers the record pattern aspect of this PR while the switch pattern aspect has already been merged in the referencing PRs.
