### ISSUE TITLE
Cloned VariableDeclarator is still somehow connected to original or to source

### ISSUE THREAD

**Issue by Artur-** [javaparser/javaparser#4476]
If I parse a class like
```
public class TestClass extends Div {
  private NativeButton hello;
  public TestClass() {
    hello = new NativeButton("Hello");
    add(hello);
  }
}
```

using  a `LexicalPreservingPrinter`
```
compilationUnit = LexicalPreservingPrinter
                .setup(StaticJavaParser.parse(source));
```

and fetch the FieldDeclaration for "hello", clone it, add it and set its name to "hello2" then the output of `LexicalPreservingPrinter.print(compilationUnit)` is
```
public class TestClass extends Div {
  private NativeButton hello;
  private NativeButton hello;
...
```
even though `toString()` for the new `FieldDeclaration` is `private NativeButton hello2`

If I instead of using `clone()` manually create a new `FieldDeclaration` and use a new `VariableDeclarator`, then the output is the expected
```
public class TestClass extends Div {
  private NativeButton hello;
  private NativeButton hello2;
...
```

Seems in fact that clearing all `data` for the `VariableDeclarator` after a clone() is enough to make it work

**Comment by jlerbsc** [comment]
Provide us with a complete test case, as this may be due to the way you implement your case.

**Comment by Artur-** [comment]
```
 ParserConfiguration parserConfiguration = new ParserConfiguration();
        parserConfiguration
                .setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_17);
        StaticJavaParser.setConfiguration(parserConfiguration);
        CompilationUnit compilationUnit = LexicalPreservingPrinter
                .setup(StaticJavaParser.parse("""
                        public class TestClass extends Div {
                          private NativeButton hello;
                          public TestClass() {
                            hello = new NativeButton("Hello");
                            add(hello);
                          }
                        }
                        """));

        System.out.println("Parsed");
        System.out.println(LexicalPreservingPrinter.print(compilationUnit));

        FieldDeclaration fieldDeclaration = compilationUnit.findFirst(FieldDeclaration.class).get();
        ClassOrInterfaceDeclaration testClass = compilationUnit.findFirst(ClassOrInterfaceDeclaration.class).get();
        FieldDeclaration newField = fieldDeclaration.clone();
        VariableDeclarator variable = newField.getVariable(0);
        variable.setName("hello2");

        testClass.addMember(newField);

        System.out.println("Modified");
        System.out.println(LexicalPreservingPrinter.print(compilationUnit));

        System.out.println("newField");
        System.out.println(newField);
```

**Comment by jlerbsc** [comment]
What you need to do is add the new field to the AST and then modify it.

It is difficult to describe exactly what happens, but here is an attempt. 

When you add the node to the AST, LPP internally initializes the representation of the node (a list of tokens) and then when you modify a node in the AST, LPP uses a mechanism to detect the change and apply the modifications to the internal representation of the node. In your case the internal representation has been cloned and at this stage LPP does not support updating the list of tokens representing the node. Then when you add the new node to the AST, the mechanism that manages the internal representation is not triggered either because there are no changes to the node. When printed, it is the internal representation (the list of tokens) which is displayed.



    FieldDeclaration newField = fieldDeclaration.clone();
    testClass.addMember(newField);
    VariableDeclarator variable = newField.getVariable(0);
    variable.setName("hello2");

**Comment by jlerbsc** [comment]
I'm closing this exit because I think we've answered your question.

**Comment by Artur-** [comment]
Thanks, now I get why it did not work. However, would it be an equally good/safe workaround to clear `data` recursively for the cloned components after cloning a detached node?

**Comment by jlerbsc** [comment]
It's not a workaround, that's how JP works.

**Comment by Artur-** [comment]
Then I am no longer sure I understand. If I take my example code and add

```
clearData(newField);
```

defined as
```
    private static void clearData(Node node) {
        HashSet<DataKey<?>> dataKeys = new HashSet<>(node.getDataKeys());
        dataKeys.forEach(node::removeData);
        for (Node child : node.getChildNodes()) {
            clearData(child);
        }
    }
```


before
```
System.out.println(LexicalPreservingPrinter.print(compilationUnit));
```

then the output will be the expected
```
public class TestClass extends Div {
  private NativeButton hello;
  public TestClass() {
    hello = new NativeButton("Hello");
    add(hello);
  }
  
  private NativeButton hello2;
}
```

**Comment by jlerbsc** [comment]
That's what I'm trying to explain to you "Then when you add the new node to the AST, the mechanism that manages the internal representation is not triggered either because there are no changes to the node. When printed, it is the internal representation (the list of tokens) which is displayed.". But if you delete the lexical representation, LPP tries to rebuild it as if you were adding a node to the AST.
