### ISSUE TITLE
Remove "data" field from Node

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#456]
This field is meant as a place where the user can put additional stuff in a node for own use.

I have never heard of anybody using it, and I would suggest keeping track of data like this in a separate Map<Node, UserObject> so it becomes well typed.

If you feel that this field must remain, say so below.

**Comment by ftomassetti** [comment]
+1 for removing it

**Comment by ptitjes** [comment]
It is often useful (and it is common practice) to attach data directly to the AST while type-checking it, etc...
If you want to attach typed information instead of just an object, there are other means like:

```
interface TypedDataKey<T>{}
```

Have your data field like:

```
private Map<TypedDataKey<?>, Object> data;
```

Document that users should use constants to implement the TypedDataKey and use an IdentityHashMap, and also enforce typing and casting in the accessors. (See Wicket for an example of this pattern.)
