### ISSUE TITLE
Remove support for illegal syntax: array brackets after a method parameter list.

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#458]
See #237

**Comment by ftomassetti** [comment]
I think to remember I saw this and I thought it was an error but later I found it was some weird syntax that is actually legal but not used since Java 1.0...

I am not sure if this was the relevant bit but in JLS 8.4 it shows _Dims_ as part of the method declarator: https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-MethodDeclaration

And if you write this class in IntelliJ it is happy about it:

``` java
public class foo {
    int bar()[] {
        return new int[]{};
    }
}
```

**Comment by ftomassetti** [comment]
So I think it is absurd and never used by anyone with a sound mind but it is technically legal...

**Comment by ftomassetti** [comment]
And related to do: you can also write the brackets after the name of a parameter:

```
int bar(int g[])[] { return g; }
```

**Comment by matozoid** [comment]
Related to do? You mean that's not supported by JavaParser?

As for the current issue: I guess this can be closed again then.

**Comment by ftomassetti** [comment]
I meant that it is another weird piece of syntax involving brackets in unexpected positions. I am not sure it is support by JavaParser, I guess we should check that.

**Comment by matozoid** [comment]
`int[]bar(int[]x[])[]{return new int[][]{};` AAARGH

**Comment by matozoid** [comment]
Okay, JavaParser parses the following, so I'm closing this.

`class I{int[]bar(int[]x[])[]{return new int[][]{};}}`
