### ISSUE TITLE
Bug in parsing multiple line comments

### ISSUE THREAD

**Issue by magicwerk** [javaparser/javaparser#498]
If I parse Java code containing mulitple line comments, only the last line comment is parsed.
If you run the attached snippet, the parsed source contains only "line 3", but "line 1" and "line 2" are missing.
This bug seems to be present in all versions up to 3.0.0-alpha.4.

```
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.visitor.DumpVisitor;

public class ShowBug {

    public static void main(String[] args) {
        String src =
                "public class TestDumpVisitor {\r\n" +
                "\r\n" +
                "   public boolean test() {\r\n" +
                "       // line 1\r\n" +
                "       // line 2\r\n" +
                "       // line 3\r\n" +
                "       return false;\r\n" +
                "   }\r\n" +
                "}\r\n" +
                "";

        CompilationUnit cu = JavaParserTools.getCompilationUnit(src);
        DumpVisitor dv = new DumpVisitor();
        cu.accept(dv, null);
        String dumpSrc = dv.getSource();

        System.out.println("Original:");
        System.out.println(src);
        System.out.println("Parsed:");
        System.out.println(dumpSrc);
    }
}
```

`

**Comment by matozoid** [comment]
A rewrite of the comment functionality is on the agenda for one of the following releases, we'll check this one too, then.

**Comment by matozoid** [comment]
@magicwerk can you tell me what your use case is? I'm planning to support only a single comment per node, so if there is a good reason to support multiple comments in a row, I should stop this plan :)

**Comment by magicwerk** [comment]
I use Javaparser for parsing existing source code and then create modified versions according to templates. Clearly it is a requirement that the creates sources change only if needed and no other content gets lost (even if just comments).

Irrespective of my use case I think it should be a requirement that roundtripping should be possible, i.e. you can parse and dump source without loss of information (besides formatting may be, but in the ideal case the line/character positions stored would be honored by the DumpVisitor).

I think this also a requirement for a tool like WalkMod which bases on Javaparser.

Hope I could convince you!
Thomas

**Comment by matozoid** [comment]
Yes, it is something that would be really great, but is currently not working perfectly. We're not storing whitespace at all, and comments don't always work well. Fixing that would be a major change. For version 3.0 I'm looking for a dependable way of handling comments, but it seems there is no way that will please everyone, so now I'm thinking about not changing comment handling at all, but just attempting to fix issues as they come up.

**Comment by ThLeu** [comment]
Since this is my first comment here, I want to, first of all, thank you very much for working on the JavaParser. We came across it in our company and we currently use it for some automated refactoring and analysis and want to use it even more.

In our current state that we are using it, the biggest weak points for us are really the "lexical preservation" that is just not possible and that comments tend to go missing when we would like to use the CompilationUnit to store the file again. 
So our current "solution" is to just replace, in the file, whatever we changed in the CompilationUnit, it doesn't matter if we used a Visitor to change it or not. If it would be possible to use the Visitor to change and rewrite the file without lines getting moved around or reformatted (this is not the biggest concern since we use our formatter after the change anyway) and comments not getting lost would be my personal favourite.

So if I could "vote" on issues it would really be "Lexical preservation" and "Comments (or anything else for that matter) not getting lost".
I just wanted to give that as a feedback so you have some cases of what the JavaParser is used for by different people.

I could also have put that comment in the "Lexical Preservation" Issue, but this one seems more active currently.

**Comment by ftomassetti** [comment]
Thanks @ThLeu for your feedback. We should really focus on Lexical Preservation in the near future.

**Comment by matozoid** [comment]
And we will. I think we should somehow be more clear to user that we currently only have support for "this node seems to be commented by that comment," and no rewriting of comments or whitespace support. Only pretty printing is there. This seems to trip up many users.

It is the most important feature on the list, but it is a big task, so no promise that this functionality will be available soon.

**Comment by andycarlsonuk** [comment]
Just to add to this... the behaviour seems to depend on the content of the source. I'm also using JavaParser to parse and modify legacy code and have found it incredibly useful but noticed that some comments are being lost. This is an issue for me because the source often contains multiple comment lines explaining the business requirement.

In the test fragment below, the first two comment lines are preserved but the second group is not - only the last line of the second group appears in the output... this is without any visitors or modifications in use - just a straight parse of the source code and then toString() on the CompilationUnit. 

I'm using JavaParser 3.0.1

public class A { private void x() {
// This is a ...
// two line comment
	int x = 1;
// This is a ...
// two line comment
if (x < 2) {
	int i = 0;
}
//END

}}

**Comment by matozoid** [comment]
Correct, it's a weak spot in the comments implementation. Its purpose is to figure out which nodes comments belong to. Some don't have a sensible node that they belong to. All of this is heuristics, and maybe we shouldn't have used it for the pretty printer, because these heuristics are not reversable. They just happen to work for the common cases.

Say we have `void x() /*aaa*/ throws Y` - we cannot store this in the AST in a way that it can be printed in the same place again. That was never the purpose anyway.

What will help is the lexical preservation code that is being created in #654 - its goal is to print code exactly like it was read, including whitespace and comments. The negative there is that it will be difficult to handle comments, since you will have to look through the parsed tokens.

So there are two options: have easy comment support that drops all "difficult" comments, or have complex comment support that keeps all comments.

**Comment by matozoid** [comment]
This is identical to #263

**Comment by jlerbsc** [comment]
This issue seems to be resolved . I cannot reproduce it with this test case.

    void test() {
        String actual = 
                "public class TestDumpVisitor {\n" +
                        "\n" +
                        "   public boolean test() {\n" +
                        "       // line 1\n" +
                        "       // line 2\n" +
                        "       // line 3\n" +
                        "       return false;\n" +
                        "   }\n" +
                        "}\n" ;
        String expected = 
                "public class TestDumpVisitor {\n" + 
                "\n" + 
                "    public boolean test() {\n" + 
                "        // line 1\n" + 
                "        // line 2\n" + 
                "        // line 3\n" + 
                "        return false;\n" + 
                "    }\n" + 
                "}\n";
        CompilationUnit cu = StaticJavaParser.parse(actual);
        TestUtils.assertEqualsStringIgnoringEol(expected, cu.toString());
    }

**Comment by Wouter1** [comment]
Why was this closed? The original problem seems unchanged (tried on 3.24.4)
