### ISSUE TITLE
Make naming consistent

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#499]
- Make fieldnames the same as getter/setter names
- Use "...List" for nodes that are a list
- Only use abbreviations like "Expr" when it's not the only word in a name, so no more "getArgs()"

**Comment by matozoid** [comment]
- ArrayCreationExpr calls the element type just "type" where it should be "elementType" (add a getType here that adds ArrayType around it.)

**Comment by rosrossito** [comment]
Hi, I would like to try to fix this issue.

**Comment by matozoid** [comment]
Cool, the ArrayCreationExpr thing is already done.

**Comment by rosrossito** [comment]
Could you clarify the task?  I looked folder "body" and it seems that everything is fine there. Could you give me some example?

**Comment by matozoid** [comment]
How about ClassOrInterfaceDeclaration.extendsList and ConstructorDeclaration.throws_? EnumConstantDeclaration.args or arguments? InitializerDeclaration.isStatic and ClassOrInterfaceDeclaration.interface_? MethodDeclaration.typeParameters or typeParams?

**Comment by rosrossito** [comment]
I see.
Thank you.

2016-11-05 16:49 GMT+02:00 Danny van Bruggen notifications@github.com:

**Comment by rosrossito** [comment]
Is this necessary to make these changes in folder javaparser-testing also?

2016-11-05 20:20 GMT+02:00 Ruslan Omelchenko <
ruslan.omelchenko.irtcits@gmail.com>:

**Comment by matozoid** [comment]
That would be consistent. Do you have something we can look at already?

**Comment by rosrossito** [comment]
I changed all code except that folder.

2016-11-12 14:46 GMT+02:00 Danny van Bruggen notifications@github.com:

**Comment by matozoid** [comment]
Yes, that is not the question. This task is one of the last things to finish before the big 3.0 release and I have exactly in my mind how to do it and would like to get it done and I'm really eager to do it. Please show what you have been doing in the last three weeks or I'll take over and do it in a few hours.

**Comment by rosrossito** [comment]
Sorry I am not so fast. 
I pulled two request.
I still have problems with building project because of "maven-resources-plugin.version" in pom.xml of javaparser-testing.

**Comment by ftomassetti** [comment]
Hi @rosrossito , I do not think you created any pull request. You created your own fork and committed your changes in your fork.

You should have done those changes in a new branch (you did them on master instead) and after that you should have created a Pull Request. To do that you should visit [https://github.com/javaparser/javaparser/pulls](https://github.com/javaparser/javaparser/pulls) and use the button "New pull request".

The first thing I see in the changes you have done on master on your fork is that you changed some words in the licenses. I suspect you used some scripts to change the text, instead of doing that from inside the IDE.

It is great that you want to contribute and this is appreciated but maybe this is not the easiest task to start with.

Also, if you need help it is good to ask on the gitter channel: we try to help as much as we can (when we have the time to do so).

**Comment by rosrossito** [comment]
Hi,
I did not use any script, I made it in IDE using Refactor-rename.
Yes, I found out that there was also changes in licenses, that's why I made
second commit, where I change back license files.

Is it possible to transfer some how changes from my fork to new branch and
make pul request in order do noy loose that changes?
