### ISSUE TITLE
Null part 3

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#516]
First, roll back #451.

This leaves us with extensive runtime null checks, so not everything is lost, but it would be nice to have compile time feedback. I only know about @Nullable annotations for this. There are two problems: they require a library dependency, and they aren't standardized (there are many different sets.)

If nobody has a better idea, I can see if I can make a `javax.annotation.Nonnull` in javaparser-core and get intellij idea to recognize it.

**Comment by matozoid** [comment]
@DeepSnowNeeL please discuss here. I'm not going to start working on JavaParser again before we have a few people agreeing on what we want here.

**Comment by DeepSnowNeeL** [comment]
I suggest : 
For example taking the class : `AnnotationMemberDeclaration` with its actual field : `Optional<Expression> defaultValue`
- Going back to `Expression defaultValue`
- On the setter, take an Expression that can be null, with the javadoc clearly saying that it can be null 
- On the getter return an `Optional<Expression>` using `Optional.ofNullable(defaultValue)`

This way the API clearly suggest that this value might be optional when getting it, and states in javadoc when it can be null.

The setters for non-null fields will use Objects.requireNonNull() to runtime-check that it doesn't take nulls, with the javadoc clearly stating that it does not accept nulls with bold text + `@Throws` . (We can't rely on `@NonNull` annotations, since it's a dead JSR (305), and it only works with an external tool like intelliJ or findbugs, it won't prevent users to compile with javac) so javadoc is our best bet.

Who is for, who is against ? Express yourself below.

**Comment by matozoid** [comment]
For fields and setters I agree with @DeepSnowNeeL, but...
- I find it odd to have setters use nulls, and their getters use Optional. I'd rather pick one way of dealing with optionality, and since the internet seems to agree that you should only use Optional only as a return value, I'd prefer to not use it at all.
- JavaDoc should be well written, but is not "in your face" and often ignored.
- The big two IDE's have support for all kinds of nullability annotations. It's not perfect, but it is not hard to configure and will happily mark all your possible null dereferences in yellow :)

But for me it's mostly the first point.

@ftomassetti @SmiddyPence @mlangkabel ? Any idea how to get out of this impasse?

**Comment by matozoid** [comment]
(reverted the optional stuff on master in preparation of the outcome of this)

**Comment by matozoid** [comment]
@DeepSnowNeeL looks like nobody is all that interested in this subject. If you submit a PR it will go in.

**Comment by DeepSnowNeeL** [comment]
We can close this now with #536 merged

**Comment by matozoid** [comment]
I'll close it when I make the release.
