### ISSUE TITLE
Improve javaparser.org

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#586]
I was looking at this presentation: https://www.youtube.com/watch?v=J9moK3Lb5ZE about a project consisting of 80 lines of JavaScript which in this moment has exactly the same number of stars of JavaParser (785). Why? Because it is something more mainstream but also because it is probably better presented than JavaParser. Its website is [here](http://ellekasai.github.io/purplecoat.js).

I think we could build a better website for JavaParser with an homepage with a similar structure:

* define JavaParser in 3 lines
* present an example of code
* maybe use animated gifs (showing the methods found analyzing a piece of code, for example)

We could then list tutorials. For example I helped Sparkjava with their documentation and we built this: [https://sparktutorials.github.io/](https://sparktutorials.github.io/). It is a collection of tutorials. I contributed the first ones together with David and then more people started contributing. Now there are almost 20 tutorials. If we could get something like that for JavaParser I think that would be great.

Currently some people is visiting javaparser.org (or so it seems looking here: https://github.com/javaparser/javaparser/graphs/traffic) but there we are not providing much information. I think we could improve that and present better this piece of software.

What do you think?
What would be the best way to mantain such a website?

**Comment by matozoid** [comment]
I've been thinking of creating a simple diagram which shows what JavaParser actually does: show a tiny bit of source, the tokens, the AST, then solving a symbol. Just to give a realistic idea what it does.

I would also love an easy way to update stuff and keep any samples compilable. I think asciidoc is good at that - I think @bodiam used it for writing a book about Groovy (but that's just an idea.)

**Comment by matozoid** [comment]
How would you define JP in three lines?

**Comment by ftomassetti** [comment]
"JavaParser is a framework to analyze, refactor and generate Java code programmatically.

You can use it for..."

**Comment by matozoid** [comment]
Framework? Set of tools maybe? JSS included :)

Maybe a line about the advantages? "It's free and well supported."

**Comment by ftomassetti** [comment]
I would put the advantages below, with bullet points:

* It is open source and available under a business-friendly license
* It is well-supported
* It is mature
* It has a growing community
* It is lightweight and easy to use

Set of tools seem good. The only issue is that JavaParser is both one of the tools and also the name of the whole set of tools

**Comment by matozoid** [comment]
Yes, we have a slight branding issue here ;) Well, it can't be helped unless we want to turn the whole place upside down for a new name.

**Comment by ftomassetti** [comment]
Yes, we have to communicate as well as possible given the current situation :)
Or create a name for the whole brand (JavaTools?)

**Comment by ptitjes** [comment]
May I ask what is "the current situation" ?

I don't yell too much that [JLaTo](jlato.org)'s issue list and code serves as inspiration... (Even if I am a bit annoyed to see the pace at which you both are trying to incorporate such features that, at the time the project was LGPL, you rejected every bit of them coming from me.)
Semantic analysis (you re-coded a semantic analyser on your own, after having front row seat when I had done in JavaParser/model), parser front-end, error-recovery, and now query/traversal patterns (!!), ...

But now you want to choose "JavaTools" as a project name ??

**Comment by ftomassetti** [comment]
By "current situation" I was thinking about the naming situation: currently we call JavaParser bot the parser and the organization. By extension we call JavaParser the combination of JavaParser with JavaSymbolSolver.

I am sorry you felt your code was rejected. I do not remember when this happened, honestly. My code was rejected multiple times, mostly because of your opinions.

I do not know why you are annoyed by the development of JavaParser. However if your goal is not to help JavaParser and its community I think you should seriously consider stopping to pop up. In my opinion everyone should be welcome here until his/her goal is to help people with JavaParser. If you have resentment against the project well, I am sorry but this probably do not put you in the right mood to contribute to it or to his community.

Honestly my first attempt was to try building some of these features with you, until you just threw away my code and did it yourself. Fine, I have started playing with these concepts on my own time, without ever looking at your code (which is open-source anyway) and I have built first [effectivejava](https://github.com/ftomassetti/effectivejava) and then [JavaSymbolSolver](https://github.com/javaparser/javasymbolsolver). Are you perhaps accusing me to have stolen your ideas? Or your code, or your design?

I have now just suggested to consider "JavaTools" as a name and this make you upset for reasons that escape me...

Really, I have nothing against you and I have an hard time understanding why you are upset. We are building open-source stuff, sharing with others and trying to build something useful. We have included contributions from over 40 persons (since it is on GitHub), dealt with 300 issues and 250 Pull Requests.

This place is open: you want to contribute and help? Feel welcome.
However I get the feeling you are just coming here to promote your tool:

![selection_472](https://cloud.githubusercontent.com/assets/439078/20639863/95af2214-b3cf-11e6-94a7-3290a7450a22.png)

Your tool is not interoperable with JavaParser. You come here and start suggesting people to switch to your project or start discussing features of your project. I get you have to promote it but this is not the right place for doing so.

Please, explain us the reasons you believe we did not behave correctly but at the same time try to think hard to what you are bringing to this community.

You can have all the technical talent you want, but you have also to use it in the proper way to deliver value to people and respect a community and the interest of that community if you want to feel valued and your contributions appreciated.

**Comment by ptitjes** [comment]
@ftomassetti I'll try to answer without going in as much detail as you did.

First, you do know why I do not contribute any more code to JavaParser: because JavaParser changed its licence. I objected against it with some other people, but we were not enough and the licence change did happen. But, I had a lot of code in my clone repositories that had not yet make their way to master and lots of open issues from before the licence change. You know perfectly this is where my resent comes from.

About the mentioning of my tool, I also often help you on some stuff without even mentioning it and I again did very recently too. I also reported many JavaParser issues after the licence change. So I think you could ease it on the "think hard to what you are bringing to this community"...

(Important side note, about my tool being open-source, let me be clear again that it is free-software and not just open-source.)

Finally, you don't seem to understand why I do jump about your "JavaTools" name proposal for your organization umbrella. Then I just want to remind you that you don't have the monopole on Java parsers and semantic analysers. Sure having "Java Tools" as part of the name or slogan is obviously a good idea, but just "JavaTools" is a bit too much...

Maybe it is a good opportunity to find a name to put before "JavaParser" and "JavaSymbolSolver" !

(And sorry if I misread your sentence "Yes, we have to communicate as well as possible given the current situation :)"...)

**Comment by matozoid** [comment]
@ptitjes - this is completely irrelevant and seriously disturbing. A few weeks ago I met @ftomassetti at Splash 2016 and we talked to many people in the programming language and parsing community. We got a lot of nice ideas there, none of it influenced by you. I'm happy if you like to discuss things or contribute, but no project needs drama like the above. I'll remove all of this in a day or so because this is * an issue to talk about the web site for a project you're not part of * and not your personal drama space.

**Comment by ftomassetti** [comment]
I think it would be also useful to get Google analytics to find out who is linking to javaparser.org

**Comment by matozoid** [comment]
+1 from me for google analytics.

**Comment by matozoid** [comment]
@ftomassetti do you want to keep this issue open forever? I'd prefer splitting into concrete steps.

**Comment by ftomassetti** [comment]
Yes, we can close this one now and open specific issues in the website project
