### ISSUE TITLE
Make Compilation Unit parse errors recoverable

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#589]
Make a recovery strategy that skips to the end of the file, storing the whole file contents in a BrokenCompilationUnit or so. The result of this would be that parsing will always have a result.

Exceptions: when parsing a file and the file is not found, there is nothing to parse.

**Comment by tamtam22** [comment]
When analyzing some java files (e.g. from an APK) which are decompiled wrongly, it throws ParseProblemException, which is expected as it didn't fit any known tokens/syntax. e.g.

~~~~
if (this.down.getDownloadUrl().contains("url")) {
    /* anonymous class already generated */.start();
} else {
    /* anonymous class already generated */.start();
}
~~~~

To overcome this, I put a catch on ParseProblemException in try-catch block as I still want to parse my other java files. However, I believe this is definitely not the fix. Even though the problematic java files are caught in ParseProblemException and the catch block does nothing, at least it doesn't stop the program from terminating nor stop reading other java files. 

However, it later encountered StackOverflowError 

~~~~
Exception in thread "main" java.lang.StackOverflowError
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:52)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.accept(ClassOrInterfaceType.java:89)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:275)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:52)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.accept(ClassOrInterfaceType.java:89)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:275)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:52)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.accept(ClassOrInterfaceType.java:89)
.....
~~~~

So i think it would be great if parsing for this file can be skipped correctly and sacrifice parsing this file rather than terminating half-way through

**Comment by matozoid** [comment]
This is noted, and recovery is going up in importance as you are the second user to explicitly request it.

@jeandersonbc - will you find time for this soon? Otherwise I'll start on it.

For the stack overflow: can you send the source file that causes this? It should not happen (well, only in extreme cases.)

**Comment by jeandersonbc** [comment]
Given the high priority of this particular issue, please, go for it @matozoid 
I will be taking a look at the fixes for further help and assistance.

**Comment by matozoid** [comment]
@tamtam22 - note that you'll need to use the full API for recovery, look for "the full API" on https://github.com/javaparser/javaparser/wiki/Migration-Guide . Of course, it currently doesn't recover from much yet since this issue is still open.

**Comment by tamtam22** [comment]
Hi matozoid, thanks for the fast response! I followed the Migration guide and tested again, 

`ParseResult<Expression> parseResult = parser.parse(ParseStart.EXPRESSION, Providers.provider(file.toString()));`

parseResult.isSuccessful() is always **true** and getProblems() is empty :/

However, if I just use parser.parse(file) then it encounters error (e.g. Encountered unexpected token) during runtime. I guess this is more relatable to #582 or  #581 but nonetheless still under 'Error recovery'

**Comment by matozoid** [comment]
Okay, for the code you posted, read the source code for `JavaParser.parse` and `JavaParser.simplifiedParse` - it's six lines in total and should help you understand and fix your problem.

**Comment by tamtam22** [comment]
Thanks matozoid! To anyone else facing the same problem as me, do note that you should change the variables accordingly instead of following blindly with the migration guide's example.

So if you are checking CompilationUnit errors, do this:
~~~~
ParseResult<CompilationUnit> parseResult = parser.parse(ParseStart.COMPILATION_UNIT, Providers.provider(file));
~~~~
Reading the JavaParser.parse implementation would really help you with this!

P.S. can't find JavaParser.simplifiedParse method in 3.0.1. Is that on a newer version?

**Comment by matozoid** [comment]
Good work :)
`simplifiedParse` should be there - it's private though.

**Comment by martinlippert** [comment]
I wonder how I can use this recovering feature for the parser. When I am parsing a file with an error, like:

```
package org.test;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Scope;

@Scope(value=)
public class TestScopeCompletion {
	
	@Bean
	@Scope("onMethod")
	public Object myBean() {
		return null;
	}
}
```

I get the error report correctly, but the compilation unit doesn't contain any child nodes. Is there maybe something that I am doing wrong here?

**Comment by matozoid** [comment]
@martinlippert - here's a bit of documentation: https://matozoid.github.io/2017/06/11/parse-error-recovery.html
