### ISSUE TITLE
Unable to build?

### ISSUE THREAD

**Issue by cciollaro** [javaparser/javaparser#60]
Hi guys,
I'm wondering if there are build instructions? Currently I've cloned the repo and imported it to eclipse but there are a few errors and the structure is strange. Are there special steps that need to be taken?

<img src="http://i.imgur.com/uaNmXjQ.png">

--Chris

**Comment by SmiddyPence** [comment]
Hi Chris

You need to run the javacc goal if you have checked out the source before it will build.

From the root of the project run `mvn javacc:javacc`. 

Then a basic `mvn clean install` should work.  If eclipse is still complaining try re-importing and make sure you select the options for importing as an existing maven project.

If that still doesn't work, let us know the compilation errors from the problems tab.

Incidentally if you just want to use the parser rather than get into the source you can include the mvn dependency:

```
<dependency>
    <groupId>com.google.code.javaparser</groupId>
    <artifactId>javaparser</artifactId>
    <version>1.0.11</version>
</dependency>
```

or download the jar.

http://repo.maven.apache.org/maven2/com/google/code/javaparser/javaparser/1.0.11/javaparser-1.0.11.jar

**Comment by ftomassetti** [comment]
Probably we could document the building process.

**Comment by cciollaro** [comment]
It's definitely my own fault for not knowing how to use Maven, but it also couldn't hurt to add that info to the project somewhere. If not, at least it's here now.

Thanks!

**Comment by ftomassetti** [comment]
Providing documentation for the build process is now #61
