### ISSUE TITLE
JavaParser interprets Unicode escape sequences in comments

### ISSUE THREAD

**Issue by Gottox** [javaparser/javaparser#600]
In JavaParser 3.0.0 alpha 10 Unicode escape sequences are interpreted. This results in the following behavior:

```java
JavaParser.parse("class Foo { /* \\u002e */ }").toString()
```
expected result:
```java
class Foo {
    /* \u002e */
}
```

actual result:
```java
class Foo {
    /* . */
}
```

**Comment by matozoid** [comment]
See #209, I'm afraid that's currently unfixable. I'll leave this issue open as a reminder.

**Comment by digulla** [comment]
Note that the Java compiler does the same. Interpretation of Unicode escape sequences happens in the lexer, before tokenization, so the parser never sees the original input.

This is the reason why code like `/* C:\User\... */`doesn't compile ("ser" is not a valid Unicode escape sequence).

**Comment by Gottox** [comment]
That's true, But keep in mind that javaparser can be used to alter java source code. This results in undesired source code mutations.

**Comment by digulla** [comment]
It's an unexpected side effect. The source code (as seen by the Java compiler) is exactly the same.

While I understand that you'd like to keep this information around, I don't know a good way to implement this in any parser/lexer framework. 

In your example, you just want this for comments. But you need to be able to remember the information for every single character of the input (`cl\u0061ss` is a perfectly valid way to write `class`). And let's not forget that you can mix upper/lowercase in Unicode escapes. So you actually need to remember the exact input, a single bit of "this was a Unicode escape" isn't enough.

I'm thinking that you would probably use this for specific cases. Like keeping Japanese characters readable on non-Unicode terminals. So I'd suggest to encode those rules in a pre/post processor and wrap javaparser with it.

Note: I've implemented this for my XML parser DecentXML. It will remember the exact input plus the type of the token. This was possible mostly because XML is so simple and repetitive. I wouldn't try that for Java.

**Comment by ftomassetti** [comment]
A related PR to consider it here https://github.com/ftomassetti/javaparser/pull/5/files, courtesy of @cal101
