### ISSUE TITLE
DumpVisitor should use the Position information to insert appropriate new lines

### ISSUE THREAD

**Issue by theangrydev** [javaparser/javaparser#606]
Currently, if a chained method call is over multiple lines like:
```
foo()
    .bar()
    .whatever();
```

Then the `Statement` renders as `foo().bar().whatever()` (without the new lines) when the `toString` method is called (which delegates to the `DumpVisitor`).

The `Position` information in `getBegin` and `getEnd` should hopefully be enough to determine where to insert the new lines to match the original source.

**Comment by ftomassetti** [comment]
Thanks for sharing this with us. Unfortunately I think that it is not that simple. We are planning to support lexical preservation in the future but this is not going to be as trivial as it seems for a variety of reasons.

Sure, if we parse a source file and then we want to dump it exactly as it is we could use the position and get the original file back. However this is not the case as soon as we change in any way the file.

New nodes do not have valid positions. Someone would need to insert that. Existing nodes that get changed should have their positions adapted. We should also consider that any node added or changed would require to adapt the positions of all nodes following.

So basically we cannot consider the position. It would even be very difficult to ensure the position is legal. For example if I have an identifier `Foo` I will need to ensure get `getBegin` and `getEnd` return positions separated by 3 characters. A bracket or a parenthesis could follow the ID without no spaces in between, so if a Node starting with a bracket or a parenthesis follows my ID node its begin position can be the same as the end position of my Node. However if the Identifier was followed by a keyword or another identifier we would need to have some spaces in between, otherwise it would lead to code that is parsed differently. Aspects like this are not trivial to consider.

There are many other things to consider to implement Lexical Preservation correctly. I have been experimenting with it using our observer mechanism and I plan to blog about that in the near future to start collecting some feedback on the ideas.

Comments or help on this feature are really welcome because we realize this is very important for the users of JavaParser.

**Comment by theangrydev** [comment]
For my particular use case, I am using the parser in a read only fashion, not modifying the parse tree at all.

I can appreciate how this is much more difficult when you allow modifications though.

My workaround at the moment is to just copy paste the `DumpVisitor` and change it to suit my needs.

Something that could work even with modifications is having different rendering style options, one of which could be a convention of putting chained method calls on new lines.

**Comment by theangrydev** [comment]
Come to think of it, something like a pretty printer that works in a similar way to e.g. an IDE auto format feature with lots of configurable options makes a lot of sense to me. That also sounds a lot easier to implement than tracking and maintaining the positions when making modifications.

**Comment by matozoid** [comment]
Hello, for version 3.0 we have renamed DumpVisitor to PrettyPrinter, since that is what it does. No new options for formatting yet, but there are some on the issue list (would you like to comment or contribute?) And as @ftomassetti said, the current version cannot not keep formatting or comments well, but we'll work on that.

**Comment by matozoid** [comment]
@theangrydev is it okay if I close this? The main issue is here: #124.

**Comment by theangrydev** [comment]
Sure, fine by me

**Comment by matozoid** [comment]
Oh, excuse me, the prettyprinter issues are over here: #541, #542, #543, #544, #545, #546.
