### ISSUE TITLE
Add visitor property to PrettyPrinter

### ISSUE THREAD

**Issue by xiewenya** [javaparser/javaparser#644]
How about make visitor configurable in class PrettyPrinter so that we can easily customize the printer. Or maybe add a abstract printer class

**Comment by matozoid** [comment]
Hmmm, I'm in an architectural discussion with myself about this now :)

Is your request...
1. I would like to use print my AST in a slightly different way by adapting the current PPVisitor?
2. I would like to print the AST in a drastically different way by writing a different visitor?
3. I would like to change the behaviour of toString() ?

Because in my mind, the PrettyPrinter is a package we offer that will print your AST, and its behaviour is changed by changing its configuration, not by passing a completely different visitor.

But, since we are going to work on generating more visitors, we also have to solve the problem of "which visitor do we use for toString, hashcode, etc" - so we're probably going to make that configurable as well.

**Comment by xiewenya** [comment]
nice to learn how you think :P
now I understand why the visitor is final in the first place.

I would like to print the AST into h5 format, that's why a configurable visitor would make it much easier.

**Comment by matozoid** [comment]
Okay, my advice would be to subclass a ...VisitorAdapter and write your own thing, then use the visitor pattern: call accept on a node with that visitor.  That's what the PrettyPrinter does too.

But you do have a point that if someone wants to modify the PP visitor even a little bit, the PrettyPrinter class becomes useless. Okay, we'll pick it up :)
