### ISSUE TITLE
com.github.javaparser.ast.expr.MethodReferenceExpr and com.github.javaparser.ast.expr.TypeExpr do not set themselves as parent of their child nodes

### ISSUE THREAD

**Issue by sebastiankirsch** [javaparser/javaparser#88]
No surprise after #82, but I didn't catch it immediately. Will provide a fix.

**Comment by sebastiankirsch** [comment]
Hm, while writing a test (every node has to have a parent set), I noticed that there's a some more nodes that don't set themselves as parent:
- comments have an additional `commentedNode` field which practically serves the same purpose as the `parent` field, but they don't have a parent set
  - an `ImportDeclaration` does not set itself as parent of its `NameExpr`
  - one of the two constructors of `QualifiedNameExpr` misses to set itself as parent of its `NameExpr`

I'll fix the import declaration as well as the qualified name expression; not sure about the comment however. I'd probably leave them be... any suggestions?

**Comment by ftomassetti** [comment]
As I remember things to be (and I could definitely be wrong):
- I think that the commentedNode and the parent are tipically two different nodes: a comment tend to be applied to an element at its own level, not to its container.
- Comments are added after parsing and behave differently because they could be put everywhere, so they do not fit as nicely as other nodes in the AST.

I think it is something we should clarify and if comments do not have parents maybe they should not have the methods get/set parent. Maybe they should not derive from Node but from some ancestor of Node containing the code common to proper nodes and comments.
