### ISSUE TITLE
Duplicate default modifier of interface's default method in java 8

### ISSUE THREAD

**Issue by phamanhminh1208** [javaparser/javaparser#887]
I use javaparser version 3.2.0 to modify existing java 8 source code but it always duplicate the default modifier of default method of interface like below:

Before modifying:
```
default boolean doSomething(){
    return false;
}

```
But after modifying it became:
```
default default boolean doSomething(){
   return false;
}


```
P/S: I'm sure that I just modify inner source code in method and do not modify modifier of any method in project.

**Comment by matozoid** [comment]
Woops! This bug was created in the latest release, `default` was turned into a normal modifier instead of a dedicated field, and the pretty printer prints the modifiers (which now include `default`) but also still checks the dedicated field.

It will be fixed in the next version (and shouldn't occur in the previous version.)
