### ISSUE TITLE
FieldDeclaration or MethodDeclaration should not auto-reorder the nodes (or provide a way to get the original raw text if necessary)

### ISSUE THREAD

**Issue by mattsnider** [javaparser/javaparser#912]
I was trying to use this parser to validate that annotations are added in the correct order. The validation function is provided an instance of either FieldDeclaration or MethodDeclaration, and needs to determine if the annotations are in the correct order. The following, for example, would be valid:

@Nullable private int mVariable = 1;

But the following, would not:

private @Nullable int mVariable = 1;

However, the NodeList provided to FieldDeclaration (or MethodDeclaration) has already separated the annotations from the other modifiers, putting the annotations first, regardless of how they appeared in the raw Java code. Consequently, you can't identify the second example from an instance of FieldDeclaration.

One way to fix it would be to preserve the order in the NodeList that elements appear in the raw Java (or having a second NodeList to maintain this). A less good way, would be to expose the raw string.

**Comment by matozoid** [comment]
Changes for this are considered for version 4, which will probably be released next year.

Maybe @ftomassetti can add some direct tips, since he created the lexical preservation code?

**Comment by ftomassetti** [comment]
Mmm, I am not an expert in annotations but the I think that they are now allowed to be used in all sort of crazy places. I wonder if the second example you reported should be considered as an annotation to the return type, instead than an annotation to the whole method. In that case we will need to reflect it into the AST. If instead it is just equivalent to the first case we should consider it differently. I am not sure what you want to do, but regardless of how annotations are inserted in NodeList the annotation should have a position that you could use. You could see if their position correspond to the start of the field or not. If that is not the case and the field has a modifier than you can recognize your incorrect case. The issue here is that we do not have an easy way to get the position of the modifiers. Am I correct @matozoid ?

The Lexical Preservation mechanism should have the position of all tokens (include `private`, `public`, etc), however it is not exposed. Maybe we should change that?

**Comment by matozoid** [comment]
Modifiers are reduced to a set of enums, so there is no more information than "exists or not". This should change in 4, but it will break too much code to do it now. We could make it available in the LP code, but should it be? If it is only to temporarily fix the modifier problem, we would want to reverse it when that is fixed...

**Comment by matozoid** [comment]
Additional, and pretty horrible way to do it: look through the token list...

**Comment by mattsnider** [comment]
Thanks for the quick replies. The  Lexical Preservation sounds exactly like what I'm looking for. In the meantime, if I wanted to look through the token list what's the best way?

**Comment by DeepSnowNeeL** [comment]
I think you can look at the range too ? and just compare the positions that
way for now ?

**Comment by matozoid** [comment]
The token list can be accessed in the `ParseResult` when using the "full API" - look at https://github.com/javaparser/javaparser/wiki/Migration-Guide which has a paragraph about it.

@DeepSnowNeeL - modifiers don't have ranges :-(

**Comment by matozoid** [comment]
Modifiers are now real nodes, so they have ranges too :-) They are not mixed with annotations, so the original problem is only half solved, but there is nothing keeping you from putting all annotations and modifiers in a nodelist and sorting them on position.

Mixing them together won't happen anytime soon. @mattsnider, if you're still around, is this enough to fix the problem?
