### ISSUE TITLE
Is it possible to visit a method's definition from a call to it

### ISSUE THREAD

**Issue by arjunbinsevarghese** [javaparser/javaparser#973]
Hi, I am trying to generate a control flow graph for the functions inside a java project. I am able to find the methods called inside a method body. But now i want to visit the method's which are called. This has to be done recursively. Is it possible to do it with javaparser and javasymbolsolver?

**Comment by matozoid** [comment]
@ftomassetti should know.

**Comment by ftomassetti** [comment]
Yes and no. With JavaSymbolSolver is possible to find the corresponding [MethodDeclaration](http://static.javadoc.io/com.github.javaparser/java-symbol-solver-model/0.5.5/com/github/javaparser/symbolsolver/model/declarations/MethodDeclaration.html). This can correspond to:
* a method loaded from a JAR
* a method obtained through reflection (typically for java.* classes)
* a method declared in a source file

In the latter case you can also get the AST while in the first two cases you cannot. In practice if your JSS MethodDeclaration is an instance of [JavaParserMethodDeclaration](http://static.javadoc.io/com.github.javaparser/java-symbol-solver-core/0.5.5/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserMethodDeclaration.html) you can call `getWrappedNode` and obtain the JavaParser MethodDeclaration, so that you can navigate the statements. In other cases you cannot.

Hope it helps

**Comment by matozoid** [comment]
No more response, assuming answered.
